# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonWorkdayWql < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-workday-wql/releases/download/v0.2.2/baton-workday-wql-v0.2.2-darwin-amd64.zip"
      sha256 "4af6778641530ba5db4d71920b061eed4f02560d0f4d872dfc6936245f3fcbb1"

      def install
        bin.install "baton-workday-wql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-workday-wql/releases/download/v0.2.2/baton-workday-wql-v0.2.2-darwin-arm64.zip"
      sha256 "5b22bd2fd698a2b9408cbb2bb5ba7bf7febeea23a783afa1819655a6af8e246a"

      def install
        bin.install "baton-workday-wql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-workday-wql/releases/download/v0.2.2/baton-workday-wql-v0.2.2-linux-amd64.tar.gz"
      sha256 "5462d98b8d822e1d2ee9e343f427add0a5477669c92885358dc65a2535b3aacd"
      def install
        bin.install "baton-workday-wql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-workday-wql/releases/download/v0.2.2/baton-workday-wql-v0.2.2-linux-arm64.tar.gz"
      sha256 "5faaccf0097c0f098a4bf4272011e3266f1042934a42b25b73992476732969a5"
      def install
        bin.install "baton-workday-wql"
      end
    end
  end

  test do
    system "#{bin}/baton-workday-wql -v"
  end
end
