# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonPercipio < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-percipio/releases/download/v0.0.4/baton-percipio-v0.0.4-darwin-amd64.zip"
      sha256 "f6839153ab0da87d111209c9bb7a68adb04e57f2cbdbadccfbf681bd7353659d"

      def install
        bin.install "baton-percipio"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-percipio/releases/download/v0.0.4/baton-percipio-v0.0.4-darwin-arm64.zip"
      sha256 "e75258e07edc543c386541b40d8e6f671732a8be8ce47d0f4e9255ca70ee1150"

      def install
        bin.install "baton-percipio"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-percipio/releases/download/v0.0.4/baton-percipio-v0.0.4-linux-amd64.tar.gz"
        sha256 "9d02cf0785fd6ec2c1c25a3b6ac44c2ded7acd21b761376f7a0d0ec16425a84d"

        def install
          bin.install "baton-percipio"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-percipio/releases/download/v0.0.4/baton-percipio-v0.0.4-linux-arm64.tar.gz"
        sha256 "a1492c0499da8e0ae79ef12c433d0d709c274b8e84b68611e6c7f24d2ce9e718"

        def install
          bin.install "baton-percipio"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-percipio -v"
  end
end
