# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonVultr < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-vultr/releases/download/v0.2.0/baton-vultr-v0.2.0-darwin-amd64.zip"
      sha256 "c7f34b6a89800b7a60250d284f04066129f098b7912a6e65ecff324f5761f12b"

      def install
        bin.install "baton-vultr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-vultr/releases/download/v0.2.0/baton-vultr-v0.2.0-darwin-arm64.zip"
      sha256 "b155c6d02230b4b34251a480a8c78b49b695355b0de81d6c6bdaadfc05f07d02"

      def install
        bin.install "baton-vultr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-vultr/releases/download/v0.2.0/baton-vultr-v0.2.0-linux-amd64.tar.gz"
      sha256 "b46b0379fc8573cfdd774418f727290710ba8a10556974985f908a22f882f534"
      def install
        bin.install "baton-vultr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-vultr/releases/download/v0.2.0/baton-vultr-v0.2.0-linux-arm64.tar.gz"
      sha256 "6a1bc975144103d148ea323831bd485d21719f756569d599cf1655f7dbd08961"
      def install
        bin.install "baton-vultr"
      end
    end
  end

  test do
    system "#{bin}/baton-vultr -v"
  end
end
