# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonDayforce < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.2.2-alpha.19"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-dayforce/releases/download/v0.2.2-alpha.19/baton-dayforce-v0.2.2-alpha.19-darwin-amd64.zip"
      sha256 "a7e101a4c620eebdd9cfe084cd60ec6a19ce61506e8064035cdfe919f2978733"

      def install
        bin.install "baton-dayforce"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-dayforce/releases/download/v0.2.2-alpha.19/baton-dayforce-v0.2.2-alpha.19-darwin-arm64.zip"
      sha256 "e73667f707a58749f7bdb364ea2affc1fddce73dec033b4dc0c43be7948b2eb0"

      def install
        bin.install "baton-dayforce"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-dayforce/releases/download/v0.2.2-alpha.19/baton-dayforce-v0.2.2-alpha.19-linux-amd64.tar.gz"
        sha256 "ca8154ecefea8f951505cc4ee05dca826b7e08748d8f511f12339b0cec4cf430"

        def install
          bin.install "baton-dayforce"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-dayforce/releases/download/v0.2.2-alpha.19/baton-dayforce-v0.2.2-alpha.19-linux-arm64.tar.gz"
        sha256 "294eacea525f8f8ba6d91329a347e40956eb84cbebe9be8a060b8661439916eb"

        def install
          bin.install "baton-dayforce"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-dayforce -v"
  end
end
