# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonDelinea < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-delinea/releases/download/v0.1.1/baton-delinea-v0.1.1-darwin-amd64.zip"
      sha256 "56f125fcfdeb6cf8800beea29d54773491d0e16f33fcd3dead23f3a1f0862193"

      def install
        bin.install "baton-delinea"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-delinea/releases/download/v0.1.1/baton-delinea-v0.1.1-darwin-arm64.zip"
      sha256 "77f5f2900795c41ef652bb93781afc8114ae66f42c16c79d928843c557079bd2"

      def install
        bin.install "baton-delinea"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-delinea/releases/download/v0.1.1/baton-delinea-v0.1.1-linux-amd64.tar.gz"
      sha256 "1d48cee2a74a143e711bc128bf3f6de5e783e7f25494c7be7fad9dd9756ebeb0"
      def install
        bin.install "baton-delinea"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-delinea/releases/download/v0.1.1/baton-delinea-v0.1.1-linux-arm64.tar.gz"
      sha256 "183c681258bebddd158e6a0a2723ea7c2bbf46ad3867e73383617087d35159ec"
      def install
        bin.install "baton-delinea"
      end
    end
  end

  test do
    system "#{bin}/baton-delinea -v"
  end
end
