# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonGithub < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-github/releases/download/v0.1.6/baton-github-v0.1.6-darwin-arm64.zip"
      sha256 "93e6f44fb51f15eaac9e6fcbf4a018954674b64f7de5d03b638287bd679a8ebf"

      def install
        bin.install "baton-github"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-github/releases/download/v0.1.6/baton-github-v0.1.6-darwin-amd64.zip"
      sha256 "e1f831824d8708892471c7c406d06f537f33d5d5296f86db68fcd9fde9a874a5"

      def install
        bin.install "baton-github"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-github/releases/download/v0.1.6/baton-github-v0.1.6-linux-arm64.tar.gz"
      sha256 "0950d80999c76e62551dc047817b212667d2f38fe5ee16c6cc4cf9538f501ae4"

      def install
        bin.install "baton-github"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-github/releases/download/v0.1.6/baton-github-v0.1.6-linux-amd64.tar.gz"
      sha256 "2bc404dcddeb071caf0dd042e45b3de8dc397453b02d524d9438eafebd3c9947"

      def install
        bin.install "baton-github"
      end
    end
  end

  test do
    system "#{bin}/baton-github -v"
  end
end
