# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class BatonPostgresql < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-postgresql/releases/download/v0.0.2/baton-postgresql-v0.0.2-darwin-amd64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3d64ac1f98f73ce07a3fb08ec7d08b82b10039d3a452e9837b431a526d89342e"

      def install
        bin.install "baton-postgresql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-postgresql/releases/download/v0.0.2/baton-postgresql-v0.0.2-darwin-arm64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "947de6edb52f53204cf85f9502bdfce7460f178fffac3e31571219261a4efc0a"

      def install
        bin.install "baton-postgresql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-postgresql/releases/download/v0.0.2/baton-postgresql-v0.0.2-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "06a116745ebeac3c9fb606aa4d38f21ddcdecdbc62406573c3aa99a1a56a5a68"

      def install
        bin.install "baton-postgresql"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-postgresql/releases/download/v0.0.2/baton-postgresql-v0.0.2-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4e5d9212b915464d4b5e2294111f8146f68259a4cd4f0901dc786f0efd666f29"

      def install
        bin.install "baton-postgresql"
      end
    end
  end

  test do
    system "#{bin}/baton-postgresql -v"
  end
end
