# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonWiz < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-wiz/releases/download/v0.0.10/baton-wiz-v0.0.10-darwin-amd64.zip"
      sha256 "7c7f986ba43a13b229b5d8c6b2d94564dad454b31da29b1c37ebe2a80a9eda7c"

      def install
        bin.install "baton-wiz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-wiz/releases/download/v0.0.10/baton-wiz-v0.0.10-darwin-arm64.zip"
      sha256 "1b509b799aac42e193096a0c5fa9a0004d1c3068644c17351f741bd30af87852"

      def install
        bin.install "baton-wiz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-wiz/releases/download/v0.0.10/baton-wiz-v0.0.10-linux-amd64.tar.gz"
        sha256 "bd9d1b26be5a450e48775157164d03964670e2ea3adb891daf0dc7c178f3dcac"

        def install
          bin.install "baton-wiz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-wiz/releases/download/v0.0.10/baton-wiz-v0.0.10-linux-arm64.tar.gz"
        sha256 "94dfd441d3ddfc89a2386c5d8ac33e6ed4870a94760bbed24f3310f9857b0be1"

        def install
          bin.install "baton-wiz"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-wiz -v"
  end
end
