# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonBitbucket < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-bitbucket/releases/download/v0.0.6/baton-bitbucket-v0.0.6-darwin-arm64.zip"
      sha256 "d9ab68e2a2c72ccf29b2a4c35525f9fbe41e1f5c9819c2abc8472bfc979f281e"

      def install
        bin.install "baton-bitbucket"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-bitbucket/releases/download/v0.0.6/baton-bitbucket-v0.0.6-darwin-amd64.zip"
      sha256 "dcb8310004a1756d590cf32895868b5c106494a41218a62761c07120b2709c31"

      def install
        bin.install "baton-bitbucket"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-bitbucket/releases/download/v0.0.6/baton-bitbucket-v0.0.6-linux-arm64.tar.gz"
      sha256 "7c03640ac93396ca08b161f8e4a47ab31b26035d48e997b143aabe89afae659b"

      def install
        bin.install "baton-bitbucket"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-bitbucket/releases/download/v0.0.6/baton-bitbucket-v0.0.6-linux-amd64.tar.gz"
      sha256 "d4a96590c7c468d133673bcbdcbaf9581b9bc436fbe4e8ae6d0d45c279c5ab62"

      def install
        bin.install "baton-bitbucket"
      end
    end
  end

  test do
    system "#{bin}/baton-bitbucket -v"
  end
end
