# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonHaloServiceDesk < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-halo-service-desk/releases/download/v0.0.1/baton-halo-service-desk-v0.0.1-darwin-amd64.zip"
      sha256 "222abc5258bf102d570cbb6d4a061c2783a92e5a192ddbd7de1ff98b6883de8c"

      def install
        bin.install "baton-halo-service-desk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-halo-service-desk/releases/download/v0.0.1/baton-halo-service-desk-v0.0.1-darwin-arm64.zip"
      sha256 "dc8089c7932233f0b3449906578b122b3574048a0ef55245d1744410b010962b"

      def install
        bin.install "baton-halo-service-desk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-halo-service-desk/releases/download/v0.0.1/baton-halo-service-desk-v0.0.1-linux-amd64.tar.gz"
        sha256 "405f95f83465898df868d09bfb1c8ec2bc900148020ab3785f4d0593842becf7"

        def install
          bin.install "baton-halo-service-desk"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-halo-service-desk/releases/download/v0.0.1/baton-halo-service-desk-v0.0.1-linux-arm64.tar.gz"
        sha256 "b2211459b9d733bdd23bd30c390448a4e058537774dc1214c4120fc1897a3657"

        def install
          bin.install "baton-halo-service-desk"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-halo-service-desk -v"
  end
end
