# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonFloqast < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-floqast/releases/download/v0.0.1/baton-floqast-v0.0.1-darwin-amd64.zip"
      sha256 "8e4910b5ce2a63b33358ac511dacb4a54ffa93aa51190d0cc36ac79573d64e06"

      def install
        bin.install "baton-floqast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-floqast/releases/download/v0.0.1/baton-floqast-v0.0.1-darwin-arm64.zip"
      sha256 "f4f4761d3be3c6118090d2fbc61196525c59987d6d7eacaa256f750c746d13e2"

      def install
        bin.install "baton-floqast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-floqast/releases/download/v0.0.1/baton-floqast-v0.0.1-linux-amd64.tar.gz"
        sha256 "202967c75cb7fa331f2bb524f177a241931e0ad7fa04178f52a5fedc8c7cd6d3"

        def install
          bin.install "baton-floqast"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-floqast/releases/download/v0.0.1/baton-floqast-v0.0.1-linux-arm64.tar.gz"
        sha256 "474a98c16d77a8b12e92d32d7e5467279fe23819856858b59c1e7ccbed7271b6"

        def install
          bin.install "baton-floqast"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-floqast -v"
  end
end
