# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonDayforce < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-dayforce/releases/download/v0.0.4/baton-dayforce-v0.0.4-darwin-amd64.zip"
      sha256 "9a8a504594bf2b011270198d57ee17f809a8b84cb4e3c537c20db26d3dcccf15"

      def install
        bin.install "baton-dayforce"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-dayforce/releases/download/v0.0.4/baton-dayforce-v0.0.4-darwin-arm64.zip"
      sha256 "a89095e4578dbba8c123245390faf042c27bd79ef77e70d6ff1956fda63216d6"

      def install
        bin.install "baton-dayforce"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-dayforce/releases/download/v0.0.4/baton-dayforce-v0.0.4-linux-amd64.tar.gz"
      sha256 "8d33376a87c8beac1d5596999c046aa2f229d59976937fca83f744bb3196ef75"
      def install
        bin.install "baton-dayforce"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-dayforce/releases/download/v0.0.4/baton-dayforce-v0.0.4-linux-arm64.tar.gz"
      sha256 "7906b9d96940d17e787e1262c0974059943115be62254f9967703ee36797502b"
      def install
        bin.install "baton-dayforce"
      end
    end
  end

  test do
    system "#{bin}/baton-dayforce -v"
  end
end
