# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSnipeIt < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-snipe-it/releases/download/v0.0.1/baton-snipe-it-v0.0.1-darwin-amd64.zip"
      sha256 "0fd1c2ec84898278fc85eeaf924854aec0c079368e7a458bcd88ced84559f5ba"

      def install
        bin.install "baton-snipe-it"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-snipe-it/releases/download/v0.0.1/baton-snipe-it-v0.0.1-darwin-arm64.zip"
      sha256 "b29cd5a0988a53144d63d569fdadef37440000e1bb06ef12860645db6debee99"

      def install
        bin.install "baton-snipe-it"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-snipe-it/releases/download/v0.0.1/baton-snipe-it-v0.0.1-linux-arm64.tar.gz"
      sha256 "50d972062a01da4b0ec400a6916c726e5e514ee778e8446232c00d136758a71c"

      def install
        bin.install "baton-snipe-it"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-snipe-it/releases/download/v0.0.1/baton-snipe-it-v0.0.1-linux-amd64.tar.gz"
      sha256 "0d7489cef249574af222cfd800f65622cc3b35c157f50f35278c3cdb06e75abb"

      def install
        bin.install "baton-snipe-it"
      end
    end
  end

  test do
    system "#{bin}/baton-snipe-it -v"
  end
end
