# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonRippling < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-rippling/releases/download/v0.0.3/baton-rippling-v0.0.3-darwin-amd64.zip"
      sha256 "2ba50d7dcca98361e4e69998e6b7aabda46e59d44972b05ac8e885ba28738bd4"

      def install
        bin.install "baton-rippling"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-rippling/releases/download/v0.0.3/baton-rippling-v0.0.3-darwin-arm64.zip"
      sha256 "930efba7b6be69f0e75ede88f56476e21e667e60fc7b2b004f2720ed0dcea3d6"

      def install
        bin.install "baton-rippling"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-rippling/releases/download/v0.0.3/baton-rippling-v0.0.3-linux-amd64.tar.gz"
      sha256 "d7ce38f989c60dc0b7e4b496845bbb978ffafd68f0ac065d0f8eabbedc894b84"
      def install
        bin.install "baton-rippling"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-rippling/releases/download/v0.0.3/baton-rippling-v0.0.3-linux-arm64.tar.gz"
      sha256 "efe537bcbdbaee1088e7287c9b34f2f0a287c06c7e449220743fcfbe28aa8d52"
      def install
        bin.install "baton-rippling"
      end
    end
  end

  test do
    system "#{bin}/baton-rippling -v"
  end
end
