# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonHttp < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-http/releases/download/v0.1.0/baton-http-v0.1.0-darwin-amd64.zip"
      sha256 "394364a94a467a2c57d598a96324f758d2ff1bc74e6ac41014182db9ddcd4b69"

      def install
        bin.install "baton-http"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-http/releases/download/v0.1.0/baton-http-v0.1.0-darwin-arm64.zip"
      sha256 "090dce23c5ebdf028336f28e8e3cd9b7b8ab465d70fc7487a7d45f31561df88c"

      def install
        bin.install "baton-http"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-http/releases/download/v0.1.0/baton-http-v0.1.0-linux-amd64.tar.gz"
      sha256 "787dc25c9d02341fd052e7f448c1b97932c4c8aefefc1b9eea22fe8abcebe7a2"
      def install
        bin.install "baton-http"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-http/releases/download/v0.1.0/baton-http-v0.1.0-linux-arm64.tar.gz"
      sha256 "2346074c234ddc5085c5d0e2d1017ea640d9afa96644e760e63e17b07a513e85"
      def install
        bin.install "baton-http"
      end
    end
  end

  test do
    system "#{bin}/baton-http -v"
  end
end
