# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonWizWin < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-wiz-win/releases/download/v0.0.3/baton-wiz-win-v0.0.3-darwin-amd64.zip"
      sha256 "95176345f7427a02338d4791e7c44ceca4f01dc98d831ebfbc902f15c712b751"

      def install
        bin.install "baton-wiz-win"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-wiz-win/releases/download/v0.0.3/baton-wiz-win-v0.0.3-darwin-arm64.zip"
      sha256 "0b70ee7a451e4e5a74fd6f0e1088ecfbd0e3b9797f8bafc4177dfba175b8906c"

      def install
        bin.install "baton-wiz-win"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-wiz-win/releases/download/v0.0.3/baton-wiz-win-v0.0.3-linux-amd64.tar.gz"
      sha256 "2dd67583c0d043d4e04c5f027c3a814d1d0f62a7da506137734358a690e3ab05"
      def install
        bin.install "baton-wiz-win"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-wiz-win/releases/download/v0.0.3/baton-wiz-win-v0.0.3-linux-arm64.tar.gz"
      sha256 "d665072bd396fe61475be245be0907c759c7567b4a7e8f5b6993a3c7d818419a"
      def install
        bin.install "baton-wiz-win"
      end
    end
  end

  test do
    system "#{bin}/baton-wiz-win -v"
  end
end
