# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonLinear < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.19"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-linear/releases/download/v0.0.19/baton-linear-v0.0.19-darwin-amd64.zip"
      sha256 "af78b26610a49765d363aeae4f8d6a726dcd67000ba8a1a366d8d522c9f955a4"

      def install
        bin.install "baton-linear"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-linear/releases/download/v0.0.19/baton-linear-v0.0.19-darwin-arm64.zip"
      sha256 "21cf6a0ced8de7936bed0bd18b2771d938a151caea284400e625529aa1355a76"

      def install
        bin.install "baton-linear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-linear/releases/download/v0.0.19/baton-linear-v0.0.19-linux-amd64.tar.gz"
        sha256 "a06f01e8fc5151d32b1299db67c2901b7fdddc31d34fed8a854072ec285c9c92"

        def install
          bin.install "baton-linear"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-linear/releases/download/v0.0.19/baton-linear-v0.0.19-linux-arm64.tar.gz"
        sha256 "5a4252b6c9ac0229210acf1eb11cb72e92b4f25c8679be2b11ca0443300dc25b"

        def install
          bin.install "baton-linear"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-linear -v"
  end
end
