# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonGithubTest < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.125-test.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-github-test/releases/download/v0.1.125-test.8/baton-github-test-v0.1.125-test.8-darwin-amd64.zip"
      sha256 "3d1fe213d305e8f2d566251bdbc9a683e194c68826b7774f1154db17e9feb8ef"

      def install
        bin.install "baton-github-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-github-test/releases/download/v0.1.125-test.8/baton-github-test-v0.1.125-test.8-darwin-arm64.zip"
      sha256 "975418063bfc5c6936f846a3ab17a650ceaea8f65815738ca6ee14f5f3e1699b"

      def install
        bin.install "baton-github-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-github-test/releases/download/v0.1.125-test.8/baton-github-test-v0.1.125-test.8-linux-amd64.tar.gz"
      sha256 "03f7e4b11c12f8177a8ee5b4fcb1fcb836ef3d4e50230b16b2852515ec02b32d"
      def install
        bin.install "baton-github-test"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-github-test/releases/download/v0.1.125-test.8/baton-github-test-v0.1.125-test.8-linux-arm64.tar.gz"
      sha256 "cdc0c05ebf5f5059f021bddd7229ed685dec4a6b1c31ca1fb4bca6fe84507734"
      def install
        bin.install "baton-github-test"
      end
    end
  end

  test do
    system "#{bin}/baton-github-test -v"
  end
end
