# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSentinelOne < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-sentinel-one/releases/download/v0.0.5/baton-sentinel-one-v0.0.5-darwin-amd64.zip"
      sha256 "ed7d56cf6ba8438a577b9097c8e663c32f7eee469bc4ee7abf85ea7b77ec533d"

      def install
        bin.install "baton-sentinel-one"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-sentinel-one/releases/download/v0.0.5/baton-sentinel-one-v0.0.5-darwin-arm64.zip"
      sha256 "6249d68520b4c241920555ca7a4cb958409d9716f57d206074bb42d418e5be1a"

      def install
        bin.install "baton-sentinel-one"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-sentinel-one/releases/download/v0.0.5/baton-sentinel-one-v0.0.5-linux-amd64.tar.gz"
      sha256 "8ac4492515fc0447d74dc594e68027cc9c614cee70812769f2b1d23fb95dbdc3"
      def install
        bin.install "baton-sentinel-one"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-sentinel-one/releases/download/v0.0.5/baton-sentinel-one-v0.0.5-linux-arm64.tar.gz"
      sha256 "256c65b4fb97cb7cb8cb3957283f0abd6c676bdcb57f671f1d26d4c0b136fc08"
      def install
        bin.install "baton-sentinel-one"
      end
    end
  end

  test do
    system "#{bin}/baton-sentinel-one -v"
  end
end
