# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOktaAwsFederation < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.3.6-alpha"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-okta-aws-federation/releases/download/v0.3.6-alpha/baton-okta-aws-federation-v0.3.6-alpha-darwin-amd64.zip"
      sha256 "38ca3128c8bb78691699148f9a31235d5a564bd452965d7f8f8e38d0eb843e7e"

      def install
        bin.install "baton-okta-aws-federation"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-okta-aws-federation/releases/download/v0.3.6-alpha/baton-okta-aws-federation-v0.3.6-alpha-darwin-arm64.zip"
      sha256 "6df784ee85e0f01a46407f701e164b22e19f86af4c78ae431cc3b03bbb202e81"

      def install
        bin.install "baton-okta-aws-federation"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-okta-aws-federation/releases/download/v0.3.6-alpha/baton-okta-aws-federation-v0.3.6-alpha-linux-amd64.tar.gz"
      sha256 "860bc4b745133bcfd9564e2ecdb9e6ac3ffda61e3438fada8e40ca1939831734"
      def install
        bin.install "baton-okta-aws-federation"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-okta-aws-federation/releases/download/v0.3.6-alpha/baton-okta-aws-federation-v0.3.6-alpha-linux-arm64.tar.gz"
      sha256 "dc2e5503ea0586a238c9629b3ef3c647d127e780369e264ba772349dd4e25948"
      def install
        bin.install "baton-okta-aws-federation"
      end
    end
  end

  test do
    system "#{bin}/baton-okta-aws-federation -v"
  end
end
