# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonNetsuite < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-netsuite/releases/download/v0.0.3/baton-netsuite-v0.0.3-darwin-amd64.zip"
      sha256 "58c92ec5d33cdd4181fb21e13fe0c5912ce3e7ac80ddd9b57a2ac394d4d18d7e"

      def install
        bin.install "baton-netsuite"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-netsuite/releases/download/v0.0.3/baton-netsuite-v0.0.3-darwin-arm64.zip"
      sha256 "22b0de060ca451a669cd6edfab351dbf90dccbdf6c2da4252c7fc4a8d0870d96"

      def install
        bin.install "baton-netsuite"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-netsuite/releases/download/v0.0.3/baton-netsuite-v0.0.3-linux-amd64.tar.gz"
        sha256 "ace1825ea6aa817a160f3e6d83b521e0ce2cc83a86e33ba0a2306f5545e9a380"

        def install
          bin.install "baton-netsuite"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-netsuite/releases/download/v0.0.3/baton-netsuite-v0.0.3-linux-arm64.tar.gz"
        sha256 "9759710010d68ec38a049105a1b922af1febba92b7478d9f62e29d440eea47c1"

        def install
          bin.install "baton-netsuite"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-netsuite -v"
  end
end
