# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonDocusign < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-docusign/releases/download/v0.1.6/baton-docusign-v0.1.6-darwin-amd64.zip"
      sha256 "f076a5955aba5bc8ba9de524d7b0667b5fb6161d8f28e6d8ce0a18785584bf80"

      def install
        bin.install "baton-docusign"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-docusign/releases/download/v0.1.6/baton-docusign-v0.1.6-darwin-arm64.zip"
      sha256 "1260c07424b9ad2663743f7a2e4615b0fcb700c98c5bec8c3e6249032e2f5e65"

      def install
        bin.install "baton-docusign"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-docusign/releases/download/v0.1.6/baton-docusign-v0.1.6-linux-amd64.tar.gz"
      sha256 "684480ba40f3861b1c90ac9f8bef9c1608acdf5c5439b837969940cc1457045e"
      def install
        bin.install "baton-docusign"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-docusign/releases/download/v0.1.6/baton-docusign-v0.1.6-linux-arm64.tar.gz"
      sha256 "0f487ec24654a29dc830981b388d9b4e96949fcfbaea8006a087da6746d32250"
      def install
        bin.install "baton-docusign"
      end
    end
  end

  test do
    system "#{bin}/baton-docusign -v"
  end
end
