# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonAzureDevops < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.6-grant-expansion-test"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-azure-devops/releases/download/v0.1.6-grant-expansion-test/baton-azure-devops-v0.1.6-grant-expansion-test-darwin-amd64.zip"
      sha256 "0e258fd1373f0e2b17bcaf9b81c33db6f701b3e21384eea9ff60baef5a215806"

      def install
        bin.install "baton-azure-devops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-azure-devops/releases/download/v0.1.6-grant-expansion-test/baton-azure-devops-v0.1.6-grant-expansion-test-darwin-arm64.zip"
      sha256 "3fc5ec3875dbb10ac0a82c1bd1cd770ad97c537fa5fc36b0e66210d8198bce8f"

      def install
        bin.install "baton-azure-devops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-azure-devops/releases/download/v0.1.6-grant-expansion-test/baton-azure-devops-v0.1.6-grant-expansion-test-linux-amd64.tar.gz"
        sha256 "3fa19777ba733a4bef377b9d9a8347a30db72efaa9645be3cced83af2bbb3ff0"

        def install
          bin.install "baton-azure-devops"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-azure-devops/releases/download/v0.1.6-grant-expansion-test/baton-azure-devops-v0.1.6-grant-expansion-test-linux-arm64.tar.gz"
        sha256 "61786867e768d723b9a6da5474f021bb6871a9e0c4478b945cfb9e18acc1ef00"

        def install
          bin.install "baton-azure-devops"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-azure-devops -v"
  end
end
