# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonFivetran < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-fivetran/releases/download/v0.1.0/baton-fivetran-v0.1.0-darwin-amd64.zip"
      sha256 "16749a378dff94a98a311db329dde52d373bb731fb23240d6c5abbb0c85223fe"

      def install
        bin.install "baton-fivetran"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-fivetran/releases/download/v0.1.0/baton-fivetran-v0.1.0-darwin-arm64.zip"
      sha256 "6d6c967c4a8cbf4e109f281fb5f46343ed8d4ecaf36995353216e1932be4b8ad"

      def install
        bin.install "baton-fivetran"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-fivetran/releases/download/v0.1.0/baton-fivetran-v0.1.0-linux-amd64.tar.gz"
        sha256 "57238ca3415a4d77eab48bba8caffb394056854400ee3fd5cdac883e568a57c0"

        def install
          bin.install "baton-fivetran"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-fivetran/releases/download/v0.1.0/baton-fivetran-v0.1.0-linux-arm64.tar.gz"
        sha256 "e99242494b5f156a6cb4b98508dbdc66b9468abb1b48e300a1203ff5b3c54cb0"

        def install
          bin.install "baton-fivetran"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-fivetran -v"
  end
end
