# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSql < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-sql/releases/download/v0.0.14/baton-sql-v0.0.14-darwin-amd64.zip"
      sha256 "2361a9c97d768afefcbe6cba0234fdd2e4d604b4f1878398dda3057bb148986e"

      def install
        bin.install "baton-sql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-sql/releases/download/v0.0.14/baton-sql-v0.0.14-darwin-arm64.zip"
      sha256 "1eb3a9f10d3ce0008ae2d30bf30cee25e139e20c2eec465c166d32dcb6ebc0df"

      def install
        bin.install "baton-sql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-sql/releases/download/v0.0.14/baton-sql-v0.0.14-linux-amd64.tar.gz"
        sha256 "22b8554e37b5f3838a38c21d587048348a02b124391566d4df796e03745845f9"

        def install
          bin.install "baton-sql"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-sql/releases/download/v0.0.14/baton-sql-v0.0.14-linux-arm64.tar.gz"
        sha256 "748ee767d4f0bd9ed3f2ef7b20646ff1486ee23f7d3ffb99494ef354b967d0c2"

        def install
          bin.install "baton-sql"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-sql -v"
  end
end
