# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonWorkdayWql < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-workday-wql/releases/download/v0.1.2/baton-workday-wql-v0.1.2-darwin-amd64.zip"
      sha256 "f850add417a92ca39bc1c1ae2e04946aafb5020ced4cc2e9917a4ea5fe363f7a"

      def install
        bin.install "baton-workday-wql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-workday-wql/releases/download/v0.1.2/baton-workday-wql-v0.1.2-darwin-arm64.zip"
      sha256 "41837f8a1a3806efb2b49a291d95e2cd3334e0715925423bce0b0198be3928ca"

      def install
        bin.install "baton-workday-wql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-workday-wql/releases/download/v0.1.2/baton-workday-wql-v0.1.2-linux-amd64.tar.gz"
      sha256 "465bc889f50b9b111c33b77dc1141507093da3a96b12729443a99ce41bbde78a"
      def install
        bin.install "baton-workday-wql"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-workday-wql/releases/download/v0.1.2/baton-workday-wql-v0.1.2-linux-arm64.tar.gz"
      sha256 "61c4d1b7c80cfed94972b3d48c13f71db970519e63c2dbe9157988279b52d27a"
      def install
        bin.install "baton-workday-wql"
      end
    end
  end

  test do
    system "#{bin}/baton-workday-wql -v"
  end
end
