# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonGithubTest < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.48"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-github-test/releases/download/v0.1.48/baton-github-test-v0.1.48-darwin-amd64.zip"
      sha256 "bdaca32ed9575cb5d315cf45f5c1e60e7e42bde26712a5096ae794dfa8af392f"

      def install
        bin.install "baton-github-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-github-test/releases/download/v0.1.48/baton-github-test-v0.1.48-darwin-arm64.zip"
      sha256 "4c0601db189e434f55f5d4a5a055da1142c5511b34d195be3c9e2b63dfbb9a8b"

      def install
        bin.install "baton-github-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-github-test/releases/download/v0.1.48/baton-github-test-v0.1.48-linux-amd64.tar.gz"
        sha256 "2b250042ce7e3d44b542422b7dba124949f73962ffb60e26c47b2674f0af6526"

        def install
          bin.install "baton-github-test"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-github-test/releases/download/v0.1.48/baton-github-test-v0.1.48-linux-arm64.tar.gz"
        sha256 "ffc56ceaa14357afabdbf0571380d49e9a281ca9c794bdc9318adb0955e93776"

        def install
          bin.install "baton-github-test"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-github-test -v"
  end
end
