# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonBlackline < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-blackline/releases/download/v0.2.4/baton-blackline-v0.2.4-darwin-amd64.zip"
      sha256 "b195d4b3d1428b7ed9b1fb44c6f77e69545ceacba30841d6d81e5c1fd3fc4209"

      def install
        bin.install "baton-blackline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-blackline/releases/download/v0.2.4/baton-blackline-v0.2.4-darwin-arm64.zip"
      sha256 "0efaf318ebbe405b847e637739f4a038aa2527be9ec623ff68ba1293a55d8cb3"

      def install
        bin.install "baton-blackline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-blackline/releases/download/v0.2.4/baton-blackline-v0.2.4-linux-amd64.tar.gz"
      sha256 "2cfcc9bc81d4550fe6367de4347e42e457fec3616108196066e753a43b332688"
      def install
        bin.install "baton-blackline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-blackline/releases/download/v0.2.4/baton-blackline-v0.2.4-linux-arm64.tar.gz"
      sha256 "c749c6f7c3d5e460d469fe4437b7accdb050cfd3873624da1c1aa9b5b856f368"
      def install
        bin.install "baton-blackline"
      end
    end
  end

  test do
    system "#{bin}/baton-blackline -v"
  end
end
