# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonHubspot < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-hubspot/releases/download/v0.0.6/baton-hubspot-v0.0.6-darwin-amd64.zip"
      sha256 "da8f7b3e21f874afcf5bdb1a5cad6b5830cbc43c1e75c7785842c488c480e95b"

      def install
        bin.install "baton-hubspot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-hubspot/releases/download/v0.0.6/baton-hubspot-v0.0.6-darwin-arm64.zip"
      sha256 "6378c20c58c17ef347b7773e271cc5a84aa627ed77f18291388c193a2fd3ecf7"

      def install
        bin.install "baton-hubspot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-hubspot/releases/download/v0.0.6/baton-hubspot-v0.0.6-linux-amd64.tar.gz"
        sha256 "99425db5a47045b29bb6d8b534f896c33a7aa7684327a41f010d8e3d48766da5"

        def install
          bin.install "baton-hubspot"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-hubspot/releases/download/v0.0.6/baton-hubspot-v0.0.6-linux-arm64.tar.gz"
        sha256 "8a810d79e133515314b87f7d5712c4d279e9dbd85dfb548a3ad4414a7c9d1735"

        def install
          bin.install "baton-hubspot"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-hubspot -v"
  end
end
