# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonTrayai < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-trayai/releases/download/v0.1.0/baton-trayai-v0.1.0-darwin-amd64.zip"
      sha256 "ba9cf0fa472a7bd979018e5cc261ed6165d75297e64b48302bb14001bf52cc6e"

      def install
        bin.install "baton-trayai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-trayai/releases/download/v0.1.0/baton-trayai-v0.1.0-darwin-arm64.zip"
      sha256 "9a270a1f79285d3ee9c4bce762215d74c32ac96746dc651e6a8adbe09637ca4b"

      def install
        bin.install "baton-trayai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-trayai/releases/download/v0.1.0/baton-trayai-v0.1.0-linux-amd64.tar.gz"
        sha256 "fa29dc1e97e41669fb70ebf2db0e3aeec71e0bff13980f00327bde97838d7d0f"

        def install
          bin.install "baton-trayai"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-trayai/releases/download/v0.1.0/baton-trayai-v0.1.0-linux-arm64.tar.gz"
        sha256 "0a99955a8b68854dfa16a9af25de842ed19fca1e0a38d58ef10ceb405628684a"

        def install
          bin.install "baton-trayai"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-trayai -v"
  end
end
