# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonDiscord < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-discord/releases/download/v0.0.1/baton-discord-v0.0.1-darwin-arm64.zip"
      sha256 "6b68a3558da183d625ce0f0b70e7d13bb45b98806ca23b747db4ae664d1d5616"

      def install
        bin.install "baton-discord"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-discord/releases/download/v0.0.1/baton-discord-v0.0.1-darwin-amd64.zip"
      sha256 "c704f472c51b16fb56642697424728839675383d41e09eed43ddb0e933435fc8"

      def install
        bin.install "baton-discord"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-discord/releases/download/v0.0.1/baton-discord-v0.0.1-linux-arm64.tar.gz"
      sha256 "7fa3d67f2e7d9bd62bb20074a4fc24a1303cedcbe428d026f53008f6a9088767"

      def install
        bin.install "baton-discord"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-discord/releases/download/v0.0.1/baton-discord-v0.0.1-linux-amd64.tar.gz"
      sha256 "41fff749f3ce41962d63c3b7c8b1caf03f419f8c7442f955b0c3ee5f14e8b78a"

      def install
        bin.install "baton-discord"
      end
    end
  end

  test do
    system "#{bin}/baton-discord -v"
  end
end
