# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonProcore < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-procore/releases/download/v0.0.4/baton-procore-v0.0.4-darwin-amd64.zip"
      sha256 "7bcb3b2bd006aee543fbe3abce5d0a88bb4c10664db055408f807c843c0a944e"

      def install
        bin.install "baton-procore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-procore/releases/download/v0.0.4/baton-procore-v0.0.4-darwin-arm64.zip"
      sha256 "51e8026e97e6baf3c34bd6b853042da59973ce8dcdb60b0722ad97d2f2987888"

      def install
        bin.install "baton-procore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-procore/releases/download/v0.0.4/baton-procore-v0.0.4-linux-amd64.tar.gz"
      sha256 "eb3be18febe11fa045bc3da1c345df5899c398da565ae04cc4b5fa4dca52ae6d"
      def install
        bin.install "baton-procore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-procore/releases/download/v0.0.4/baton-procore-v0.0.4-linux-arm64.tar.gz"
      sha256 "71cba5809f2ebe33cb658c2d53878f351c361e554fa45eeb51f03371807bb8ee"
      def install
        bin.install "baton-procore"
      end
    end
  end

  test do
    system "#{bin}/baton-procore -v"
  end
end
