# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonFleetdm < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-fleetdm/releases/download/v0.0.1/baton-fleetdm-v0.0.1-darwin-amd64.zip"
      sha256 "352c1bec1bc6020766b19dc01878ce019496efe8cd7f5fa5075ab110243b823d"

      def install
        bin.install "baton-fleetdm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-fleetdm/releases/download/v0.0.1/baton-fleetdm-v0.0.1-darwin-arm64.zip"
      sha256 "2d8fb95cb6b38d5020c8f3e2a7e0e79a9ca6b4ead08be940d76429eb31e3b9f0"

      def install
        bin.install "baton-fleetdm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-fleetdm/releases/download/v0.0.1/baton-fleetdm-v0.0.1-linux-amd64.tar.gz"
        sha256 "eae1eca1cee728a63c8a8e6cba273362f28fde1c37cbc2066452ed2363059607"

        def install
          bin.install "baton-fleetdm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-fleetdm/releases/download/v0.0.1/baton-fleetdm-v0.0.1-linux-arm64.tar.gz"
        sha256 "762eed0ab040cf804022f8881c6ea4a4650353a0e12fca501dc5a0780e37898c"

        def install
          bin.install "baton-fleetdm"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-fleetdm -v"
  end
end
