# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonNinjio < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-ninjio/releases/download/v0.0.5/baton-ninjio-v0.0.5-darwin-amd64.zip"
      sha256 "e3608c38a60c2bcd5792c8c57285fde59dc5facb7b070293067705807c37db37"

      def install
        bin.install "baton-ninjio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-ninjio/releases/download/v0.0.5/baton-ninjio-v0.0.5-darwin-arm64.zip"
      sha256 "108159a580162e9b797ac5d67145c7cf23af81c2fbd45d41309d275d8df32ce3"

      def install
        bin.install "baton-ninjio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-ninjio/releases/download/v0.0.5/baton-ninjio-v0.0.5-linux-amd64.tar.gz"
      sha256 "4a14ab9debc325b01829c0ab5a7e1c3d6a5c51c913fce79701fa31aa370a3f3a"
      def install
        bin.install "baton-ninjio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-ninjio/releases/download/v0.0.5/baton-ninjio-v0.0.5-linux-arm64.tar.gz"
      sha256 "7c789d119437cff09977c786a7c89ea2a3e330e3792c2504873d50585332397b"
      def install
        bin.install "baton-ninjio"
      end
    end
  end

  test do
    system "#{bin}/baton-ninjio -v"
  end
end
