# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonGoogleads < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-googleads/releases/download/v0.1.0/baton-googleads-v0.1.0-darwin-amd64.zip"
      sha256 "d693206ee3a4325fb78fa2dfccb4706aa9f7dcb539082f40ce5cb2616e5ead16"

      def install
        bin.install "baton-googleads"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-googleads/releases/download/v0.1.0/baton-googleads-v0.1.0-darwin-arm64.zip"
      sha256 "e4d8e6f3fb6e446a63b4e6849004a49084c00f80e2f6fe102694f90cf8a4972e"

      def install
        bin.install "baton-googleads"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-googleads/releases/download/v0.1.0/baton-googleads-v0.1.0-linux-amd64.tar.gz"
      sha256 "7342b7eaf1f3a22cc6ac3718e0c6247145a41eeca506f951f4abd072a41f2be0"
      def install
        bin.install "baton-googleads"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-googleads/releases/download/v0.1.0/baton-googleads-v0.1.0-linux-arm64.tar.gz"
      sha256 "4b3c653119c6497e82759101e7240fe8106961e330dddf245dd6ca14b639f7e9"
      def install
        bin.install "baton-googleads"
      end
    end
  end

  test do
    system "#{bin}/baton-googleads -v"
  end
end
