# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonNetsuite < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.25"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-netsuite/releases/download/v0.0.25/baton-netsuite-v0.0.25-darwin-amd64.zip"
      sha256 "3d87269d0f219e4edd70fe1a8af68bdbb1550423c0a4696b426529fbd2402665"

      def install
        bin.install "baton-netsuite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-netsuite/releases/download/v0.0.25/baton-netsuite-v0.0.25-darwin-arm64.zip"
      sha256 "5a60953de4552df31384edeaf6df68b07ad1322afd0006473348ca5a500c37bf"

      def install
        bin.install "baton-netsuite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-netsuite/releases/download/v0.0.25/baton-netsuite-v0.0.25-linux-amd64.tar.gz"
      sha256 "243b4fe0eae218587ff4b58a0978914403336e8339f696e31033a60a25eb61f9"
      def install
        bin.install "baton-netsuite"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-netsuite/releases/download/v0.0.25/baton-netsuite-v0.0.25-linux-arm64.tar.gz"
      sha256 "c4557aca0f849123e2a6d2da95ec09a4f8360354c312d0de48341737d7423c86"
      def install
        bin.install "baton-netsuite"
      end
    end
  end

  test do
    system "#{bin}/baton-netsuite -v"
  end
end
