# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSapCloudIdentity < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-sap-cloud-identity/releases/download/v0.0.3/baton-sap-cloud-identity-v0.0.3-darwin-amd64.zip"
      sha256 "8463ac8515d62893ab5b887e55ba6c8f8217e97212ec4f320790ac2085141f1d"

      def install
        bin.install "baton-sap-cloud-identity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-sap-cloud-identity/releases/download/v0.0.3/baton-sap-cloud-identity-v0.0.3-darwin-arm64.zip"
      sha256 "69491807a5971ce6791df86b14405482b830d91092c1e2e5bc51b3895bc88060"

      def install
        bin.install "baton-sap-cloud-identity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-sap-cloud-identity/releases/download/v0.0.3/baton-sap-cloud-identity-v0.0.3-linux-amd64.tar.gz"
      sha256 "3af2bc736276a7fdc31f00a233ad985289e14062324cb98e0d4c1381dd1095b8"
      def install
        bin.install "baton-sap-cloud-identity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-sap-cloud-identity/releases/download/v0.0.3/baton-sap-cloud-identity-v0.0.3-linux-arm64.tar.gz"
      sha256 "266c387db3c51414ccd47b3facced8cac4afd80f9a43281092501c3cb4802e78"
      def install
        bin.install "baton-sap-cloud-identity"
      end
    end
  end

  test do
    system "#{bin}/baton-sap-cloud-identity -v"
  end
end
