# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonCouchdb < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-couchdb/releases/download/v0.1.0/baton-couchdb-v0.1.0-darwin-amd64.zip"
      sha256 "343885d623b968af428bddce6ba7f85f9214ae4c354a254ee5714369fb0f41c4"

      def install
        bin.install "baton-couchdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-couchdb/releases/download/v0.1.0/baton-couchdb-v0.1.0-darwin-arm64.zip"
      sha256 "05210aed8dd8014bbe2b98efeb7dd51920ae05551d32822362d88d75616d2280"

      def install
        bin.install "baton-couchdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-couchdb/releases/download/v0.1.0/baton-couchdb-v0.1.0-linux-amd64.tar.gz"
      sha256 "fa702816da4177bfca3a477605cf04f3477fc08e991ca3561013909ce64d17c0"
      def install
        bin.install "baton-couchdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-couchdb/releases/download/v0.1.0/baton-couchdb-v0.1.0-linux-arm64.tar.gz"
      sha256 "489dc2cf43d29ea182e9ddeab9d6936980b32bb424083dd5518a2d698999c60d"
      def install
        bin.install "baton-couchdb"
      end
    end
  end

  test do
    system "#{bin}/baton-couchdb -v"
  end
end
