# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonPostgresql < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-postgresql/releases/download/v0.1.3/baton-postgresql-v0.1.3-darwin-amd64.zip"
      sha256 "3affc1b080fb4e9418636c5b7b272a22dc7da462d2f69d7b9079b26113b00239"

      def install
        bin.install "baton-postgresql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-postgresql/releases/download/v0.1.3/baton-postgresql-v0.1.3-darwin-arm64.zip"
      sha256 "d84ed91c3d4b115dcbd3b6f42d17444e8a9665622ea1ab2ab8c3fe13af7f8c15"

      def install
        bin.install "baton-postgresql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-postgresql/releases/download/v0.1.3/baton-postgresql-v0.1.3-linux-amd64.tar.gz"
      sha256 "7d4166818127f8411f1ed6020c16a4f8a131ccac93134db6766eefe5e4e47c41"

      def install
        bin.install "baton-postgresql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-postgresql/releases/download/v0.1.3/baton-postgresql-v0.1.3-linux-arm64.tar.gz"
      sha256 "0a15f113c23238aa4076284ad073354bcf0dfff9c32b666240895931f963153f"

      def install
        bin.install "baton-postgresql"
      end
    end
  end

  test do
    system "#{bin}/baton-postgresql -v"
  end
end
