# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonRapid7 < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-rapid7/releases/download/v0.0.1/baton-rapid7-v0.0.1-darwin-amd64.zip"
      sha256 "3875e02c0f3e409c22e618e0b87b09c50390158a8e905726c873af21ed5d475d"

      def install
        bin.install "baton-rapid7"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-rapid7/releases/download/v0.0.1/baton-rapid7-v0.0.1-darwin-arm64.zip"
      sha256 "c9b52106673adb0b884ee9867c3a3ad0f968c4acc35541b76984df3eaa8cf9bf"

      def install
        bin.install "baton-rapid7"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-rapid7/releases/download/v0.0.1/baton-rapid7-v0.0.1-linux-amd64.tar.gz"
        sha256 "5c148c83fff45efadb6dd518a3f9640b8407599bf17214f0fb660c3ffb0a0431"

        def install
          bin.install "baton-rapid7"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-rapid7/releases/download/v0.0.1/baton-rapid7-v0.0.1-linux-arm64.tar.gz"
        sha256 "aedb93ba2d4786b3ee8ac0d3d39a1f92a06e5ae1f6b030f379635494be860f5f"

        def install
          bin.install "baton-rapid7"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-rapid7 -v"
  end
end
