# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonBroadcomSac < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-broadcom-sac/releases/download/v0.0.9/baton-broadcom-sac-v0.0.9-darwin-arm64.zip"
      sha256 "6ec20fbfd54f0b3248f1eb41ce5b45e33e7020e66fdc95e86d176abd429fd1a5"

      def install
        bin.install "baton-broadcom-sac"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-broadcom-sac/releases/download/v0.0.9/baton-broadcom-sac-v0.0.9-darwin-amd64.zip"
      sha256 "ef05d9228356b30dbd46234ba5c6711df45cd1b50009b2068d5b17bee38b1e1b"

      def install
        bin.install "baton-broadcom-sac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-broadcom-sac/releases/download/v0.0.9/baton-broadcom-sac-v0.0.9-linux-arm64.tar.gz"
      sha256 "abaeea5033d2d0dc2f45c8fc63c688dbeb68807ab39f7a7af1ce9de27c030157"

      def install
        bin.install "baton-broadcom-sac"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-broadcom-sac/releases/download/v0.0.9/baton-broadcom-sac-v0.0.9-linux-amd64.tar.gz"
      sha256 "e5af8d3f3fc1987893cd03b3525e787857aab5287e509f7c4e3dfbdf5cfd456a"

      def install
        bin.install "baton-broadcom-sac"
      end
    end
  end

  test do
    system "#{bin}/baton-broadcom-sac -v"
  end
end
