# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonLinear < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.20"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-linear/releases/download/v0.0.20/baton-linear-v0.0.20-darwin-amd64.zip"
      sha256 "c5b3e1377e77f160ba4b14ed812f97a95d378ff215fe019f549274f05697805d"

      def install
        bin.install "baton-linear"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-linear/releases/download/v0.0.20/baton-linear-v0.0.20-darwin-arm64.zip"
      sha256 "e87619848e61ec32dd1c9d1401bf54c2fcac65b604fcbe8aae8c8c9b1dd216ce"

      def install
        bin.install "baton-linear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-linear/releases/download/v0.0.20/baton-linear-v0.0.20-linux-amd64.tar.gz"
        sha256 "2a54d7917d031204cd024fd3b11c8a21e360ac3fe22864fddeea54a7611b2447"

        def install
          bin.install "baton-linear"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-linear/releases/download/v0.0.20/baton-linear-v0.0.20-linux-arm64.tar.gz"
        sha256 "7c5011355768ab50fb3d25b2bbe687a6491e341b8f74fc890f733e19fb954bdc"

        def install
          bin.install "baton-linear"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-linear -v"
  end
end
