# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonTenableVm < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-tenable-vm/releases/download/v0.1.1/baton-tenable-vm-v0.1.1-darwin-amd64.zip"
      sha256 "639a6b440141447df60abe96605ac52fbb896c13c07403c28d2f6fac36ae1b9e"

      def install
        bin.install "baton-tenable-vm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-tenable-vm/releases/download/v0.1.1/baton-tenable-vm-v0.1.1-darwin-arm64.zip"
      sha256 "f86694621901d7a2c5bd0ab93d45480d1b56be1468fca53930e499bd3660fe71"

      def install
        bin.install "baton-tenable-vm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-tenable-vm/releases/download/v0.1.1/baton-tenable-vm-v0.1.1-linux-amd64.tar.gz"
        sha256 "7cb37444403548125a395d3769170257254a78e525ffb99425bae7b798ce53f7"

        def install
          bin.install "baton-tenable-vm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-tenable-vm/releases/download/v0.1.1/baton-tenable-vm-v0.1.1-linux-arm64.tar.gz"
        sha256 "e7239ca8f996e66f99f717a2009d2632a3c3b04fad2a968e9d4522cc93949f4e"

        def install
          bin.install "baton-tenable-vm"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-tenable-vm -v"
  end
end
