# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonGrafana < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-grafana/releases/download/v0.0.7/baton-grafana-v0.0.7-darwin-amd64.zip"
      sha256 "5a810410426bd588423d263ddbfe676b61aebaf29658d8410ca518e1272ce76a"

      def install
        bin.install "baton-grafana"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-grafana/releases/download/v0.0.7/baton-grafana-v0.0.7-darwin-arm64.zip"
      sha256 "2a8e156b9af7492822c49907ea2bf8ad66edf748165f12098bcf3c553abd0c92"

      def install
        bin.install "baton-grafana"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-grafana/releases/download/v0.0.7/baton-grafana-v0.0.7-linux-amd64.tar.gz"
      sha256 "363373c8b2eb7dbe26d804286852eb6bc0b8acfc704c62df911278b09299a872"
      def install
        bin.install "baton-grafana"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-grafana/releases/download/v0.0.7/baton-grafana-v0.0.7-linux-arm64.tar.gz"
      sha256 "3f8030ee4f0695b5776bead9704336997144572ff7a85973ee8238ba243d0681"
      def install
        bin.install "baton-grafana"
      end
    end
  end

  test do
    system "#{bin}/baton-grafana -v"
  end
end
