# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonDelinea < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-delinea/releases/download/v0.1.0/baton-delinea-v0.1.0-darwin-amd64.zip"
      sha256 "5848e30fbdb1a067c672191d7432477a976c389ed50dd9d082701bc626d53df2"

      def install
        bin.install "baton-delinea"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-delinea/releases/download/v0.1.0/baton-delinea-v0.1.0-darwin-arm64.zip"
      sha256 "b90225b4e78c97ce874c6960ae380622fe0bc53b7892b0683ca2f894462abfa5"

      def install
        bin.install "baton-delinea"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-delinea/releases/download/v0.1.0/baton-delinea-v0.1.0-linux-amd64.tar.gz"
      sha256 "c6919fca0eb87f013d1ff85d9ab40387e0dd99aa7393ea381b81ff6f46f2dcba"
      def install
        bin.install "baton-delinea"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-delinea/releases/download/v0.1.0/baton-delinea-v0.1.0-linux-arm64.tar.gz"
      sha256 "6d10415fd11b72c1cf344a443a8b37a7193be24d978a6bb0e5bc69509311dcbc"
      def install
        bin.install "baton-delinea"
      end
    end
  end

  test do
    system "#{bin}/baton-delinea -v"
  end
end
