# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonAzureDevops < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.25"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-azure-devops/releases/download/v0.1.25/baton-azure-devops-v0.1.25-darwin-amd64.zip"
      sha256 "a9bb372be028062f497f8490bd07aa522d4d110f5a9c7b6cc878c04df678ea5a"

      def install
        bin.install "baton-azure-devops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-azure-devops/releases/download/v0.1.25/baton-azure-devops-v0.1.25-darwin-arm64.zip"
      sha256 "9747e626784c22555591af4319968dcf2fc4540f0fa1fd554b96a43dbe0efee1"

      def install
        bin.install "baton-azure-devops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-azure-devops/releases/download/v0.1.25/baton-azure-devops-v0.1.25-linux-amd64.tar.gz"
      sha256 "06737923497c9ca0eb4145424eb7584a05e22b3591d3edb7ae135b3047e00069"
      def install
        bin.install "baton-azure-devops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-azure-devops/releases/download/v0.1.25/baton-azure-devops-v0.1.25-linux-arm64.tar.gz"
      sha256 "c137a4491c7f69fc2a87aced3b013d8487e092c16b28a9132925a1743fe7f646"
      def install
        bin.install "baton-azure-devops"
      end
    end
  end

  test do
    system "#{bin}/baton-azure-devops -v"
  end
end
