# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonCursor < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-cursor/releases/download/v0.0.1/baton-cursor-v0.0.1-darwin-amd64.zip"
      sha256 "974a8dbc1ecf5e75ad708a3e0331521810eb76d1af2f1b9b5c99e32ee3caaa49"

      def install
        bin.install "baton-cursor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-cursor/releases/download/v0.0.1/baton-cursor-v0.0.1-darwin-arm64.zip"
      sha256 "ecbfe20937fd432909c821299a5336d2b455894271fae3e88f42f9c9c86e7d42"

      def install
        bin.install "baton-cursor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-cursor/releases/download/v0.0.1/baton-cursor-v0.0.1-linux-amd64.tar.gz"
        sha256 "50c9e107beb5ddc4b8539a826918fece26d73f493c92e7c2ffea1b019fc99bde"

        def install
          bin.install "baton-cursor"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-cursor/releases/download/v0.0.1/baton-cursor-v0.0.1-linux-arm64.tar.gz"
        sha256 "01a6c8fc708c19a5d17620ab02c0f94680bf4b8b36f1a54e81851792982b86c6"

        def install
          bin.install "baton-cursor"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-cursor -v"
  end
end
