# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOracleCloudInfrastructure < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-oracle-cloud-infrastructure/releases/download/v0.0.2/baton-oracle-cloud-infrastructure-v0.0.2-darwin-amd64.zip"
      sha256 "f11dcf7f9ac2b61849388c46a3ec243fe2d9888756b59fb0812835ce045782b4"

      def install
        bin.install "baton-oracle-cloud-infrastructure"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-oracle-cloud-infrastructure/releases/download/v0.0.2/baton-oracle-cloud-infrastructure-v0.0.2-darwin-arm64.zip"
      sha256 "df99c1b3df7bd57838b2625c3848ce024511f6440ca21d0e33dfe0e97b036e17"

      def install
        bin.install "baton-oracle-cloud-infrastructure"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-oracle-cloud-infrastructure/releases/download/v0.0.2/baton-oracle-cloud-infrastructure-v0.0.2-linux-amd64.tar.gz"
        sha256 "261352b8913ebd3e1640039e5b8f643cdcda086ceda5fbf32423f06b0409ffc2"

        def install
          bin.install "baton-oracle-cloud-infrastructure"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-oracle-cloud-infrastructure/releases/download/v0.0.2/baton-oracle-cloud-infrastructure-v0.0.2-linux-arm64.tar.gz"
        sha256 "4541f6869c969f2ced6b5826f382906df001d7a0c4587b0a57b3dd8f6c2a70d5"

        def install
          bin.install "baton-oracle-cloud-infrastructure"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-oracle-cloud-infrastructure -v"
  end
end
