# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonPingfed < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-pingfed/releases/download/v0.1.0/baton-pingfed-v0.1.0-darwin-amd64.zip"
      sha256 "418fd5ea35c97d0622e9e3ab978beebd33d3f5ff8e2eb9c77ff45f8975340de7"

      def install
        bin.install "baton-pingfed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-pingfed/releases/download/v0.1.0/baton-pingfed-v0.1.0-darwin-arm64.zip"
      sha256 "884bc111b0a8c8dedfda7ade071e325ad53f76ab0dfb4741ec5b5673be56602d"

      def install
        bin.install "baton-pingfed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-pingfed/releases/download/v0.1.0/baton-pingfed-v0.1.0-linux-amd64.tar.gz"
      sha256 "57d40fd84e6b2fa92d752224f8d53a45e950b2012ccb169c5b0357a29cb05fab"
      def install
        bin.install "baton-pingfed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-pingfed/releases/download/v0.1.0/baton-pingfed-v0.1.0-linux-arm64.tar.gz"
      sha256 "fdc461575b4f5f7431c6614bde18e070aca964bcffa89fbd1c584c8067158a38"
      def install
        bin.install "baton-pingfed"
      end
    end
  end

  test do
    system "#{bin}/baton-pingfed -v"
  end
end
