# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSumoLogic < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-sumo-logic/releases/download/v0.0.7/baton-sumo-logic-v0.0.7-darwin-amd64.zip"
      sha256 "e7df166b0ac40d649a4d9d8fbcbebfce1ed9bd52725f96b879552904bc68b6f4"

      def install
        bin.install "baton-sumo-logic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-sumo-logic/releases/download/v0.0.7/baton-sumo-logic-v0.0.7-darwin-arm64.zip"
      sha256 "7b94a0698d8e8867e291a12376cd48014f927319e0998c33718182b75140c6bb"

      def install
        bin.install "baton-sumo-logic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-sumo-logic/releases/download/v0.0.7/baton-sumo-logic-v0.0.7-linux-amd64.tar.gz"
        sha256 "9b01afec63ba2c817117f6552ce62734bf80a159f4e6f2dfb59797f7a0d9302d"

        def install
          bin.install "baton-sumo-logic"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-sumo-logic/releases/download/v0.0.7/baton-sumo-logic-v0.0.7-linux-arm64.tar.gz"
        sha256 "b4d55b72721e6fb2c409d80bbb3b72e8ff3debb0e5b01112d12045456be47e6c"

        def install
          bin.install "baton-sumo-logic"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-sumo-logic -v"
  end
end
