# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonPercipio < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-percipio/releases/download/v0.0.3/baton-percipio-v0.0.3-darwin-amd64.zip"
      sha256 "9af04a0ac746ee0a8105c95f5b18ffca078113fad5c69c9ea6d383f879f2d39b"

      def install
        bin.install "baton-percipio"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-percipio/releases/download/v0.0.3/baton-percipio-v0.0.3-darwin-arm64.zip"
      sha256 "cc6b98672cd6b55941d421235549615b6002953020ddbc98969815d0bef7d8a7"

      def install
        bin.install "baton-percipio"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-percipio/releases/download/v0.0.3/baton-percipio-v0.0.3-linux-amd64.tar.gz"
        sha256 "890eaa526846fad7c377d9201f113ff633577499af4d4eca146bc4ccc0f9cc0c"

        def install
          bin.install "baton-percipio"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-percipio/releases/download/v0.0.3/baton-percipio-v0.0.3-linux-arm64.tar.gz"
        sha256 "1e591e53b2240b57549d3bda696bca8bf3d4aab7e857a03565d628de64e22ce8"

        def install
          bin.install "baton-percipio"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-percipio -v"
  end
end
