# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonHttp < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.24.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-http/releases/download/v0.24.11/baton-http-v0.24.11-darwin-amd64.zip"
      sha256 "8c745ac6da48865c2c7fa90391a22fe0dec321a20ae4630946532b042c167bc0"

      def install
        bin.install "baton-http"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-http/releases/download/v0.24.11/baton-http-v0.24.11-darwin-arm64.zip"
      sha256 "ddb993d4f24150a95ae23acbf1632310692db73acf568466acd5648a4c9365bb"

      def install
        bin.install "baton-http"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-http/releases/download/v0.24.11/baton-http-v0.24.11-linux-amd64.tar.gz"
      sha256 "b10908504445f64d05a1074c8eabf7ea8a6e9e68dce02c168f6655dd92da8100"
      def install
        bin.install "baton-http"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-http/releases/download/v0.24.11/baton-http-v0.24.11-linux-arm64.tar.gz"
      sha256 "cdf3359a637d2ed041c9e61e6bb0226db35c18708f32767c2b42a562e067a2aa"
      def install
        bin.install "baton-http"
      end
    end
  end

  test do
    system "#{bin}/baton-http -v"
  end
end
