# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonFloqast < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-floqast/releases/download/v0.0.4/baton-floqast-v0.0.4-darwin-amd64.zip"
      sha256 "88e8be86ab41c9d28ab715360f341b795e2ef8a5c36bef60c63070abc8648818"

      def install
        bin.install "baton-floqast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-floqast/releases/download/v0.0.4/baton-floqast-v0.0.4-darwin-arm64.zip"
      sha256 "112620edf73e92d6a13dec9959fa965b94b7c76f17eca0c9007fd915acebdb57"

      def install
        bin.install "baton-floqast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-floqast/releases/download/v0.0.4/baton-floqast-v0.0.4-linux-amd64.tar.gz"
      sha256 "7aa957c36681218aadcaa84f9592e699e8ef1f5601e5b0d319c389616dce6e4c"
      def install
        bin.install "baton-floqast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-floqast/releases/download/v0.0.4/baton-floqast-v0.0.4-linux-arm64.tar.gz"
      sha256 "b3f6f82bcd42390da82c89a834ca207e06ac04a5310a9d6bdd779eee8f8613bb"
      def install
        bin.install "baton-floqast"
      end
    end
  end

  test do
    system "#{bin}/baton-floqast -v"
  end
end
