# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonJiraDatacenter < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.18"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-jira-datacenter/releases/download/v0.0.18/baton-jira-datacenter-v0.0.18-darwin-amd64.zip"
      sha256 "992d866b57321c0bef9bff925e33095e22318cd6e8a96a265f7b47f3488f2a1f"

      def install
        bin.install "baton-jira-datacenter"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-jira-datacenter/releases/download/v0.0.18/baton-jira-datacenter-v0.0.18-darwin-arm64.zip"
      sha256 "38bb164feeeaea6311c83b25d62a04ec9d006bca0eed549a2dc91b42b8f3cbbd"

      def install
        bin.install "baton-jira-datacenter"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-jira-datacenter/releases/download/v0.0.18/baton-jira-datacenter-v0.0.18-linux-amd64.tar.gz"
        sha256 "26a5c5c1b28a462f2f4fe855aead060ef02f8191d586baabb7524b29b813cec1"

        def install
          bin.install "baton-jira-datacenter"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-jira-datacenter/releases/download/v0.0.18/baton-jira-datacenter-v0.0.18-linux-arm64.tar.gz"
        sha256 "e080e93b3c1e72397434ab411cc5f9dd4984a0d670054a8313cc3b1307ba584f"

        def install
          bin.install "baton-jira-datacenter"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-jira-datacenter -v"
  end
end
