# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonActiveDirectory < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.4.17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-active-directory/releases/download/v0.4.17/baton-active-directory-v0.4.17-darwin-amd64.zip"
      sha256 "91474ac09fe740ea8c73499e59ceeefa98117689ee5472e172a02b4110547d61"

      def install
        bin.install "baton-active-directory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-active-directory/releases/download/v0.4.17/baton-active-directory-v0.4.17-darwin-arm64.zip"
      sha256 "e4a26311cfbf1798d2fbdd9a9a164f4e152d02e741412b925d819bd309692f08"

      def install
        bin.install "baton-active-directory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-active-directory/releases/download/v0.4.17/baton-active-directory-v0.4.17-linux-amd64.tar.gz"
      sha256 "cc3b187779472007783dcbfb93ffb9ecc971708bffac34b7679bbe81e2c2afea"
      def install
        bin.install "baton-active-directory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-active-directory/releases/download/v0.4.17/baton-active-directory-v0.4.17-linux-arm64.tar.gz"
      sha256 "f38447005df7174f2868fe2acdc98b106075a0a937dae14d49185d2da0c488a7"
      def install
        bin.install "baton-active-directory"
      end
    end
  end

  test do
    system "#{bin}/baton-active-directory -v"
  end
end
