# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonTreasureData < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-treasure-data/releases/download/v0.0.1/baton-treasure-data-v0.0.1-darwin-amd64.zip"
      sha256 "d4887720ef02c97250e1b55ce7aed6227d7a31aa5435cd62b8ff082587805216"

      def install
        bin.install "baton-treasure-data"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-treasure-data/releases/download/v0.0.1/baton-treasure-data-v0.0.1-darwin-arm64.zip"
      sha256 "29141c3c544bb180840aaa82fb241e51cf5d28d0efe8c8cb4bdbcee3bbc48a48"

      def install
        bin.install "baton-treasure-data"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-treasure-data/releases/download/v0.0.1/baton-treasure-data-v0.0.1-linux-amd64.tar.gz"
      sha256 "3c62666e623de176298ecf941abbe686ef2f34f57036d4d65c1f9700df7ec219"
      def install
        bin.install "baton-treasure-data"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-treasure-data/releases/download/v0.0.1/baton-treasure-data-v0.0.1-linux-arm64.tar.gz"
      sha256 "c38c0f8ffe6dbac93e26933157e43720a0ca528a69e7cd28f08c9e3c15665431"
      def install
        bin.install "baton-treasure-data"
      end
    end
  end

  test do
    system "#{bin}/baton-treasure-data -v"
  end
end
