# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonGithub < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.25"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-github/releases/download/v0.1.25/baton-github-v0.1.25-darwin-amd64.zip"
      sha256 "7f3815669739718ebc477fc0f926d270d5668978d0a228d4c376ed9a811aef30"

      def install
        bin.install "baton-github"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-github/releases/download/v0.1.25/baton-github-v0.1.25-darwin-arm64.zip"
      sha256 "5118cf419ee4d88c7461b84c32bab1090d5ee7fa2bea6718b82b823750a30981"

      def install
        bin.install "baton-github"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-github/releases/download/v0.1.25/baton-github-v0.1.25-linux-amd64.tar.gz"
        sha256 "9f8ab5eae7d473c970c60f62f315b359378bd4fbbab4ffc2ca34dc47a381ffa9"

        def install
          bin.install "baton-github"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-github/releases/download/v0.1.25/baton-github-v0.1.25-linux-arm64.tar.gz"
        sha256 "2a51d2b37af821ae9ce21beeded75629f3c4a7ce7f1ab8f90df2e862ef6985f7"

        def install
          bin.install "baton-github"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-github -v"
  end
end
