# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSentry < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-sentry/releases/download/v0.0.3/baton-sentry-v0.0.3-darwin-amd64.zip"
      sha256 "040cdbee7c0f8a8f02d9b65a5e2dd845ea7e796fd18c82ce8fc86f8bc57dd178"

      def install
        bin.install "baton-sentry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-sentry/releases/download/v0.0.3/baton-sentry-v0.0.3-darwin-arm64.zip"
      sha256 "73e35a5269a6324c963196baaf6e1dc642ade08cff2d4f81f94955cb27a05d77"

      def install
        bin.install "baton-sentry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-sentry/releases/download/v0.0.3/baton-sentry-v0.0.3-linux-amd64.tar.gz"
        sha256 "8d22ce7df4d1c5a11666d21b3b1ec62f753b89c1fbc1938ef2a3d0c5a7e3b5f2"

        def install
          bin.install "baton-sentry"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-sentry/releases/download/v0.0.3/baton-sentry-v0.0.3-linux-arm64.tar.gz"
        sha256 "37e226f3d64405c4b01f8b5f1bd2b46e0d89446a5efd863c66168753d1226d16"

        def install
          bin.install "baton-sentry"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-sentry -v"
  end
end
