# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSnipeIt < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-snipe-it/releases/download/v0.0.3/baton-snipe-it-v0.0.3-darwin-amd64.zip"
      sha256 "1432ce240048645c7aaa9ce18b3cca18fec0546465c90ec114d144ce859f1b68"

      def install
        bin.install "baton-snipe-it"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-snipe-it/releases/download/v0.0.3/baton-snipe-it-v0.0.3-darwin-arm64.zip"
      sha256 "fd8827cf7cd6a90d47407785d087f9aea90184ac1748ff9bbf13ca079748c3b3"

      def install
        bin.install "baton-snipe-it"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-snipe-it/releases/download/v0.0.3/baton-snipe-it-v0.0.3-linux-arm64.tar.gz"
      sha256 "fbde68673c09f002f9f8535647a0b5681c8f60d1dbb7ba849ecb19009065f4d1"

      def install
        bin.install "baton-snipe-it"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-snipe-it/releases/download/v0.0.3/baton-snipe-it-v0.0.3-linux-amd64.tar.gz"
      sha256 "9f6c9df7293a8e0e581e19320f9dc64e04b9268cd3d38fa95b584d4f02f65282"

      def install
        bin.install "baton-snipe-it"
      end
    end
  end

  test do
    system "#{bin}/baton-snipe-it -v"
  end
end
