# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSharepoint < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.2.2-test.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-sharepoint/releases/download/v0.2.2-test.2/baton-sharepoint-v0.2.2-test.2-darwin-amd64.zip"
      sha256 "b62102f49a7d48ed7f1b3ace9e6fb6bb78b834b3fdd2091b8f2c18a691d13739"

      def install
        bin.install "baton-sharepoint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-sharepoint/releases/download/v0.2.2-test.2/baton-sharepoint-v0.2.2-test.2-darwin-arm64.zip"
      sha256 "1b88876634086d5734eecb188aa1acf1bc7ecb69b0f801b742a1726eb0f5b9f3"

      def install
        bin.install "baton-sharepoint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-sharepoint/releases/download/v0.2.2-test.2/baton-sharepoint-v0.2.2-test.2-linux-amd64.tar.gz"
      sha256 "95344448e373b87746c81c58b1bb9b2a2318dc3a8bc6d97b23e4f0b1cfa4ef06"
      def install
        bin.install "baton-sharepoint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-sharepoint/releases/download/v0.2.2-test.2/baton-sharepoint-v0.2.2-test.2-linux-arm64.tar.gz"
      sha256 "242de8b6fa08d23aec5d887b135c594a8587007c91d7947a3ec51d1d748cd83e"
      def install
        bin.install "baton-sharepoint"
      end
    end
  end

  test do
    system "#{bin}/baton-sharepoint -v"
  end
end
