# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonVgs < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-vgs/releases/download/v0.1.3/baton-vgs-v0.1.3-darwin-amd64.zip"
      sha256 "06a5c5ab660da5673d6d9fd235d1d83c3d8f5b65e3faced3bb45cedcc6956931"

      def install
        bin.install "baton-vgs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-vgs/releases/download/v0.1.3/baton-vgs-v0.1.3-darwin-arm64.zip"
      sha256 "cd23003db38bb9abfd4002fb6f1a562e45f892c0229074e6ea889dda3553df9b"

      def install
        bin.install "baton-vgs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-vgs/releases/download/v0.1.3/baton-vgs-v0.1.3-linux-amd64.tar.gz"
      sha256 "36088b8b6f35cfbaa97acba71d07b40f692afa736e27de5ad4fe5627304de704"
      def install
        bin.install "baton-vgs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-vgs/releases/download/v0.1.3/baton-vgs-v0.1.3-linux-arm64.tar.gz"
      sha256 "5f0c0d5cdc3b8120499fdda42c767e2567cdb22fa1990c1ead6ab4ba9b1c2941"
      def install
        bin.install "baton-vgs"
      end
    end
  end

  test do
    system "#{bin}/baton-vgs -v"
  end
end
