# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOktaAwsFederation < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.3.16-alpha"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-okta-aws-federation/releases/download/v0.3.16-alpha/baton-okta-aws-federation-v0.3.16-alpha-darwin-amd64.zip"
      sha256 "c7adea23f5cf6c2522517f76ad39e8c12dae3cecd675341c5b3f10bdc23fbb5c"

      def install
        bin.install "baton-okta-aws-federation"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-okta-aws-federation/releases/download/v0.3.16-alpha/baton-okta-aws-federation-v0.3.16-alpha-darwin-arm64.zip"
      sha256 "991454fc9356e19acba046c02eba632f3953df2a2fe0266e047d4b52737d2f07"

      def install
        bin.install "baton-okta-aws-federation"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-okta-aws-federation/releases/download/v0.3.16-alpha/baton-okta-aws-federation-v0.3.16-alpha-linux-amd64.tar.gz"
      sha256 "c62c05f17adabf33fedac483f31ed9715b14792e4c937c52fe29d8fa01f1c5ea"
      def install
        bin.install "baton-okta-aws-federation"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-okta-aws-federation/releases/download/v0.3.16-alpha/baton-okta-aws-federation-v0.3.16-alpha-linux-arm64.tar.gz"
      sha256 "b7e236f0e04cf44b8619c34bfc5d5e5eb386815b7787d2a5a58ce922d815f734"
      def install
        bin.install "baton-okta-aws-federation"
      end
    end
  end

  test do
    system "#{bin}/baton-okta-aws-federation -v"
  end
end
