# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonBitbucketDatacenter < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.11"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-bitbucket-datacenter/releases/download/v0.1.11/baton-bitbucket-datacenter-v0.1.11-darwin-amd64.zip"
      sha256 "c6624ecb4958a6b7de31347279ab9952515193394149f1a8decbe7683d0c45ce"

      def install
        bin.install "baton-bitbucket-datacenter"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-bitbucket-datacenter/releases/download/v0.1.11/baton-bitbucket-datacenter-v0.1.11-darwin-arm64.zip"
      sha256 "a8cd109f2d403249610a9a44f7916ae16e2cd03d9984ba99a5af5d1d5f08458d"

      def install
        bin.install "baton-bitbucket-datacenter"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-bitbucket-datacenter/releases/download/v0.1.11/baton-bitbucket-datacenter-v0.1.11-linux-amd64.tar.gz"
        sha256 "5817e53e4a876fa4e8a04d97aa4282eb32fc7175e0846ebd9f694954b73b31ab"

        def install
          bin.install "baton-bitbucket-datacenter"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-bitbucket-datacenter/releases/download/v0.1.11/baton-bitbucket-datacenter-v0.1.11-linux-arm64.tar.gz"
        sha256 "5b550a99b4e179dac2869266d85cf7957a2ab7961eaf98c10cbfc070a21a4d64"

        def install
          bin.install "baton-bitbucket-datacenter"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-bitbucket-datacenter -v"
  end
end
