# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonMicrosoftDynamicsFo < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-microsoft-dynamics-fo/releases/download/v0.0.5/baton-microsoft-dynamics-fo-v0.0.5-darwin-amd64.zip"
      sha256 "033670a1fbe9e83c31951c248533805c1f31de7a33fd310e7da7df2a7c52a4ac"

      def install
        bin.install "baton-microsoft-dynamics-fo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-microsoft-dynamics-fo/releases/download/v0.0.5/baton-microsoft-dynamics-fo-v0.0.5-darwin-arm64.zip"
      sha256 "c3604537ac6a8b70d3f14bac15f9085a4158521afdffd86b76334306aac3cf6d"

      def install
        bin.install "baton-microsoft-dynamics-fo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-microsoft-dynamics-fo/releases/download/v0.0.5/baton-microsoft-dynamics-fo-v0.0.5-linux-amd64.tar.gz"
        sha256 "c74bfb719478be1a48558d6caf8a0022c592cc8f64a861ca12eb73a357d6575c"

        def install
          bin.install "baton-microsoft-dynamics-fo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-microsoft-dynamics-fo/releases/download/v0.0.5/baton-microsoft-dynamics-fo-v0.0.5-linux-arm64.tar.gz"
        sha256 "c774bdeca3d971ca8d51006a7c96ce477c7aa5e67e4f34bb23fea2a5a5f0d405"

        def install
          bin.install "baton-microsoft-dynamics-fo"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-microsoft-dynamics-fo -v"
  end
end
