# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonGithub < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.2.4-test.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-github/releases/download/v0.2.4-test.1/baton-github-v0.2.4-test.1-darwin-amd64.zip"
      sha256 "5b5968728c543df38daba07d3d43e65fef995f2eb2c604d767c8d8e53cf1833c"

      def install
        bin.install "baton-github"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-github/releases/download/v0.2.4-test.1/baton-github-v0.2.4-test.1-darwin-arm64.zip"
      sha256 "f8bdbc4c12ffdb8458a6067a1aceb1c7c55ad8e0daaeb8471fb805415c94c76c"

      def install
        bin.install "baton-github"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-github/releases/download/v0.2.4-test.1/baton-github-v0.2.4-test.1-linux-amd64.tar.gz"
      sha256 "fd969f286b815c3a9f27465db22f0b51fa31bbaf375ad345264146b63c401973"
      def install
        bin.install "baton-github"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-github/releases/download/v0.2.4-test.1/baton-github-v0.2.4-test.1-linux-arm64.tar.gz"
      sha256 "03bf8695644df063dc5a86f4c6596f787e9ed4fb96e65189bce10da50bccbf34"
      def install
        bin.install "baton-github"
      end
    end
  end

  test do
    system "#{bin}/baton-github -v"
  end
end
