# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonHubspot < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-hubspot/releases/download/v0.0.9/baton-hubspot-v0.0.9-darwin-amd64.zip"
      sha256 "79ae4a2aad4ff5082f208852d085f1ee891ed18dc2864c5aa1a7de0ba1267da3"

      def install
        bin.install "baton-hubspot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-hubspot/releases/download/v0.0.9/baton-hubspot-v0.0.9-darwin-arm64.zip"
      sha256 "3068bd85601ba86e61bfb50d300ccbd8a359b634786b011fe822d187040c440f"

      def install
        bin.install "baton-hubspot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-hubspot/releases/download/v0.0.9/baton-hubspot-v0.0.9-linux-amd64.tar.gz"
      sha256 "e6067c81bbb6ea82b45cfb8f59c864a5bca6bd1e42a49cc7abc56d797724a7a0"
      def install
        bin.install "baton-hubspot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-hubspot/releases/download/v0.0.9/baton-hubspot-v0.0.9-linux-arm64.tar.gz"
      sha256 "712456020a05795ff630df1cd37476451dfe07ff7073c08c1f61ff9ee782716a"
      def install
        bin.install "baton-hubspot"
      end
    end
  end

  test do
    system "#{bin}/baton-hubspot -v"
  end
end
