# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class BatonMysql < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-mysql/releases/download/v0.0.3/baton-mysql-v0.0.3-darwin-arm64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7bd2345c544e03b33c7d49550418af8e8237e1a8c3875225e1af16849723b6e1"

      def install
        bin.install "baton-mysql"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-mysql/releases/download/v0.0.3/baton-mysql-v0.0.3-darwin-amd64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4ced54dcc0f45b60e0f47470e88b7823235e0be78d66c6ccfaac3a14a941c925"

      def install
        bin.install "baton-mysql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-mysql/releases/download/v0.0.3/baton-mysql-v0.0.3-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "868ec8a605b9eedfde7cab2d0c9c3f815b64c9491c7db84eb10d46e839931c94"

      def install
        bin.install "baton-mysql"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-mysql/releases/download/v0.0.3/baton-mysql-v0.0.3-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "476c0a220099be7b33e3ad97b69e6cc33486571ce2d614c849198898539e6d74"

      def install
        bin.install "baton-mysql"
      end
    end
  end

  test do
    system "#{bin}/baton-mysql -v"
  end
end
