# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSalesforce < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-salesforce/releases/download/v0.0.9/baton-salesforce-v0.0.9-darwin-amd64.zip"
      sha256 "a02d4505b3769ff2b64d76daeca7516d4abb5efd070da501b7c422093d916605"

      def install
        bin.install "baton-salesforce"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-salesforce/releases/download/v0.0.9/baton-salesforce-v0.0.9-darwin-arm64.zip"
      sha256 "053bc8d390f29663d51fd2235ec41cae2021e254fb002c5e4acc4811febba8c5"

      def install
        bin.install "baton-salesforce"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-salesforce/releases/download/v0.0.9/baton-salesforce-v0.0.9-linux-amd64.tar.gz"
        sha256 "6ed8f10b348e945883747fc310022755fb8a9a9e4fe0b44b800bc999b986d35f"

        def install
          bin.install "baton-salesforce"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-salesforce/releases/download/v0.0.9/baton-salesforce-v0.0.9-linux-arm64.tar.gz"
        sha256 "ba426c49b61c9caebfcf8bc5a5a4c9aef00eae591949f37dc7a3b5f10fb57747"

        def install
          bin.install "baton-salesforce"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-salesforce -v"
  end
end
