# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonMinecraftLuckperms < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-minecraft-luckperms/releases/download/v0.0.2/baton-minecraft-luckperms-v0.0.2-darwin-amd64.zip"
      sha256 "c0a4a9edc25136a21d8f918b7af537abf459b0cf7c922aa0ba03fa615d3bcfde"

      def install
        bin.install "baton-minecraft-luckperms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-minecraft-luckperms/releases/download/v0.0.2/baton-minecraft-luckperms-v0.0.2-darwin-arm64.zip"
      sha256 "fb49760ca9995a89ce9ae6aec8da8039d719e9c3542353d56219e04e01c44fae"

      def install
        bin.install "baton-minecraft-luckperms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-minecraft-luckperms/releases/download/v0.0.2/baton-minecraft-luckperms-v0.0.2-linux-amd64.tar.gz"
        sha256 "05333168686ce56bc1c4f7120bdcf6e2a033730f5cad5c8b642b4a7882bcc720"

        def install
          bin.install "baton-minecraft-luckperms"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-minecraft-luckperms/releases/download/v0.0.2/baton-minecraft-luckperms-v0.0.2-linux-arm64.tar.gz"
        sha256 "30f17db4ebe55c8bd1e7434a7c9d16265678650978c1c08cbbd03dea1ca01184"

        def install
          bin.install "baton-minecraft-luckperms"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-minecraft-luckperms -v"
  end
end
