# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonDropbox < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.5-alpha"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-dropbox/releases/download/v0.0.5-alpha/baton-dropbox-v0.0.5-alpha-darwin-amd64.zip"
      sha256 "3fed42166423fc8347b8383b618ee144411ef913f44d94dfe187f36d3db120f3"

      def install
        bin.install "baton-dropbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-dropbox/releases/download/v0.0.5-alpha/baton-dropbox-v0.0.5-alpha-darwin-arm64.zip"
      sha256 "704fa480c2842664ee974ac83fdeaa73bd107d074aeae630d964dfa881d36dd9"

      def install
        bin.install "baton-dropbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-dropbox/releases/download/v0.0.5-alpha/baton-dropbox-v0.0.5-alpha-linux-amd64.tar.gz"
        sha256 "d425086b94b7c531bed68328c41c9af76d41a285b7fea0d90a47a21c8f71808c"

        def install
          bin.install "baton-dropbox"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-dropbox/releases/download/v0.0.5-alpha/baton-dropbox-v0.0.5-alpha-linux-arm64.tar.gz"
        sha256 "0bfbc79ef0ab18b8d3c2bf1113310b0daee383b760862af4b5b9cf0a194e747e"

        def install
          bin.install "baton-dropbox"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-dropbox -v"
  end
end
