# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSnowflake < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-snowflake/releases/download/v0.0.17/baton-snowflake-v0.0.17-darwin-amd64.zip"
      sha256 "d172a7df38c71ddb534ed87f90bcabec906c6cb92ae618823c0dfa160876b574"

      def install
        bin.install "baton-snowflake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-snowflake/releases/download/v0.0.17/baton-snowflake-v0.0.17-darwin-arm64.zip"
      sha256 "dc8ced592f88c408d2bd98b5cdf6f2b5ac9f3827b67e40b05bb9268b5a36ecdc"

      def install
        bin.install "baton-snowflake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-snowflake/releases/download/v0.0.17/baton-snowflake-v0.0.17-linux-amd64.tar.gz"
        sha256 "46669b767b77620755f16a33d4669d9acbc19e936371b7462a9365bad1749075"

        def install
          bin.install "baton-snowflake"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-snowflake/releases/download/v0.0.17/baton-snowflake-v0.0.17-linux-arm64.tar.gz"
        sha256 "d1ff7d64c39cec7cce556a6364f9e5732a81f8f03a3b49053a4e9c2eb7172f0f"

        def install
          bin.install "baton-snowflake"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-snowflake -v"
  end
end
