# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOracleCloudInfrastructure < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-oracle-cloud-infrastructure/releases/download/v0.0.11/baton-oracle-cloud-infrastructure-v0.0.11-darwin-amd64.zip"
      sha256 "d4308426106ab232284ffad02d4a90e0bdb183518045c31e3dd7bb594aebd38b"

      def install
        bin.install "baton-oracle-cloud-infrastructure"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-oracle-cloud-infrastructure/releases/download/v0.0.11/baton-oracle-cloud-infrastructure-v0.0.11-darwin-arm64.zip"
      sha256 "37d008a3b8cafcc8f24cc182ca0f2fbd781da08a0119f5d2dcb75ff29f225ed6"

      def install
        bin.install "baton-oracle-cloud-infrastructure"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-oracle-cloud-infrastructure/releases/download/v0.0.11/baton-oracle-cloud-infrastructure-v0.0.11-linux-amd64.tar.gz"
        sha256 "2cab6c06394a26c404884b372e877b9d469067ed357a72189fcf95dbba3cb052"

        def install
          bin.install "baton-oracle-cloud-infrastructure"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-oracle-cloud-infrastructure/releases/download/v0.0.11/baton-oracle-cloud-infrastructure-v0.0.11-linux-arm64.tar.gz"
        sha256 "8db24a2f1f2f124ea6b2a891d20989e27cbef59fcc2de993d9c733c65b410e6a"

        def install
          bin.install "baton-oracle-cloud-infrastructure"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-oracle-cloud-infrastructure -v"
  end
end
