# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonActiveDirectory < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.4.1-alpha.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-active-directory/releases/download/v0.4.1-alpha.3/baton-active-directory-v0.4.1-alpha.3-darwin-amd64.zip"
      sha256 "432d9c4fc03d4874554a8dbff2460156fe7444f2ca6792059b4dccf12292d432"

      def install
        bin.install "baton-active-directory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-active-directory/releases/download/v0.4.1-alpha.3/baton-active-directory-v0.4.1-alpha.3-darwin-arm64.zip"
      sha256 "43747597263bc4ec2d12c4c67f8cb81ea96bbf696cd3577e95fabf6ef145de5a"

      def install
        bin.install "baton-active-directory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-active-directory/releases/download/v0.4.1-alpha.3/baton-active-directory-v0.4.1-alpha.3-linux-amd64.tar.gz"
        sha256 "ad283188ca6eb62adf8c9bb70591d9cd8e841cb6ba863476c922d36c781950a4"

        def install
          bin.install "baton-active-directory"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-active-directory/releases/download/v0.4.1-alpha.3/baton-active-directory-v0.4.1-alpha.3-linux-arm64.tar.gz"
        sha256 "aef432f385a92a54c179282ac9976f710d69127d996a4e432dfb48991d76dc40"

        def install
          bin.install "baton-active-directory"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-active-directory -v"
  end
end
