# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonCursor < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-cursor/releases/download/v0.2.0/baton-cursor-v0.2.0-darwin-amd64.zip"
      sha256 "685fe630c8f6312804c6c4abb9638c93265b4a004402a6e86360ad46e9913913"

      def install
        bin.install "baton-cursor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-cursor/releases/download/v0.2.0/baton-cursor-v0.2.0-darwin-arm64.zip"
      sha256 "c421c13f22352452849848a62e5bb5c0830a1216333ace4e146016956c1673e6"

      def install
        bin.install "baton-cursor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-cursor/releases/download/v0.2.0/baton-cursor-v0.2.0-linux-amd64.tar.gz"
        sha256 "50d454b69a01a95cc573603ccf5215d98ab975a5b948b2a01f799be8cb7755fd"

        def install
          bin.install "baton-cursor"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-cursor/releases/download/v0.2.0/baton-cursor-v0.2.0-linux-arm64.tar.gz"
        sha256 "f86f2dc19e3ddd1f801623fd22edb85583a1de00e97a250910cacb49c831cb1d"

        def install
          bin.install "baton-cursor"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-cursor -v"
  end
end
