# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonFloqast < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-floqast/releases/download/v0.0.5/baton-floqast-v0.0.5-darwin-amd64.zip"
      sha256 "012d4b6ecc76657749a62a67dbf92b5c11050b9baa9fd3a3a89a2fd7e29a1e1d"

      def install
        bin.install "baton-floqast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-floqast/releases/download/v0.0.5/baton-floqast-v0.0.5-darwin-arm64.zip"
      sha256 "3a1e812b94f27cce2921f89ed91b4cf6734c9ac0727274b2f75d340afb2e9921"

      def install
        bin.install "baton-floqast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-floqast/releases/download/v0.0.5/baton-floqast-v0.0.5-linux-amd64.tar.gz"
      sha256 "6b81638d55782fd1318a232bc977d98d222e145de18256e53754435d9a0d7ae3"
      def install
        bin.install "baton-floqast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-floqast/releases/download/v0.0.5/baton-floqast-v0.0.5-linux-arm64.tar.gz"
      sha256 "374965b6c976869c000629599817531120bbd2f3dbfa3a26706f4a40f71d0339"
      def install
        bin.install "baton-floqast"
      end
    end
  end

  test do
    system "#{bin}/baton-floqast -v"
  end
end
