# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonEks < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-eks/releases/download/v0.0.1/baton-eks-v0.0.1-darwin-amd64.zip"
      sha256 "4b82411840d4c53696e2ca5bcf023d6c5bfda3d040d7fde11c85b0f37c9ad363"

      def install
        bin.install "baton-eks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-eks/releases/download/v0.0.1/baton-eks-v0.0.1-darwin-arm64.zip"
      sha256 "ac126a76b12a96fdb4c94e76a54f07e2a9f32cc863a1a3284837858865847db6"

      def install
        bin.install "baton-eks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-eks/releases/download/v0.0.1/baton-eks-v0.0.1-linux-amd64.tar.gz"
        sha256 "5b7670ac0068fee79b2a672d217d897e128a99609b38797ca75959837a1a3629"

        def install
          bin.install "baton-eks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-eks/releases/download/v0.0.1/baton-eks-v0.0.1-linux-arm64.tar.gz"
        sha256 "2ec3e6f827aebc8bc9c0eb05332d91cf205e87db81fe90873aa58c780e6af0cb"

        def install
          bin.install "baton-eks"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-eks -v"
  end
end
