# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonPercipio < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.9"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-percipio/releases/download/v0.0.9/baton-percipio-v0.0.9-darwin-amd64.zip"
      sha256 "f87d9025bd2f5eb226c6e12a1f64e37449006b0ff7a78f58d84b9e07a399b738"

      def install
        bin.install "baton-percipio"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-percipio/releases/download/v0.0.9/baton-percipio-v0.0.9-darwin-arm64.zip"
      sha256 "062a11cfd13440e9bb1d9d59bd8c80b24383603e78f100163ca629a28faf052b"

      def install
        bin.install "baton-percipio"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-percipio/releases/download/v0.0.9/baton-percipio-v0.0.9-linux-amd64.tar.gz"
        sha256 "f03bc23cc74fb26218631136d17d84526262055c4df7ca18583e1fc26fa8d4d9"

        def install
          bin.install "baton-percipio"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-percipio/releases/download/v0.0.9/baton-percipio-v0.0.9-linux-arm64.tar.gz"
        sha256 "529103a96829215d15822c53235992c79f7f69e1cc5a61d4607644c2c9fb88f7"

        def install
          bin.install "baton-percipio"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-percipio -v"
  end
end
