# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonCrowdstrike < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-crowdstrike/releases/download/v0.0.2/baton-crowdstrike-v0.0.2-darwin-arm64.zip"
      sha256 "926207efedc6f06839970cb6e6877334d993485b6d7a8f77ce1cf7ae7ad7e875"

      def install
        bin.install "baton-crowdstrike"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-crowdstrike/releases/download/v0.0.2/baton-crowdstrike-v0.0.2-darwin-amd64.zip"
      sha256 "a6621d7dc2fd8680031cd2a24e22584ee49fdf56e4f5e62f47b8dd2ef8fb2ec9"

      def install
        bin.install "baton-crowdstrike"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-crowdstrike/releases/download/v0.0.2/baton-crowdstrike-v0.0.2-linux-arm64.tar.gz"
      sha256 "05e2a425b88946f4af3503ca77d02fe74ecf64ef65d7dedae24d53df8fd7947e"

      def install
        bin.install "baton-crowdstrike"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-crowdstrike/releases/download/v0.0.2/baton-crowdstrike-v0.0.2-linux-amd64.tar.gz"
      sha256 "28e2baa0f3ab6b62c230fa0c5b438845a1160c82c0a00d87be53b11809a223d2"

      def install
        bin.install "baton-crowdstrike"
      end
    end
  end

  test do
    system "#{bin}/baton-crowdstrike -v"
  end
end
