# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonHttp < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-http/releases/download/v0.5.0/baton-http-v0.5.0-darwin-amd64.zip"
      sha256 "d609b066d645c48381b12d9ccd809c1af16b80f38f1f8ae37d3cb8819ad982a4"

      def install
        bin.install "baton-http"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-http/releases/download/v0.5.0/baton-http-v0.5.0-darwin-arm64.zip"
      sha256 "42a16609674d8292c2e19e0f506ed94c0124b27aa97b3861c90e7b3b35b3d6ce"

      def install
        bin.install "baton-http"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-http/releases/download/v0.5.0/baton-http-v0.5.0-linux-amd64.tar.gz"
        sha256 "10d477ac46b90cec3343bdfbf7094a6a0a972150b387c631101953451624b149"

        def install
          bin.install "baton-http"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-http/releases/download/v0.5.0/baton-http-v0.5.0-linux-arm64.tar.gz"
        sha256 "68b1cee7b27b71fb3fff291dcff989454208853adb80e2097b4a3ea408efb9fd"

        def install
          bin.install "baton-http"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-http -v"
  end
end
