# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonUkg < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-ukg/releases/download/v0.0.1/baton-ukg-v0.0.1-darwin-amd64.zip"
      sha256 "b700b0d441b1b354e1e917a9f03cfbeefbf5fa1f34d0777115fc0e76914e40ca"

      def install
        bin.install "baton-ukg"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-ukg/releases/download/v0.0.1/baton-ukg-v0.0.1-darwin-arm64.zip"
      sha256 "f670be1e3e3020fd1a35e5a31df386d765dfba6815c2a748a4b91224cadb0c1c"

      def install
        bin.install "baton-ukg"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-ukg/releases/download/v0.0.1/baton-ukg-v0.0.1-linux-amd64.tar.gz"
        sha256 "90c9b9e92721156756b47d7ce945a96a730ebe1ce593fef4bb76d35d76c5e470"

        def install
          bin.install "baton-ukg"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-ukg/releases/download/v0.0.1/baton-ukg-v0.0.1-linux-arm64.tar.gz"
        sha256 "ed10aee200ed04732abebbd518a80ce3d8dff73790b55cc2dcf43e503accd710"

        def install
          bin.install "baton-ukg"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-ukg -v"
  end
end
