# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonHubspot < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-hubspot/releases/download/v0.0.10/baton-hubspot-v0.0.10-darwin-amd64.zip"
      sha256 "4f7712a533f376708dec4d5776dcbaf604ef3bf30b0042cc8e37c8d9d0ab82fc"

      def install
        bin.install "baton-hubspot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-hubspot/releases/download/v0.0.10/baton-hubspot-v0.0.10-darwin-arm64.zip"
      sha256 "2ea0db263aa17f27fdba1ba4e33191a9ee74dd86234facb78253091911f11b3d"

      def install
        bin.install "baton-hubspot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-hubspot/releases/download/v0.0.10/baton-hubspot-v0.0.10-linux-amd64.tar.gz"
      sha256 "e9e2ff6e07111e3ca23f70a94150807b3df727829943f1eddc4c230b7c529d7c"
      def install
        bin.install "baton-hubspot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-hubspot/releases/download/v0.0.10/baton-hubspot-v0.0.10-linux-arm64.tar.gz"
      sha256 "cc2eef898fde30ce67da1961164ba83686e163f4d90f107c18ae23978e32264e"
      def install
        bin.install "baton-hubspot"
      end
    end
  end

  test do
    system "#{bin}/baton-hubspot -v"
  end
end
