# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonFreshservice < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-freshservice/releases/download/v0.0.3/baton-freshservice-v0.0.3-darwin-amd64.zip"
      sha256 "1caee31156d4b9b5eb49961e838a8325ca8bb883fa37ba0309da96054bed9933"

      def install
        bin.install "baton-freshservice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-freshservice/releases/download/v0.0.3/baton-freshservice-v0.0.3-darwin-arm64.zip"
      sha256 "d2264d9bac7bdc48d9c31ec26470ad330aeb71796a491a698d5f5686fdeaff6c"

      def install
        bin.install "baton-freshservice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-freshservice/releases/download/v0.0.3/baton-freshservice-v0.0.3-linux-amd64.tar.gz"
        sha256 "251113819977420ff111d8078d34554aea5b989e2ef667fe5cfd7a0c8be44e6a"

        def install
          bin.install "baton-freshservice"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-freshservice/releases/download/v0.0.3/baton-freshservice-v0.0.3-linux-arm64.tar.gz"
        sha256 "42af934a3d8d6cc83049f4896010991b6f422e90765ca9a0376b293fc638889b"

        def install
          bin.install "baton-freshservice"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-freshservice -v"
  end
end
