# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonGoogleWorkspace < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.12"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-google-workspace/releases/download/v0.0.12/baton-google-workspace-v0.0.12-darwin-amd64.zip"
      sha256 "ac3299f6092540219d5db919f5a6c8901dd9b980e34dbaac88cd51cc6eb6893a"

      def install
        bin.install "baton-google-workspace"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-google-workspace/releases/download/v0.0.12/baton-google-workspace-v0.0.12-darwin-arm64.zip"
      sha256 "1c4eeaf17b0f7ba58aad1054a86116436bf10efcf23e4c3accc7abe261206f84"

      def install
        bin.install "baton-google-workspace"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-google-workspace/releases/download/v0.0.12/baton-google-workspace-v0.0.12-linux-amd64.tar.gz"
        sha256 "cd0d345bed1e065d2d1e804eddd40bf94d8bda73e51ba71fe776804b661ec313"

        def install
          bin.install "baton-google-workspace"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-google-workspace/releases/download/v0.0.12/baton-google-workspace-v0.0.12-linux-arm64.tar.gz"
        sha256 "f52231e566731825b6d891c419d12966f0ff4b22dfbf73ce9ce92f9c4ad667a0"

        def install
          bin.install "baton-google-workspace"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-google-workspace -v"
  end
end
