# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonExpensify < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-expensify/releases/download/v0.0.9/baton-expensify-v0.0.9-darwin-amd64.zip"
      sha256 "a1db27d62e329712d2982c1bbf8eb0a14941f774b35933f3fedd5e2923867422"

      def install
        bin.install "baton-expensify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-expensify/releases/download/v0.0.9/baton-expensify-v0.0.9-darwin-arm64.zip"
      sha256 "5fdc04b0f6751912980aa4d2f18ee86fd1130949d3add1eec655036a61fbc09c"

      def install
        bin.install "baton-expensify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-expensify/releases/download/v0.0.9/baton-expensify-v0.0.9-linux-amd64.tar.gz"
        sha256 "fc80f042086b68b8a73006493c5411394e8a108757e590b1a4e4280f683b1ddd"

        def install
          bin.install "baton-expensify"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-expensify/releases/download/v0.0.9/baton-expensify-v0.0.9-linux-arm64.tar.gz"
        sha256 "cdbb28dc66c65bc2706025a1b3a8b414dc14f4b1eb23de42cba2d50eddfca241"

        def install
          bin.install "baton-expensify"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-expensify -v"
  end
end
