# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonMysql < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-mysql/releases/download/v0.1.3/baton-mysql-v0.1.3-darwin-amd64.zip"
      sha256 "6242d1652d0a808297b572b16e14ebcfbbf1c31c31c10c4801089f7f9a71d471"

      def install
        bin.install "baton-mysql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-mysql/releases/download/v0.1.3/baton-mysql-v0.1.3-darwin-arm64.zip"
      sha256 "9914ec803c1a3be5cf300a8cdccc2146516f10913060aac4bb62c2d6db39af55"

      def install
        bin.install "baton-mysql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-mysql/releases/download/v0.1.3/baton-mysql-v0.1.3-linux-amd64.tar.gz"
      sha256 "164c1c2ff1fcd14940db3a485fa93844ba638d08cd275d40409c4f6ccef2da16"
      def install
        bin.install "baton-mysql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-mysql/releases/download/v0.1.3/baton-mysql-v0.1.3-linux-arm64.tar.gz"
      sha256 "6a1b1f8b66b836fd53e1130143fc9ef3f9a670ab64b2c51dd2920fa1d177b430"
      def install
        bin.install "baton-mysql"
      end
    end
  end

  test do
    system "#{bin}/baton-mysql -v"
  end
end
