# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOracleIdcs < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-oracle-idcs/releases/download/v0.0.12/baton-oracle-idcs-v0.0.12-darwin-amd64.zip"
      sha256 "4b29f43c41c5060ef069321b436bfc532f4e91fbc5d331a7d74921f926404e3b"

      def install
        bin.install "baton-oracle-idcs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-oracle-idcs/releases/download/v0.0.12/baton-oracle-idcs-v0.0.12-darwin-arm64.zip"
      sha256 "a8ddcd27314eb8fc4fdbbb97fff94b0f62328a9ee7bd12c6e8b44ae37a14d03f"

      def install
        bin.install "baton-oracle-idcs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-oracle-idcs/releases/download/v0.0.12/baton-oracle-idcs-v0.0.12-linux-amd64.tar.gz"
      sha256 "b8d5b5e369db9cefd28cabaa90d4dd230dfdb986ab68d32a25f431d93143c58a"
      def install
        bin.install "baton-oracle-idcs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-oracle-idcs/releases/download/v0.0.12/baton-oracle-idcs-v0.0.12-linux-arm64.tar.gz"
      sha256 "c10aff9539bf5f1d9b9a434cf734f48d6bce9c658b209cfcb40043f34ace2b10"
      def install
        bin.install "baton-oracle-idcs"
      end
    end
  end

  test do
    system "#{bin}/baton-oracle-idcs -v"
  end
end
