# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSonatypeNexus < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-sonatype-nexus/releases/download/v0.0.0/baton-sonatype-nexus-v0.0.0-darwin-amd64.zip"
      sha256 "fdb7f2e6c215a93a19f9592bfd9a4b4717735e8c27f2dec79294efbb6ea2900f"

      def install
        bin.install "baton-sonatype-nexus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-sonatype-nexus/releases/download/v0.0.0/baton-sonatype-nexus-v0.0.0-darwin-arm64.zip"
      sha256 "7e389920609f7be290dc608116e488f4189e1bf8f21d8381e3090a03928a0fb7"

      def install
        bin.install "baton-sonatype-nexus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-sonatype-nexus/releases/download/v0.0.0/baton-sonatype-nexus-v0.0.0-linux-amd64.tar.gz"
        sha256 "61de9c85097d895be1e7f88413189550445ec1aa66e71b2959fe567a762a7597"

        def install
          bin.install "baton-sonatype-nexus"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-sonatype-nexus/releases/download/v0.0.0/baton-sonatype-nexus-v0.0.0-linux-arm64.tar.gz"
        sha256 "8faf2d4f3d977dbd678cef91e5643a4a13d9a3d96184daf548bbb69fbafc40ee"

        def install
          bin.install "baton-sonatype-nexus"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-sonatype-nexus -v"
  end
end
