# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonJira < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-jira/releases/download/v0.0.7/baton-jira-v0.0.7-darwin-amd64.zip"
      sha256 "71a2dcf3434437610e18a0fe53960a255f5b3dfd835fba30b667d8b4596eb002"

      def install
        bin.install "baton-jira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-jira/releases/download/v0.0.7/baton-jira-v0.0.7-darwin-arm64.zip"
      sha256 "10cfaccbc6ea35f6f98c5c1833a7ef8f9d8c4f436e595ca9494b537bee004239"

      def install
        bin.install "baton-jira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-jira/releases/download/v0.0.7/baton-jira-v0.0.7-linux-amd64.tar.gz"
      sha256 "7127799d51cb8918d1bedc3ec25fbd731db62940d4dc41559fb7ca32d2772f90"

      def install
        bin.install "baton-jira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-jira/releases/download/v0.0.7/baton-jira-v0.0.7-linux-arm64.tar.gz"
      sha256 "c6a9e07742a85ae498510c548ca6c82c80d62f975127e4cce768051ac7ecff3b"

      def install
        bin.install "baton-jira"
      end
    end
  end

  test do
    system "#{bin}/baton-jira -v"
  end
end
