# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSigmacomputing < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-sigmacomputing/releases/download/v0.2.0/baton-sigmacomputing-v0.2.0-darwin-amd64.zip"
      sha256 "6f32c7a61152e78d748ac60b405ac67aadd29515e76e75ba88cf611dadc6f5bf"

      def install
        bin.install "baton-sigmacomputing"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-sigmacomputing/releases/download/v0.2.0/baton-sigmacomputing-v0.2.0-darwin-arm64.zip"
      sha256 "e7ef4aede8259c012052873c08cb8de434128004519aca96047721712dec74d3"

      def install
        bin.install "baton-sigmacomputing"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-sigmacomputing/releases/download/v0.2.0/baton-sigmacomputing-v0.2.0-linux-amd64.tar.gz"
      sha256 "9048b62d626d22c07212ce5f6cfc51da730c43e33182275958b809432b9b081f"
      def install
        bin.install "baton-sigmacomputing"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-sigmacomputing/releases/download/v0.2.0/baton-sigmacomputing-v0.2.0-linux-arm64.tar.gz"
      sha256 "2dda5e3a4ac3f4eab6e695e887e35e8620f2b22f4368bfa27784742cba0ebf0f"
      def install
        bin.install "baton-sigmacomputing"
      end
    end
  end

  test do
    system "#{bin}/baton-sigmacomputing -v"
  end
end
