# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonDayforce < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.2.2-alpha.17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-dayforce/releases/download/v0.2.2-alpha.17/baton-dayforce-v0.2.2-alpha.17-darwin-amd64.zip"
      sha256 "ade6133f0d904b02e7616f68548448c51e103ba462ff83f3e0ac514b6eddcdb6"

      def install
        bin.install "baton-dayforce"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-dayforce/releases/download/v0.2.2-alpha.17/baton-dayforce-v0.2.2-alpha.17-darwin-arm64.zip"
      sha256 "26fcd94f76378232ef024aeda3566c38e91968406465c32da9c090fee3627369"

      def install
        bin.install "baton-dayforce"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-dayforce/releases/download/v0.2.2-alpha.17/baton-dayforce-v0.2.2-alpha.17-linux-amd64.tar.gz"
        sha256 "50df4f835a497b26d3004dc1eaed3ba898866249ab1bd5fbd18113bfb1e90fed"

        def install
          bin.install "baton-dayforce"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-dayforce/releases/download/v0.2.2-alpha.17/baton-dayforce-v0.2.2-alpha.17-linux-arm64.tar.gz"
        sha256 "23a2b7da18f1c354f876860930833f5e3b48a4cb1ed486cbec84f28be9195cc8"

        def install
          bin.install "baton-dayforce"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-dayforce -v"
  end
end
