# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonPaloAltoCortex < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-palo-alto-cortex/releases/download/v0.0.3/baton-palo-alto-cortex-v0.0.3-darwin-amd64.zip"
      sha256 "7d83853cdd17feea6a312b0a36a78bb35944070ef7ddb8dd1dc09d7577f79aa6"

      def install
        bin.install "baton-palo-alto-cortex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-palo-alto-cortex/releases/download/v0.0.3/baton-palo-alto-cortex-v0.0.3-darwin-arm64.zip"
      sha256 "9fba5aa3a5233cdd347b140b17e4d00597b71106607b50a559ea208c27f4f088"

      def install
        bin.install "baton-palo-alto-cortex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-palo-alto-cortex/releases/download/v0.0.3/baton-palo-alto-cortex-v0.0.3-linux-amd64.tar.gz"
      sha256 "c2bb09a77bc08a1ce6d5560aa7f7a4c27709729b02510b19db9c8376571fb146"
      def install
        bin.install "baton-palo-alto-cortex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-palo-alto-cortex/releases/download/v0.0.3/baton-palo-alto-cortex-v0.0.3-linux-arm64.tar.gz"
      sha256 "d63be1e5c9100db31fc1e5403deb88110050ccd18d2ce3b0f8bcac3d11933521"
      def install
        bin.install "baton-palo-alto-cortex"
      end
    end
  end

  test do
    system "#{bin}/baton-palo-alto-cortex -v"
  end
end
