# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonPrivx < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-privx/releases/download/v0.0.3/baton-privx-v0.0.3-darwin-amd64.zip"
      sha256 "0dff84afe932fea8452517716b5e25a37b3cc0f673351f73dcee41ff78967a0a"

      def install
        bin.install "baton-privx"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-privx/releases/download/v0.0.3/baton-privx-v0.0.3-darwin-arm64.zip"
      sha256 "4a2ad7c90a4937e9bf218cd1c725b9e96f597150c2af2845d7bf6bfa0e945107"

      def install
        bin.install "baton-privx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-privx/releases/download/v0.0.3/baton-privx-v0.0.3-linux-amd64.tar.gz"
        sha256 "461b8b74990954872939e0b5b831455eb71acbd293e7ed824cd17ecae04e7972"

        def install
          bin.install "baton-privx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-privx/releases/download/v0.0.3/baton-privx-v0.0.3-linux-arm64.tar.gz"
        sha256 "3448109f8a8bc3a5db25f29afe5258784f1a5dbe4c2bf5612c0331cee524ac57"

        def install
          bin.install "baton-privx"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-privx -v"
  end
end
