# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonPingfederate < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-pingfed/releases/download/v0.0.1/baton-pingfederate-v0.0.1-darwin-amd64.zip"
      sha256 "faad2f4bd34b48b6c7b3da9891e741ba76927da7e508e744997569489e69804c"

      def install
        bin.install "baton-pingfederate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-pingfed/releases/download/v0.0.1/baton-pingfederate-v0.0.1-darwin-arm64.zip"
      sha256 "3bf55b7cdd4785c2f5d27d928bdfb1d0011123f158e38b514960cee593899cef"

      def install
        bin.install "baton-pingfederate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-pingfed/releases/download/v0.0.1/baton-pingfederate-v0.0.1-linux-amd64.tar.gz"
        sha256 "3294a3770b85fe82b32a21341d1bcf195ef16ac9bae81c6f82e53c72dbda78ce"

        def install
          bin.install "baton-pingfederate"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-pingfed/releases/download/v0.0.1/baton-pingfederate-v0.0.1-linux-arm64.tar.gz"
        sha256 "29e37ca52598a18997d23620ee2d71b27a8e7c3c48f24f6f08c3cd291869e904"

        def install
          bin.install "baton-pingfederate"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-pingfederate -v"
  end
end
