# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonMonday < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-monday/releases/download/v0.1.0/baton-monday-v0.1.0-darwin-amd64.zip"
      sha256 "1ab2a7184303b1e7e887edbb1c7a7290e1a630e80cde4fdfdc1e5273f4ddb3f2"

      def install
        bin.install "baton-monday"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-monday/releases/download/v0.1.0/baton-monday-v0.1.0-darwin-arm64.zip"
      sha256 "ef4429aad7e09fdc52dea157f074c3e3245e0ecc65a2fe00719261346947568e"

      def install
        bin.install "baton-monday"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-monday/releases/download/v0.1.0/baton-monday-v0.1.0-linux-amd64.tar.gz"
        sha256 "ebd517157f43497771aeafe47fdc4114dda03bbc44e7b81129ca5d8d43dc45f4"

        def install
          bin.install "baton-monday"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-monday/releases/download/v0.1.0/baton-monday-v0.1.0-linux-arm64.tar.gz"
        sha256 "97dc5a8c7b039f57dd9261c2f6b9cd51eb2e5cf71fd2bf53054bdb61f9e5387f"

        def install
          bin.install "baton-monday"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-monday -v"
  end
end
