# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSlack < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-slack/releases/download/v0.0.1/baton-slack-v0.0.1-darwin-amd64.zip"
      sha256 "c9234022be116138655d1d0a42632eeedf957b600cb68a05bd461ffacd1b0305"

      def install
        bin.install "baton-slack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-slack/releases/download/v0.0.1/baton-slack-v0.0.1-darwin-arm64.zip"
      sha256 "4f8ef941fe91932c5e6f4c4435706d43c9baa5a96ccf7ebf2153ac527830e192"

      def install
        bin.install "baton-slack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-slack/releases/download/v0.0.1/baton-slack-v0.0.1-linux-arm64.tar.gz"
      sha256 "baa5823675708dc1cab532462b8290bd8d58e5cdb115c3e57ca35b84f74c454a"

      def install
        bin.install "baton-slack"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-slack/releases/download/v0.0.1/baton-slack-v0.0.1-linux-amd64.tar.gz"
      sha256 "8c04364b84c7b42c9a94d6dddd7f10dbbaf3653ac362efc377ca24642cd40a0f"

      def install
        bin.install "baton-slack"
      end
    end
  end

  test do
    system "#{bin}/baton-slack -v"
  end
end
