# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class BatonDemo < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-demo/releases/download/v0.0.1/baton-demo-v0.0.1-darwin-amd64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b653d64f45f98dabd405d50c9460c5f871f4557fb3d7e1bd526e4fdcb217152b"

      def install
        bin.install "baton-demo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-demo/releases/download/v0.0.1/baton-demo-v0.0.1-darwin-arm64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "646e49d38a15147bc5200544bc796c5368ca1d8df5aac51f306429451a857494"

      def install
        bin.install "baton-demo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-demo/releases/download/v0.0.1/baton-demo-v0.0.1-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3c3ac8810a17d6b57b9a79bf0d042f0da53164d18fb40dd32f28cd99d2867ec5"

      def install
        bin.install "baton-demo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-demo/releases/download/v0.0.1/baton-demo-v0.0.1-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e21a37024bb8eb9245402286483c3afb77a0c1ecb28099e9462401ac5f5ef5f5"

      def install
        bin.install "baton-demo"
      end
    end
  end

  test do
    system "#{bin}/baton-demo -v"
  end
end
