# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonNetsuite < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.21"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-netsuite/releases/download/v0.0.21/baton-netsuite-v0.0.21-darwin-amd64.zip"
      sha256 "49ebe0f740db2efaca6b38c379841c1e96d82378b6ec7b122f11522ae8856e7c"

      def install
        bin.install "baton-netsuite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-netsuite/releases/download/v0.0.21/baton-netsuite-v0.0.21-darwin-arm64.zip"
      sha256 "475ce69f0a93bf006eb73c03660d353e223e83cf2255770934b74e17778108f6"

      def install
        bin.install "baton-netsuite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-netsuite/releases/download/v0.0.21/baton-netsuite-v0.0.21-linux-amd64.tar.gz"
      sha256 "40efe8d3e42512d5498d851ba4b8f3d3adab7a1fef3bb77d17c8be143e467a09"
      def install
        bin.install "baton-netsuite"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-netsuite/releases/download/v0.0.21/baton-netsuite-v0.0.21-linux-arm64.tar.gz"
      sha256 "1783f14f7e65d7d57e0dffc5d6213c76d953191b3d43cbea12e82f97cb1198df"
      def install
        bin.install "baton-netsuite"
      end
    end
  end

  test do
    system "#{bin}/baton-netsuite -v"
  end
end
