# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOpensearch < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-opensearch/releases/download/v0.0.1/baton-opensearch-v0.0.1-darwin-amd64.zip"
      sha256 "74f38faefaeaa18de756b29e30f8a796e8fb028ec0459af1bf514ac497c20719"

      def install
        bin.install "baton-opensearch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-opensearch/releases/download/v0.0.1/baton-opensearch-v0.0.1-darwin-arm64.zip"
      sha256 "6c7db31ea45056d9549a9a1d22cecf7d6d6a67ee16dfd5ba5efe7a100292abcf"

      def install
        bin.install "baton-opensearch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-opensearch/releases/download/v0.0.1/baton-opensearch-v0.0.1-linux-amd64.tar.gz"
        sha256 "da8f9aa1c8fa288a29a1e2ee0109d58fbfd47c6963e15bc24b9f68b7a1305365"

        def install
          bin.install "baton-opensearch"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-opensearch/releases/download/v0.0.1/baton-opensearch-v0.0.1-linux-arm64.tar.gz"
        sha256 "27e4d99fcecb96d7faa0b1fda473067ab6c321b0f6eff5896d78d63c4096c388"

        def install
          bin.install "baton-opensearch"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-opensearch -v"
  end
end
