# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonServicedeskPlus < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-servicedesk-plus/releases/download/v0.0.2/baton-servicedesk-plus-v0.0.2-darwin-amd64.zip"
      sha256 "d6ee3646057bcc7f15b8fbfdd7bc707028cf6607ecf7f79a72b256653993e7a5"

      def install
        bin.install "baton-servicedesk-plus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-servicedesk-plus/releases/download/v0.0.2/baton-servicedesk-plus-v0.0.2-darwin-arm64.zip"
      sha256 "0e5f7815efa876d522983377ced1c53e7400d0dbf9416ba645fe5e60a8d3b8b9"

      def install
        bin.install "baton-servicedesk-plus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-servicedesk-plus/releases/download/v0.0.2/baton-servicedesk-plus-v0.0.2-linux-amd64.tar.gz"
      sha256 "1a8f4514a3b526283095494c86b893e04fac12eb0e54717d1163a1cd036e3199"
      def install
        bin.install "baton-servicedesk-plus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-servicedesk-plus/releases/download/v0.0.2/baton-servicedesk-plus-v0.0.2-linux-arm64.tar.gz"
      sha256 "5497644a0342611d473451c2171c349f05abe8e759a22985fd9e6524b0bcd201"
      def install
        bin.install "baton-servicedesk-plus"
      end
    end
  end

  test do
    system "#{bin}/baton-servicedesk-plus -v"
  end
end
