# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baton1password < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-1password/releases/download/v0.0.4/baton-1password-v0.0.4-darwin-amd64.zip"
      sha256 "09047603c28729c4381a21b8307553f2032239fe2b493b2f2869dbe92d26dc8d"

      def install
        bin.install "baton-1password"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-1password/releases/download/v0.0.4/baton-1password-v0.0.4-darwin-arm64.zip"
      sha256 "377b7c16ef9b085cf9e178d6a710f6e8c071d0239720251ee93a3980aa19dbe3"

      def install
        bin.install "baton-1password"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-1password/releases/download/v0.0.4/baton-1password-v0.0.4-linux-arm64.tar.gz"
      sha256 "3de41e1856c76c6c39b176de1ac2dca29426e62e1e84c9fab39601af3393d83a"

      def install
        bin.install "baton-1password"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-1password/releases/download/v0.0.4/baton-1password-v0.0.4-linux-amd64.tar.gz"
      sha256 "d53ea657db033402a5d930b65b880eca58ec165e2853f0d783fabe41ea2f346f"

      def install
        bin.install "baton-1password"
      end
    end
  end

  test do
    system "#{bin}/baton-1password -v"
  end
end
