# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonDatadog < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-datadog/releases/download/v0.0.5/baton-datadog-v0.0.5-darwin-amd64.zip"
      sha256 "2b18d9a816aba151c8db36215f2606f8863f9cf70f1174e1f8eb56ada2baa403"

      def install
        bin.install "baton-datadog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-datadog/releases/download/v0.0.5/baton-datadog-v0.0.5-darwin-arm64.zip"
      sha256 "ff420d41cd1815b996b8d23e1b199883bf09095ae9adfc8fef4b03edc79a50a4"

      def install
        bin.install "baton-datadog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-datadog/releases/download/v0.0.5/baton-datadog-v0.0.5-linux-amd64.tar.gz"
      sha256 "772b03719924a23e32f1c9fe11569c0092c033d4d219e4b57611da99bc6d06cb"
      def install
        bin.install "baton-datadog"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-datadog/releases/download/v0.0.5/baton-datadog-v0.0.5-linux-arm64.tar.gz"
      sha256 "db0172eb5e43396824058f716fa440310705ae10c6a80b1c5b3e4e4c6f1bb653"
      def install
        bin.install "baton-datadog"
      end
    end
  end

  test do
    system "#{bin}/baton-datadog -v"
  end
end
