# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonVercel < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-vercel/releases/download/v0.0.2/baton-vercel-v0.0.2-darwin-amd64.zip"
      sha256 "d983664e3c2d2c98dc6f67b0da30226db8f3a0469b0249fec5ea4a6a12aebf83"

      def install
        bin.install "baton-vercel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-vercel/releases/download/v0.0.2/baton-vercel-v0.0.2-darwin-arm64.zip"
      sha256 "4914116b7cf627aa3a5bee646c8c544bbf56b3e7ca0d66c2cb7932db5bab778a"

      def install
        bin.install "baton-vercel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-vercel/releases/download/v0.0.2/baton-vercel-v0.0.2-linux-amd64.tar.gz"
      sha256 "b5d3a9a00e77c86d8200000a7c6fdf9bc89b72ca5f3fd1a0b034be15cf455ae8"
      def install
        bin.install "baton-vercel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-vercel/releases/download/v0.0.2/baton-vercel-v0.0.2-linux-arm64.tar.gz"
      sha256 "12f8763df4316a816791c46dbfc858f4a443c6fd60f1ae199f27a11076108d80"
      def install
        bin.install "baton-vercel"
      end
    end
  end

  test do
    system "#{bin}/baton-vercel -v"
  end
end
