# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonFileshare < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1-rc.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-fileshare/releases/download/v0.0.1-rc.5/baton-fileshare-v0.0.1-rc.5-darwin-amd64.zip"
      sha256 "3b8b8d96d000f20a5f48de38dc58a8872c8174af426b491ab060563b0c778b9f"

      def install
        bin.install "baton-fileshare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-fileshare/releases/download/v0.0.1-rc.5/baton-fileshare-v0.0.1-rc.5-darwin-arm64.zip"
      sha256 "36b4e9b12d69c3104c8e3a2a4f856bc112a852b86906499501dc9852a28af03a"

      def install
        bin.install "baton-fileshare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-fileshare/releases/download/v0.0.1-rc.5/baton-fileshare-v0.0.1-rc.5-linux-amd64.tar.gz"
      sha256 "75c6395a6548cdd876cc81050e76875d79b0ed638483b48ad8e55ea70227598c"
      def install
        bin.install "baton-fileshare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-fileshare/releases/download/v0.0.1-rc.5/baton-fileshare-v0.0.1-rc.5-linux-arm64.tar.gz"
      sha256 "c24945dbeac79d66e62cb8397b2d5453663e09e997d066907c205aa3899f47d2"
      def install
        bin.install "baton-fileshare"
      end
    end
  end

  test do
    system "#{bin}/baton-fileshare -v"
  end
end
