# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonAuth0 < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-auth0/releases/download/v0.0.9/baton-auth0-v0.0.9-darwin-amd64.zip"
      sha256 "9ff0d590be38590c40d5dd734e8775b5f7820ebd8445ddc43000cc5e5de21e88"

      def install
        bin.install "baton-auth0"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-auth0/releases/download/v0.0.9/baton-auth0-v0.0.9-darwin-arm64.zip"
      sha256 "e83bba1c9a9c344295639fd57aac51f61a6b3bc0410dd7bfec9fad21cba0d707"

      def install
        bin.install "baton-auth0"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-auth0/releases/download/v0.0.9/baton-auth0-v0.0.9-linux-amd64.tar.gz"
      sha256 "499c5e1704f0493498bf27003c4319211e28322caca32ed0a636323254d3c187"
      def install
        bin.install "baton-auth0"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-auth0/releases/download/v0.0.9/baton-auth0-v0.0.9-linux-arm64.tar.gz"
      sha256 "0bdaed25559e38e89bd9e8171dd097444e84d5ad873ecef03318c560612d5afc"
      def install
        bin.install "baton-auth0"
      end
    end
  end

  test do
    system "#{bin}/baton-auth0 -v"
  end
end
