# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOutreach < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-outreach/releases/download/v0.1.2/baton-outreach-v0.1.2-darwin-amd64.zip"
      sha256 "773e1cf3ebe25e3c46bad06fb4fcffa8d82ef39fc146888523a537b20f87d07c"

      def install
        bin.install "baton-outreach"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-outreach/releases/download/v0.1.2/baton-outreach-v0.1.2-darwin-arm64.zip"
      sha256 "b7cf6e415c539ff4036c65823622de6e23e2db24ae7e3c24764207763c6c7a7d"

      def install
        bin.install "baton-outreach"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-outreach/releases/download/v0.1.2/baton-outreach-v0.1.2-linux-amd64.tar.gz"
        sha256 "d027480c77fbbe2086e883e792d67604e56adf9c7b310f8645e2196cc3ac2263"

        def install
          bin.install "baton-outreach"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-outreach/releases/download/v0.1.2/baton-outreach-v0.1.2-linux-arm64.tar.gz"
        sha256 "f284497a3d550868c8a970bc6c143c5832058bd949271e004e0d32b91d706538"

        def install
          bin.install "baton-outreach"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-outreach -v"
  end
end
