# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonAzureDevops < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-azure-devops/releases/download/v0.1.8/baton-azure-devops-v0.1.8-darwin-amd64.zip"
      sha256 "c9439c1ebb06dcf282152da646198e0d9fa9803dbdcdab2e4a7894d443fca491"

      def install
        bin.install "baton-azure-devops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-azure-devops/releases/download/v0.1.8/baton-azure-devops-v0.1.8-darwin-arm64.zip"
      sha256 "67a93a360b737000cff614c7e9c78ee5c6972f326fee4d62bb424b3b6b4b7763"

      def install
        bin.install "baton-azure-devops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-azure-devops/releases/download/v0.1.8/baton-azure-devops-v0.1.8-linux-amd64.tar.gz"
      sha256 "f890909c06a9acdce1cd21c7c4f2665fd1c2dcea88e68d20bef089c9f58e554f"
      def install
        bin.install "baton-azure-devops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-azure-devops/releases/download/v0.1.8/baton-azure-devops-v0.1.8-linux-arm64.tar.gz"
      sha256 "5663d45a2e82c286fee5ec5f3006ed83b36c94a031443ae58a92c1f1e56e8b6d"
      def install
        bin.install "baton-azure-devops"
      end
    end
  end

  test do
    system "#{bin}/baton-azure-devops -v"
  end
end
