# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonVgs < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-vgs/releases/download/v0.1.0/baton-vgs-v0.1.0-darwin-amd64.zip"
      sha256 "672de09397dc2f248c14db2781a24be9ad36b4bbf6f551b772442048db094d8d"

      def install
        bin.install "baton-vgs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-vgs/releases/download/v0.1.0/baton-vgs-v0.1.0-darwin-arm64.zip"
      sha256 "85a7e18e35045fadfccdb84255bfad491329a5e921e443ba7fc8c812af5ca364"

      def install
        bin.install "baton-vgs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-vgs/releases/download/v0.1.0/baton-vgs-v0.1.0-linux-amd64.tar.gz"
      sha256 "b77aa3981a1a4c6e86aae882cd4811ce9266770b541142d3baae4ba513381395"
      def install
        bin.install "baton-vgs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-vgs/releases/download/v0.1.0/baton-vgs-v0.1.0-linux-arm64.tar.gz"
      sha256 "1aa08fc541b2c080d0a7da3a2595e369d351b8d1b1e592e08a7d600e9f198ad4"
      def install
        bin.install "baton-vgs"
      end
    end
  end

  test do
    system "#{bin}/baton-vgs -v"
  end
end
