# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonBitrise < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-bitrise/releases/download/v0.1.0/baton-bitrise-v0.1.0-darwin-amd64.zip"
      sha256 "dc948279d055eeddc1598724f51cd5f5a9eaa0bd54038209f3e9a6098a847b0a"

      def install
        bin.install "baton-bitrise"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-bitrise/releases/download/v0.1.0/baton-bitrise-v0.1.0-darwin-arm64.zip"
      sha256 "78dfab16e573af400531a0c03d89bf975d54cc5d8d500ef1b63483f7dfc5848f"

      def install
        bin.install "baton-bitrise"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-bitrise/releases/download/v0.1.0/baton-bitrise-v0.1.0-linux-amd64.tar.gz"
        sha256 "7372d148b2a56458335e019d36e2b05dfc234b746300d9a36f28d99c027a96dc"

        def install
          bin.install "baton-bitrise"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-bitrise/releases/download/v0.1.0/baton-bitrise-v0.1.0-linux-arm64.tar.gz"
        sha256 "4ec8f7260e72bd9120fa5d762fbb53b36d5a0e7140f37e37a87c549265df810d"

        def install
          bin.install "baton-bitrise"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-bitrise -v"
  end
end
