# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonTailscale < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-tailscale/releases/download/v0.0.5/baton-tailscale-v0.0.5-darwin-amd64.zip"
      sha256 "ecc5b20bad523a1dfc31a0195787694ffabb2511c48c842fa4cf85f98f5dc54a"

      def install
        bin.install "baton-tailscale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-tailscale/releases/download/v0.0.5/baton-tailscale-v0.0.5-darwin-arm64.zip"
      sha256 "f719526e3b342ef1906c8e92f3a5a8913a64957faaa71e687c25a0b6a2f32d7c"

      def install
        bin.install "baton-tailscale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-tailscale/releases/download/v0.0.5/baton-tailscale-v0.0.5-linux-amd64.tar.gz"
        sha256 "55898e7f41219868f406ad3533be77b72b9ebff03af0e2d58d956a966a051fac"

        def install
          bin.install "baton-tailscale"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-tailscale/releases/download/v0.0.5/baton-tailscale-v0.0.5-linux-arm64.tar.gz"
        sha256 "26286b80bfe6316c3baa8217e6e8abff56924ffe9abdec3ea790ae76fef6ec2a"

        def install
          bin.install "baton-tailscale"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-tailscale -v"
  end
end
