# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOktaAwsFederation < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.3.29"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-okta-aws-federation/releases/download/v0.3.29/baton-okta-aws-federation-v0.3.29-darwin-amd64.zip"
      sha256 "cdec97b0f40afe644fad249cee3ee2868fb64d6ae1b98e739d09f87be311bda6"

      def install
        bin.install "baton-okta-aws-federation"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-okta-aws-federation/releases/download/v0.3.29/baton-okta-aws-federation-v0.3.29-darwin-arm64.zip"
      sha256 "c4f29ba931e693397cca73bf0eb7dd040ce4ddc141f3826852a41eabbb585233"

      def install
        bin.install "baton-okta-aws-federation"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-okta-aws-federation/releases/download/v0.3.29/baton-okta-aws-federation-v0.3.29-linux-amd64.tar.gz"
      sha256 "2d3179399298ac31938443cd3ed883dd073c7af96df8eada39a1bb84d15f1669"
      def install
        bin.install "baton-okta-aws-federation"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-okta-aws-federation/releases/download/v0.3.29/baton-okta-aws-federation-v0.3.29-linux-arm64.tar.gz"
      sha256 "9c3fffeacf3fb56048a1c2f269e45b7e723c7ea946efe8496b6a24e99873b99a"
      def install
        bin.install "baton-okta-aws-federation"
      end
    end
  end

  test do
    system "#{bin}/baton-okta-aws-federation -v"
  end
end
