# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonAzureInfrastructure < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-azure-infrastructure/releases/download/v0.0.10/baton-azure-infrastructure-v0.0.10-darwin-amd64.zip"
      sha256 "09614fabdb0bb34e777d577ba6936374541656429377389b272b9ea21ad3a265"

      def install
        bin.install "baton-azure-infrastructure"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-azure-infrastructure/releases/download/v0.0.10/baton-azure-infrastructure-v0.0.10-darwin-arm64.zip"
      sha256 "8c64bf97a5a4b0fac4b7fa787d3e6d7b529a260ed3b6433e824134d8e93eca75"

      def install
        bin.install "baton-azure-infrastructure"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-azure-infrastructure/releases/download/v0.0.10/baton-azure-infrastructure-v0.0.10-linux-amd64.tar.gz"
        sha256 "3563fece4d9768bf73fda379eb3ae1e2bae4b39db5ff8bc52bbc1b744b905ae5"

        def install
          bin.install "baton-azure-infrastructure"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-azure-infrastructure/releases/download/v0.0.10/baton-azure-infrastructure-v0.0.10-linux-arm64.tar.gz"
        sha256 "ce79c69e844462b9db80ef4e6186b80dee83b4a852c7aa9425bd2951cbc00fbe"

        def install
          bin.install "baton-azure-infrastructure"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-azure-infrastructure -v"
  end
end
