# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonLinear < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.16-test-retry-debugging-3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-linear/releases/download/v0.0.16-test-retry-debugging-3/baton-linear-v0.0.16-test-retry-debugging-3-darwin-amd64.zip"
      sha256 "91a90fcba874fa06c4d5b3f63227f595c0387de292390e3503a17d5aa16600a7"

      def install
        bin.install "baton-linear"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-linear/releases/download/v0.0.16-test-retry-debugging-3/baton-linear-v0.0.16-test-retry-debugging-3-darwin-arm64.zip"
      sha256 "14d5aabaec2f5e6d900900d81efe6a3ee9bb1f82ec57bfabee39edd1db1b0a92"

      def install
        bin.install "baton-linear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-linear/releases/download/v0.0.16-test-retry-debugging-3/baton-linear-v0.0.16-test-retry-debugging-3-linux-amd64.tar.gz"
        sha256 "d1c8067ae1ed2ba5b11c42c8a58000a904a74c294c233ca573b5b4e29da6c3d1"

        def install
          bin.install "baton-linear"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-linear/releases/download/v0.0.16-test-retry-debugging-3/baton-linear-v0.0.16-test-retry-debugging-3-linux-arm64.tar.gz"
        sha256 "acb8bd4142730cbbac34a7a4fd49a1d15ae2d7d1e1c35ff3a166b12a14413973"

        def install
          bin.install "baton-linear"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-linear -v"
  end
end
