# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonFileshare < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-fileshare/releases/download/v0.1.1/baton-fileshare-v0.1.1-darwin-amd64.zip"
      sha256 "949f559721a44a64dfc76e358f086f4155d1c9c87ca3ff3c368fe7d691834921"

      def install
        bin.install "baton-fileshare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-fileshare/releases/download/v0.1.1/baton-fileshare-v0.1.1-darwin-arm64.zip"
      sha256 "bd26a4161dfd783947208a283491eb85193892818f87687635d07e9abc18399c"

      def install
        bin.install "baton-fileshare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-fileshare/releases/download/v0.1.1/baton-fileshare-v0.1.1-linux-amd64.tar.gz"
      sha256 "377ef3fd344488611d428f86b73528523eeddccb2e10e1806a873c351f002e08"
      def install
        bin.install "baton-fileshare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-fileshare/releases/download/v0.1.1/baton-fileshare-v0.1.1-linux-arm64.tar.gz"
      sha256 "e84ee876c4678a21656dbbacaf12d2af7b795e7f2ba091b2b23e8ddb56258684"
      def install
        bin.install "baton-fileshare"
      end
    end
  end

  test do
    system "#{bin}/baton-fileshare -v"
  end
end
