# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonGitlab < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.28-skip-child-resource-annos-4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-gitlab/releases/download/v0.0.28-skip-child-resource-annos-4/baton-gitlab-v0.0.28-skip-child-resource-annos-4-darwin-amd64.zip"
      sha256 "92e05226516c9f20fd05b4ecabd4d15c4a6deedc85e526dbad447425732e00e9"

      def install
        bin.install "baton-gitlab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-gitlab/releases/download/v0.0.28-skip-child-resource-annos-4/baton-gitlab-v0.0.28-skip-child-resource-annos-4-darwin-arm64.zip"
      sha256 "bc2024d5ae48b73734ef42e3eb82674ddf0af1cc30317652f1866c7c897bab2f"

      def install
        bin.install "baton-gitlab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-gitlab/releases/download/v0.0.28-skip-child-resource-annos-4/baton-gitlab-v0.0.28-skip-child-resource-annos-4-linux-amd64.tar.gz"
        sha256 "7d2798a6baa6492cf87e6bd7b293051c140b4fed82480426c068208200cee88b"

        def install
          bin.install "baton-gitlab"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-gitlab/releases/download/v0.0.28-skip-child-resource-annos-4/baton-gitlab-v0.0.28-skip-child-resource-annos-4-linux-arm64.tar.gz"
        sha256 "972bcd17c54fe4ef7d6fb19519f04325ce2e41a3a7a2f2b095e0e0bed662f90f"

        def install
          bin.install "baton-gitlab"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-gitlab -v"
  end
end
