# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonTeamcity < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-teamcity/releases/download/v0.1.0/baton-teamcity-v0.1.0-darwin-amd64.zip"
      sha256 "423a0dd6ef258cc16f947d1746ea8c5143dcf736445054be158391c34006abc8"

      def install
        bin.install "baton-teamcity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-teamcity/releases/download/v0.1.0/baton-teamcity-v0.1.0-darwin-arm64.zip"
      sha256 "f557bda9751024b757df9b85b972b2b49134844c128ef0efb05d6427d1d19941"

      def install
        bin.install "baton-teamcity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-teamcity/releases/download/v0.1.0/baton-teamcity-v0.1.0-linux-amd64.tar.gz"
        sha256 "09ce762efd304a0518282d2e4f4597f3f88da12fb862578c94bcd528d0005545"

        def install
          bin.install "baton-teamcity"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-teamcity/releases/download/v0.1.0/baton-teamcity-v0.1.0-linux-arm64.tar.gz"
        sha256 "e44fe9d22ef760a201cd4c0bfb8877180297a581c5174ee6a350bcb555c788ec"

        def install
          bin.install "baton-teamcity"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-teamcity -v"
  end
end
