# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonDuo < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-duo/releases/download/v0.0.1/baton-duo-v0.0.1-darwin-amd64.zip"
      sha256 "9eaf23fd52e26a4153f6f838959a0785338e1f828a2d2229ba2c4ddd550f68e6"

      def install
        bin.install "baton-duo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-duo/releases/download/v0.0.1/baton-duo-v0.0.1-darwin-arm64.zip"
      sha256 "80bc6a0bb42b77a347af2c32cf91907a4da6f114e11adbde933fc6bb841db663"

      def install
        bin.install "baton-duo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-duo/releases/download/v0.0.1/baton-duo-v0.0.1-linux-arm64.tar.gz"
      sha256 "2ec092526659625b32be717264a80a1b3d7932f19ea52a47a9ce676946241b9a"

      def install
        bin.install "baton-duo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-duo/releases/download/v0.0.1/baton-duo-v0.0.1-linux-amd64.tar.gz"
      sha256 "a4c9e02b6bedc437e323d2e5b4d4be87d0e1fa080b78e9ea267e34153a7bd441"

      def install
        bin.install "baton-duo"
      end
    end
  end

  test do
    system "#{bin}/baton-duo -v"
  end
end
