# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonTrello < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-trello/releases/download/v0.1.0/baton-trello-v0.1.0-darwin-amd64.zip"
      sha256 "2babbb935a4ca01dd704577d9f555deb6b4c52f5d6f07983ec761d9e20b357d0"

      def install
        bin.install "baton-trello"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-trello/releases/download/v0.1.0/baton-trello-v0.1.0-darwin-arm64.zip"
      sha256 "f86a48735554fc99dbb36bfa2debe1cc7c26d724d93649cba7183f7d233e24c3"

      def install
        bin.install "baton-trello"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-trello/releases/download/v0.1.0/baton-trello-v0.1.0-linux-amd64.tar.gz"
      sha256 "3a032846dff73b79262d81ae1b9c2622305d086c4df8397309b959c58af49f7a"
      def install
        bin.install "baton-trello"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-trello/releases/download/v0.1.0/baton-trello-v0.1.0-linux-arm64.tar.gz"
      sha256 "7c9a8ca0df940ccc34f0a12d2090c6ce5fcf4362a1506f3aab669128aa277d94"
      def install
        bin.install "baton-trello"
      end
    end
  end

  test do
    system "#{bin}/baton-trello -v"
  end
end
