# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonCeligo < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-celigo/releases/download/v0.0.1/baton-celigo-v0.0.1-darwin-arm64.zip"
      sha256 "3dc04240f574b61b24df4c386ee0bc06b5feccd78f0dc37348b9294bcc27837a"

      def install
        bin.install "baton-celigo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-celigo/releases/download/v0.0.1/baton-celigo-v0.0.1-darwin-amd64.zip"
      sha256 "a1be16cdf0a437ae849237ff9ed932060535864b10fa404c2ec839bcc6340197"

      def install
        bin.install "baton-celigo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-celigo/releases/download/v0.0.1/baton-celigo-v0.0.1-linux-arm64.tar.gz"
      sha256 "c3122461af0fc1536428d79c7c7cd41be80e44f56a1040908df98c3987744ab8"

      def install
        bin.install "baton-celigo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-celigo/releases/download/v0.0.1/baton-celigo-v0.0.1-linux-amd64.tar.gz"
      sha256 "bad612eb90256b899bf2ad8374e7cc7377711b5489c8eb4a96b035391133d384"

      def install
        bin.install "baton-celigo"
      end
    end
  end

  test do
    system "#{bin}/baton-celigo -v"
  end
end
