# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonGoogleCloudPlatform < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-google-cloud-platform/releases/download/v0.0.10/baton-google-cloud-platform-v0.0.10-darwin-amd64.zip"
      sha256 "4292c3a765afcb821c58c63e6c83b68a576f7f0bcf799825507769d17b524c75"

      def install
        bin.install "baton-google-cloud-platform"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-google-cloud-platform/releases/download/v0.0.10/baton-google-cloud-platform-v0.0.10-darwin-arm64.zip"
      sha256 "87f681018290693002e6d17ed3b09dba2feffd7d52c0cb496364c6dd1eb4d66b"

      def install
        bin.install "baton-google-cloud-platform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-google-cloud-platform/releases/download/v0.0.10/baton-google-cloud-platform-v0.0.10-linux-amd64.tar.gz"
        sha256 "8bf8c513c6709ac82e93eca529febb48f44b86ce8e89553d020f43836773e361"

        def install
          bin.install "baton-google-cloud-platform"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-google-cloud-platform/releases/download/v0.0.10/baton-google-cloud-platform-v0.0.10-linux-arm64.tar.gz"
        sha256 "67c5e035100e881fa97d6b5e433e0c4744663c2360b45167b19ce982a364ef68"

        def install
          bin.install "baton-google-cloud-platform"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-google-cloud-platform -v"
  end
end
