# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class BatonDemo < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-demo/releases/download/v0.0.4/baton-demo-v0.0.4-darwin-amd64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7dfd45346440ea0bbf04d983aecada9186e41931fb59c74908a1489a9acba990"

      def install
        bin.install "baton-demo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-demo/releases/download/v0.0.4/baton-demo-v0.0.4-darwin-arm64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "10605c82a77ac4513b4801b29c51deedafc00a932d847ca3053534fa090f445f"

      def install
        bin.install "baton-demo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-demo/releases/download/v0.0.4/baton-demo-v0.0.4-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "487a62290d99634db8b763afe70e71b686572c4ae73ce5aa8e8faf0197bb9dea"

      def install
        bin.install "baton-demo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-demo/releases/download/v0.0.4/baton-demo-v0.0.4-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c852ef075eca22d7871546fd3398990ae34a9677adb71bd41d5287116c28a9bf"

      def install
        bin.install "baton-demo"
      end
    end
  end

  test do
    system "#{bin}/baton-demo -v"
  end
end
