# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonActiveDirectory < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-active-directory/releases/download/v0.5.0/baton-active-directory-v0.5.0-darwin-amd64.zip"
      sha256 "ad98e44896c76a54599749f092f70c793c0a38180554fb892e6588c6ef003679"

      def install
        bin.install "baton-active-directory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-active-directory/releases/download/v0.5.0/baton-active-directory-v0.5.0-darwin-arm64.zip"
      sha256 "9c85bde8f03a67e48ef7092ef51d7a55654fd96c44c5d705606fceb9f21dc076"

      def install
        bin.install "baton-active-directory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-active-directory/releases/download/v0.5.0/baton-active-directory-v0.5.0-linux-amd64.tar.gz"
      sha256 "92e46634e956659170335f7b783679ec9b46634be8b6d0eb2d4c560141594e5f"
      def install
        bin.install "baton-active-directory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-active-directory/releases/download/v0.5.0/baton-active-directory-v0.5.0-linux-arm64.tar.gz"
      sha256 "37d5cdf2555d2407eda63729281ab07a409cde3695f24086a6db4d9ad0ed59ff"
      def install
        bin.install "baton-active-directory"
      end
    end
  end

  test do
    system "#{bin}/baton-active-directory -v"
  end
end
