# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonBroadcomSac < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-broadcom-sac/releases/download/v0.0.4/baton-broadcom-sac-v0.0.4-darwin-amd64.zip"
      sha256 "89cfa522443c77896465bb0ea6b024eaa744f446d01a6b5eb52e37d1b5657a42"

      def install
        bin.install "baton-broadcom-sac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-broadcom-sac/releases/download/v0.0.4/baton-broadcom-sac-v0.0.4-darwin-arm64.zip"
      sha256 "1be9540483e7e6708dbf7c2c5da479104b4955dde4017461617bb0d6151e78e5"

      def install
        bin.install "baton-broadcom-sac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-broadcom-sac/releases/download/v0.0.4/baton-broadcom-sac-v0.0.4-linux-arm64.tar.gz"
      sha256 "9c0846af5622f8d4d75460b945fed9f043a15caf93d06759bf865c56ed931831"

      def install
        bin.install "baton-broadcom-sac"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-broadcom-sac/releases/download/v0.0.4/baton-broadcom-sac-v0.0.4-linux-amd64.tar.gz"
      sha256 "07e2f5cbb384adc858f63e28abe696b6e8381733795ebba8c236dbc0f6917ce3"

      def install
        bin.install "baton-broadcom-sac"
      end
    end
  end

  test do
    system "#{bin}/baton-broadcom-sac -v"
  end
end
