# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSmartsheet < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-smartsheet/releases/download/v0.0.2/baton-smartsheet-v0.0.2-darwin-amd64.zip"
      sha256 "8f0b8bac9b6544d49b68012f0ced4e7eb6b2096ebf56ec61ca7532b7110b4b32"

      def install
        bin.install "baton-smartsheet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-smartsheet/releases/download/v0.0.2/baton-smartsheet-v0.0.2-darwin-arm64.zip"
      sha256 "40c553145dc89f3c8fb82efe0735db0e78bbe5e58f28a91999e383534c6998f3"

      def install
        bin.install "baton-smartsheet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-smartsheet/releases/download/v0.0.2/baton-smartsheet-v0.0.2-linux-amd64.tar.gz"
        sha256 "f0c50e4a6e7835e5ae8a8b525c627deecb8ced89da1014331e31167b0c9b3e74"

        def install
          bin.install "baton-smartsheet"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-smartsheet/releases/download/v0.0.2/baton-smartsheet-v0.0.2-linux-arm64.tar.gz"
        sha256 "d2c658814319792452a5a54da307530f8c6cd92e93bb2f91d49e2360717368df"

        def install
          bin.install "baton-smartsheet"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-smartsheet -v"
  end
end
