# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOkta < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.5.28"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-okta/releases/download/v0.5.28/baton-okta-v0.5.28-darwin-amd64.zip"
      sha256 "37b3b89e9870664795ee16f66b9c3996fdb1ecb4ea3bed74cf3f3ca15756228a"

      def install
        bin.install "baton-okta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-okta/releases/download/v0.5.28/baton-okta-v0.5.28-darwin-arm64.zip"
      sha256 "a1523e785052e873acc176bea679c7ea6cbcc57dbf9ecfc85bbf4541aee8e3c1"

      def install
        bin.install "baton-okta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-okta/releases/download/v0.5.28/baton-okta-v0.5.28-linux-amd64.tar.gz"
      sha256 "ae485215f88b4a9220d0d1579cb77bf9f41e7c08e68b787772830c79e661909b"
      def install
        bin.install "baton-okta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-okta/releases/download/v0.5.28/baton-okta-v0.5.28-linux-arm64.tar.gz"
      sha256 "0bdce3d104b93658c9b4bbcefce629eb6f1c3ce0d9706dda52f3b2f0c154cbc7"
      def install
        bin.install "baton-okta"
      end
    end
  end

  test do
    system "#{bin}/baton-okta -v"
  end
end
