# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonAsana < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-asana/releases/download/v0.0.10/baton-asana-v0.0.10-darwin-amd64.zip"
      sha256 "36ee9d41c1ecea5c91992dd546797b31bee3486ff1b59c2ecba275b1d1949cc3"

      def install
        bin.install "baton-asana"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-asana/releases/download/v0.0.10/baton-asana-v0.0.10-darwin-arm64.zip"
      sha256 "c0313633253ddb886f28c61970f06b7e08ef52e638a293d644ba558eabdd0462"

      def install
        bin.install "baton-asana"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-asana/releases/download/v0.0.10/baton-asana-v0.0.10-linux-amd64.tar.gz"
        sha256 "020ee665e647a0177043350770458c58157384ab120de737d15f6e5d0bbd98d7"

        def install
          bin.install "baton-asana"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-asana/releases/download/v0.0.10/baton-asana-v0.0.10-linux-arm64.tar.gz"
        sha256 "e49366964eeb8811538eb9e11c62f4a14310535cd8077fb08555d8bf0eecd124"

        def install
          bin.install "baton-asana"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-asana -v"
  end
end
