# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonAzure < Formula
  desc ""
  homepage "https://conductorone.com"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-azure/releases/download/v1.1.0/baton-azure-v1.1.0-darwin-amd64.zip"
      sha256 "b3b67109cd65233072d6c8a6d5a1dab752d0827eac3ecaa7de78612a5ed0a458"

      def install
        bin.install "baton-azure"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-azure/releases/download/v1.1.0/baton-azure-v1.1.0-darwin-arm64.zip"
      sha256 "7ce4389a70f7fe5cd1d427a467efd38851aa5dcefb1936f099671c671750180f"

      def install
        bin.install "baton-azure"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-azure/releases/download/v1.1.0/baton-azure-v1.1.0-linux-amd64.tar.gz"
      sha256 "33c47c34ef31e16f643aec7861e8df1da6bcd8d93bc4f5eed7a761588ef2325d"
      def install
        bin.install "baton-azure"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-azure/releases/download/v1.1.0/baton-azure-v1.1.0-linux-arm64.tar.gz"
      sha256 "a654aa847ddf63136645dd687dc35d0932023f2993b251fbac9ee46744cc90bf"
      def install
        bin.install "baton-azure"
      end
    end
  end

  test do
    system "#{bin}/baton-azure -v"
  end
end
