# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOkta < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.19"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-okta/releases/download/v0.1.19/baton-okta-v0.1.19-darwin-amd64.zip"
      sha256 "1e0330bda91b1894604758907ddb99bccff904c231c14623b16dc84542ed9221"

      def install
        bin.install "baton-okta"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-okta/releases/download/v0.1.19/baton-okta-v0.1.19-darwin-arm64.zip"
      sha256 "5d14b76ed0a93fda4e5c53908a723b16b4612ea214cf1341732b9bff8441fad9"

      def install
        bin.install "baton-okta"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-okta/releases/download/v0.1.19/baton-okta-v0.1.19-linux-amd64.tar.gz"
        sha256 "0790e16a5705ca151fd7398ba6f4d6dbff24c2a99725d7a7fd7b369a8ba775b1"

        def install
          bin.install "baton-okta"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-okta/releases/download/v0.1.19/baton-okta-v0.1.19-linux-arm64.tar.gz"
        sha256 "da90851a03fbdb334507e44e6714a35ecbf662c1a61a798befbd0fb4c7cc1037"

        def install
          bin.install "baton-okta"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-okta -v"
  end
end
