# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonWorkato < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.10-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-workato/releases/download/v0.0.10-beta.1/baton-workato-v0.0.10-beta.1-darwin-amd64.zip"
      sha256 "13c0b9589326b6a71ef5cd062f9b498ae2b8414b16aa7bcd4b998adedc45df2c"

      def install
        bin.install "baton-workato"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-workato/releases/download/v0.0.10-beta.1/baton-workato-v0.0.10-beta.1-darwin-arm64.zip"
      sha256 "753d8522e46f88669565f2d29b230e178bf87eebe52eaf7aea47971319c46b30"

      def install
        bin.install "baton-workato"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-workato/releases/download/v0.0.10-beta.1/baton-workato-v0.0.10-beta.1-linux-amd64.tar.gz"
      sha256 "e5890e65419061a77c70e5aa14de7c8f5a4ff110f7e2e147532772e36f7a84e8"
      def install
        bin.install "baton-workato"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-workato/releases/download/v0.0.10-beta.1/baton-workato-v0.0.10-beta.1-linux-arm64.tar.gz"
      sha256 "9166d590f1de0de8491f15c45c1d70baa747d60717b214b98afc370c7daf011a"
      def install
        bin.install "baton-workato"
      end
    end
  end

  test do
    system "#{bin}/baton-workato -v"
  end
end
