# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonJiraDatacenter < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.24"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-jira-datacenter/releases/download/v0.0.24/baton-jira-datacenter-v0.0.24-darwin-amd64.zip"
      sha256 "163808200efced2f57f2ca8a3d5e95d5a40317dadcbb70f44a1e9c6760b14471"

      def install
        bin.install "baton-jira-datacenter"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-jira-datacenter/releases/download/v0.0.24/baton-jira-datacenter-v0.0.24-darwin-arm64.zip"
      sha256 "8dd24ea6f990ea602c41de9092bd4967e0d23e02ab46d1a7b9ecf2af475f9f4a"

      def install
        bin.install "baton-jira-datacenter"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-jira-datacenter/releases/download/v0.0.24/baton-jira-datacenter-v0.0.24-linux-amd64.tar.gz"
        sha256 "bfbbb621eeea6a4c02f87ac4e0fa9fccd8a06575ff9b9d5e26d5df391cf036f2"

        def install
          bin.install "baton-jira-datacenter"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-jira-datacenter/releases/download/v0.0.24/baton-jira-datacenter-v0.0.24-linux-arm64.tar.gz"
        sha256 "21a518cac8155ce17f0c59165691c4b328547acd2f6e528500d726ef4c8f3845"

        def install
          bin.install "baton-jira-datacenter"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-jira-datacenter -v"
  end
end
