# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonDatabricks < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-databricks/releases/download/v0.1.5/baton-databricks-v0.1.5-darwin-amd64.zip"
      sha256 "9cb09ee89fb8ca30443813231236ec22850c805570c79846eafed49f43517349"

      def install
        bin.install "baton-databricks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-databricks/releases/download/v0.1.5/baton-databricks-v0.1.5-darwin-arm64.zip"
      sha256 "c86f8a996a8f07f4962205fafd50249b35b6b21b4f1c5d1809fe8ac835de647d"

      def install
        bin.install "baton-databricks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-databricks/releases/download/v0.1.5/baton-databricks-v0.1.5-linux-amd64.tar.gz"
      sha256 "098a12da1da19ec76550ab8a5ba8fb21582cfc319d6a161fd46b01dd4bb7540c"
      def install
        bin.install "baton-databricks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-databricks/releases/download/v0.1.5/baton-databricks-v0.1.5-linux-arm64.tar.gz"
      sha256 "194735fe16ccf2fe9947b2d978d68bfc5efc5bdf08541c95a29035c7dc29da7f"
      def install
        bin.install "baton-databricks"
      end
    end
  end

  test do
    system "#{bin}/baton-databricks -v"
  end
end
