# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonRunner < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.12-test.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-runner/releases/download/v0.1.12-test.12/baton-runner-v0.1.12-test.12-darwin-amd64.zip"
      sha256 "e1d0816e5d842922ab25aef7089c9a882b17b6294ad087518e52880be0a95923"

      def install
        bin.install "baton-runner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-runner/releases/download/v0.1.12-test.12/baton-runner-v0.1.12-test.12-darwin-arm64.zip"
      sha256 "9d111a2be01e10799246df26f6edeacf8b70b703672117f71d6cd995ae640c3c"

      def install
        bin.install "baton-runner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-runner/releases/download/v0.1.12-test.12/baton-runner-v0.1.12-test.12-linux-amd64.tar.gz"
      sha256 "d548efb952f252df8f9808b60316c2a8931fefd2ae50c26f0474c25982ed0935"
      def install
        bin.install "baton-runner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-runner/releases/download/v0.1.12-test.12/baton-runner-v0.1.12-test.12-linux-arm64.tar.gz"
      sha256 "d443a3069abbcae047f6f30ce681d63561e710e52b91f85d36cae78db3befcee"
      def install
        bin.install "baton-runner"
      end
    end
  end

  test do
    system "#{bin}/baton-runner -v"
  end
end
