# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonZuora < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-zuora/releases/download/v0.0.1/baton-zuora-v0.0.1-darwin-amd64.zip"
      sha256 "1c318e702d26bb2a9f762ab1967fbfa116f784c220403de5ac3ad474f199c5ca"

      def install
        bin.install "baton-zuora"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-zuora/releases/download/v0.0.1/baton-zuora-v0.0.1-darwin-arm64.zip"
      sha256 "1a42dbc00c695fe6c631d80e1d53e519b14a315671a91b4ec48c9a65db488e1e"

      def install
        bin.install "baton-zuora"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-zuora/releases/download/v0.0.1/baton-zuora-v0.0.1-linux-amd64.tar.gz"
      sha256 "92bd36748583ab2513224cef7caa0eddf3e5653c742fdccfc15d1ffe5a5b200c"
      def install
        bin.install "baton-zuora"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-zuora/releases/download/v0.0.1/baton-zuora-v0.0.1-linux-arm64.tar.gz"
      sha256 "41e65d66ee3003e5fac359753841968a6b1b028cf76619d38db2f79918d4b38b"
      def install
        bin.install "baton-zuora"
      end
    end
  end

  test do
    system "#{bin}/baton-zuora -v"
  end
end
