# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonPingOne < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-ping-one/releases/download/v0.0.5/baton-ping-one-v0.0.5-darwin-amd64.zip"
      sha256 "62a06d01bb7e6b7ab3d5be9ac3ca92f9cb068a364bee13a63cf3744c929a2fbd"

      def install
        bin.install "baton-ping-one"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-ping-one/releases/download/v0.0.5/baton-ping-one-v0.0.5-darwin-arm64.zip"
      sha256 "edc655c128da40efca727b6e044420a68233e5b72dae622dc05df65baa8da95c"

      def install
        bin.install "baton-ping-one"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-ping-one/releases/download/v0.0.5/baton-ping-one-v0.0.5-linux-amd64.tar.gz"
        sha256 "576f4496c61baedd2edbc1c08f426372fd67a848860d4b304ba8d02b70daad44"

        def install
          bin.install "baton-ping-one"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-ping-one/releases/download/v0.0.5/baton-ping-one-v0.0.5-linux-arm64.tar.gz"
        sha256 "37c962a872f1e0b89932782076db569d6e92213fa6572587d8421b13ba719f2b"

        def install
          bin.install "baton-ping-one"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-ping-one -v"
  end
end
