# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonEks < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-eks/releases/download/v0.0.3/baton-eks-v0.0.3-darwin-amd64.zip"
      sha256 "85b25c7614643d774a89b0109af1c57ed444d35203ec51c4e792b250884a550f"

      def install
        bin.install "baton-eks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-eks/releases/download/v0.0.3/baton-eks-v0.0.3-darwin-arm64.zip"
      sha256 "32911bee2c4396f817d7cff5f5346fa7d50197c1d48f5b496bde4d2644216fef"

      def install
        bin.install "baton-eks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-eks/releases/download/v0.0.3/baton-eks-v0.0.3-linux-amd64.tar.gz"
        sha256 "8c4edea906c035f44364afcb0d6f005593037cdd2bca9fe1967a9c541f8d72b6"

        def install
          bin.install "baton-eks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-eks/releases/download/v0.0.3/baton-eks-v0.0.3-linux-arm64.tar.gz"
        sha256 "f9285086d49dc78d03eec0285df3c7cd67b4d1c9d465e362979384ad098e8acb"

        def install
          bin.install "baton-eks"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-eks -v"
  end
end
