# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonPipedrive < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-pipedrive/releases/download/v0.3.0/baton-pipedrive-v0.3.0-darwin-amd64.zip"
      sha256 "8561f044994338ee6178b888b2ed704977aa96b333d4be6d6f940aa66cb438a0"

      def install
        bin.install "baton-pipedrive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-pipedrive/releases/download/v0.3.0/baton-pipedrive-v0.3.0-darwin-arm64.zip"
      sha256 "e40a47036683aa8621a6b30cae476c6e435548131323e1fabcd112259b0a3533"

      def install
        bin.install "baton-pipedrive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-pipedrive/releases/download/v0.3.0/baton-pipedrive-v0.3.0-linux-amd64.tar.gz"
      sha256 "fde3c403d3949a3c66e307276884e6e4d18f16c4c9408a820ee7606102a54c18"
      def install
        bin.install "baton-pipedrive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-pipedrive/releases/download/v0.3.0/baton-pipedrive-v0.3.0-linux-arm64.tar.gz"
      sha256 "9add6863d7167a9d6202b1b940358c4dd967d883a6ae2ac473d86731e6fd4636"
      def install
        bin.install "baton-pipedrive"
      end
    end
  end

  test do
    system "#{bin}/baton-pipedrive -v"
  end
end
