# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonLaunchdarkly < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-launchdarkly/releases/download/v0.0.3/baton-launchdarkly-v0.0.3-darwin-amd64.zip"
      sha256 "c9f196f62016d2d70ba036211622699675582c820b9d412cfbba65c9a9ab11b7"

      def install
        bin.install "baton-launchdarkly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-launchdarkly/releases/download/v0.0.3/baton-launchdarkly-v0.0.3-darwin-arm64.zip"
      sha256 "3bda6c7652329a1de4d9fcae3caf97269d8b71a96d93e6e85af460b33703ae2e"

      def install
        bin.install "baton-launchdarkly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-launchdarkly/releases/download/v0.0.3/baton-launchdarkly-v0.0.3-linux-amd64.tar.gz"
        sha256 "23fe6fb7ab461d931bc15da275921c4838dce6a2074356b2e5a8851f40525fd6"

        def install
          bin.install "baton-launchdarkly"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-launchdarkly/releases/download/v0.0.3/baton-launchdarkly-v0.0.3-linux-arm64.tar.gz"
        sha256 "3af13fc846b85f0dac137de1c91f02113ff035339e832a526d553cbbd021c65d"

        def install
          bin.install "baton-launchdarkly"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-launchdarkly -v"
  end
end
