# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOktaCiamWorkforce < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-okta-ciam-workforce/releases/download/v0.1.0/baton-okta-ciam-workforce-v0.1.0-darwin-amd64.zip"
      sha256 "9d8717c3b0b489bcb0d39faf7ebc74f3d3cf7ffd2abde37e0ffc762b9651a68c"

      def install
        bin.install "baton-okta-ciam-workforce"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-okta-ciam-workforce/releases/download/v0.1.0/baton-okta-ciam-workforce-v0.1.0-darwin-arm64.zip"
      sha256 "c629af5ea0fa6d922b750c565f2c1bd6a43d18b1ce5ea4d9d7c623fcd8f00085"

      def install
        bin.install "baton-okta-ciam-workforce"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-okta-ciam-workforce/releases/download/v0.1.0/baton-okta-ciam-workforce-v0.1.0-linux-amd64.tar.gz"
      sha256 "ddf3709bfadb7af3dbb5585da40c9af825b3dbe67886b2f3128c41c52e204d9d"
      def install
        bin.install "baton-okta-ciam-workforce"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-okta-ciam-workforce/releases/download/v0.1.0/baton-okta-ciam-workforce-v0.1.0-linux-arm64.tar.gz"
      sha256 "c668b4e1a60ac9b869516e49e75cd23636c21c7ec4d1125d766599495d4a584a"
      def install
        bin.install "baton-okta-ciam-workforce"
      end
    end
  end

  test do
    system "#{bin}/baton-okta-ciam-workforce -v"
  end
end
