# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonRamp < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-ramp/releases/download/v0.0.2/baton-ramp-v0.0.2-darwin-amd64.zip"
      sha256 "3cb84af4ec9314c5eef501bca6cec6a48a3164d81117b9b097b2cc55377b8cf3"

      def install
        bin.install "baton-ramp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-ramp/releases/download/v0.0.2/baton-ramp-v0.0.2-darwin-arm64.zip"
      sha256 "e083d4e67e5b38f9e0a032628d43cc472cc47079c2d4e4fec6061b38a8a47fbd"

      def install
        bin.install "baton-ramp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-ramp/releases/download/v0.0.2/baton-ramp-v0.0.2-linux-amd64.tar.gz"
        sha256 "ba334f9f489a91a677572297df185b53348c7ceeeea7922af213352c30df8fa0"

        def install
          bin.install "baton-ramp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-ramp/releases/download/v0.0.2/baton-ramp-v0.0.2-linux-arm64.tar.gz"
        sha256 "b019967d0acbc0a5681ecd364e912e7dc4ffba287e83020552d553033f93d57a"

        def install
          bin.install "baton-ramp"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-ramp -v"
  end
end
