# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSigmacomputing < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-sigmacomputing/releases/download/v0.1.1/baton-sigmacomputing-v0.1.1-darwin-amd64.zip"
      sha256 "f6468c41829d661d9956d28c677a62394cf436c59c0c5e183171212c757369f9"

      def install
        bin.install "baton-sigmacomputing"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-sigmacomputing/releases/download/v0.1.1/baton-sigmacomputing-v0.1.1-darwin-arm64.zip"
      sha256 "bd4eee778254b8eb90e23b8ae85e0e57d742072a402c28765c8c191021192104"

      def install
        bin.install "baton-sigmacomputing"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-sigmacomputing/releases/download/v0.1.1/baton-sigmacomputing-v0.1.1-linux-amd64.tar.gz"
      sha256 "99c0a8d1088a7e2e23317388ed41ae8bb74ac5b831c83efbc99a2b281ad148b6"
      def install
        bin.install "baton-sigmacomputing"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-sigmacomputing/releases/download/v0.1.1/baton-sigmacomputing-v0.1.1-linux-arm64.tar.gz"
      sha256 "887770fae106fdafe9cdc66a458aa73345be8b9075e0014d4b34dbe0a25b0c60"
      def install
        bin.install "baton-sigmacomputing"
      end
    end
  end

  test do
    system "#{bin}/baton-sigmacomputing -v"
  end
end
