# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonVgs < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-vgs/releases/download/v0.0.3/baton-vgs-v0.0.3-darwin-amd64.zip"
      sha256 "75cad280b56dccc02b7d12602456a83edeb4b066380ee93d6cfeaa4310be0743"

      def install
        bin.install "baton-vgs"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-vgs/releases/download/v0.0.3/baton-vgs-v0.0.3-darwin-arm64.zip"
      sha256 "42c411d7451fd8e3254262e162cf8b92e7772569f8e4495fe5ec6d39ad46ff8d"

      def install
        bin.install "baton-vgs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-vgs/releases/download/v0.0.3/baton-vgs-v0.0.3-linux-amd64.tar.gz"
        sha256 "cdca6e2b8082cb3e6ac8ff2cc92b3db59f07090bbc4fe46b4755441206d756be"

        def install
          bin.install "baton-vgs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-vgs/releases/download/v0.0.3/baton-vgs-v0.0.3-linux-arm64.tar.gz"
        sha256 "722812b16ac76d604735ccc95d1175f04210844782c10d6c39226813cd3de7a5"

        def install
          bin.install "baton-vgs"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-vgs -v"
  end
end
