# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOpsgenie < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-opsgenie/releases/download/v0.0.8/baton-opsgenie-v0.0.8-darwin-amd64.zip"
      sha256 "5785d23e97cb7940f5ca4e7ef70ea27161e9e64396f30f5797b3ae07e2c7e265"

      def install
        bin.install "baton-opsgenie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-opsgenie/releases/download/v0.0.8/baton-opsgenie-v0.0.8-darwin-arm64.zip"
      sha256 "8abbdcaa73eb884e0ea315e68373ab7b0f61f528b9cd9eb7a47be14866ed9b1d"

      def install
        bin.install "baton-opsgenie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-opsgenie/releases/download/v0.0.8/baton-opsgenie-v0.0.8-linux-amd64.tar.gz"
        sha256 "a62b875a6e16b20f8c5ebf21f00edefde434bcf21ef33c9c499d9a36c8dcf0b1"

        def install
          bin.install "baton-opsgenie"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-opsgenie/releases/download/v0.0.8/baton-opsgenie-v0.0.8-linux-arm64.tar.gz"
        sha256 "c1c63dde5257198e840ac5a6d82c1289246e00e1b946278d8d799b239a58e4d3"

        def install
          bin.install "baton-opsgenie"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-opsgenie -v"
  end
end
