# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonGrafana < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-grafana/releases/download/v0.0.5/baton-grafana-v0.0.5-darwin-amd64.zip"
      sha256 "ac22d293eeb08f3768c0f52eeab541db47db87adc597f777bb7dc41261c74dd3"

      def install
        bin.install "baton-grafana"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-grafana/releases/download/v0.0.5/baton-grafana-v0.0.5-darwin-arm64.zip"
      sha256 "9e54ffda12a75f6c0faf9000b387d1d33329ec90af73e484c27d44f5fe3a6fab"

      def install
        bin.install "baton-grafana"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-grafana/releases/download/v0.0.5/baton-grafana-v0.0.5-linux-amd64.tar.gz"
      sha256 "17afa6098e179cf9b810a1935a7ab5c9015ed6deb9c34f112f4718e86392e294"
      def install
        bin.install "baton-grafana"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-grafana/releases/download/v0.0.5/baton-grafana-v0.0.5-linux-arm64.tar.gz"
      sha256 "d014d60d2adef4a138f73aabac1066ffc8f3866a1d4445cdc8c3b169061296bd"
      def install
        bin.install "baton-grafana"
      end
    end
  end

  test do
    system "#{bin}/baton-grafana -v"
  end
end
