# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonGreenhouse < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-greenhouse/releases/download/v0.0.9/baton-greenhouse-v0.0.9-darwin-amd64.zip"
      sha256 "17964afc3121901e03c5c0eac4bd4fbf2680df76d6ce3631d2002099bfef59c9"

      def install
        bin.install "baton-greenhouse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-greenhouse/releases/download/v0.0.9/baton-greenhouse-v0.0.9-darwin-arm64.zip"
      sha256 "8ac5c960599d39e7c764aaac140a069a61f01a71540af0c4cacbe890cb2bb2c8"

      def install
        bin.install "baton-greenhouse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-greenhouse/releases/download/v0.0.9/baton-greenhouse-v0.0.9-linux-amd64.tar.gz"
      sha256 "4a2b5cc10d89bbc4810972682aaf2d8095cf4f21494d5dc83942b873007d3a0d"
      def install
        bin.install "baton-greenhouse"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-greenhouse/releases/download/v0.0.9/baton-greenhouse-v0.0.9-linux-arm64.tar.gz"
      sha256 "eba28efe263f9332f4e9e1af2afcfd256bf33ef0774d31096d86c7e235561d25"
      def install
        bin.install "baton-greenhouse"
      end
    end
  end

  test do
    system "#{bin}/baton-greenhouse -v"
  end
end
