# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonLdap < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.15"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-ldap/releases/download/v0.0.15/baton-ldap-v0.0.15-darwin-amd64.zip"
      sha256 "92811c977bfafb7e6a9479d49eb057a79e02d75f0f4dc0dc13b70b24b445362c"

      def install
        bin.install "baton-ldap"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-ldap/releases/download/v0.0.15/baton-ldap-v0.0.15-darwin-arm64.zip"
      sha256 "3ff23c25e6ad39964ee366a9634c2645e2c15585e3386e479907161cbd89f7bd"

      def install
        bin.install "baton-ldap"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-ldap/releases/download/v0.0.15/baton-ldap-v0.0.15-linux-amd64.tar.gz"
        sha256 "679a305805180538299e9ddbc7d6213d1b7ae80462e1a6d07307e9c329459d3f"

        def install
          bin.install "baton-ldap"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-ldap/releases/download/v0.0.15/baton-ldap-v0.0.15-linux-arm64.tar.gz"
        sha256 "25012266fdfa62e4e77e8fd4e2593f18d9157bff648633b742f60ad09ff55f10"

        def install
          bin.install "baton-ldap"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-ldap -v"
  end
end
