# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSql < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-sql/releases/download/v0.0.10/baton-sql-v0.0.10-darwin-amd64.zip"
      sha256 "9b306916146301cfb577e08656d22c96a14a67d8076c2dbe0fba9c879c17485b"

      def install
        bin.install "baton-sql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-sql/releases/download/v0.0.10/baton-sql-v0.0.10-darwin-arm64.zip"
      sha256 "7cf328f0aad40aa22274b4cd99e687519684da9ed8557c0443e7b26a9b51a179"

      def install
        bin.install "baton-sql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-sql/releases/download/v0.0.10/baton-sql-v0.0.10-linux-amd64.tar.gz"
        sha256 "d42494804184c33260e160cf8c7044127ec3f485f2aa6429899b22d0a6607edc"

        def install
          bin.install "baton-sql"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-sql/releases/download/v0.0.10/baton-sql-v0.0.10-linux-arm64.tar.gz"
        sha256 "8efbcbd505487c86c15d3587586b9b24e29b4d8b1ea0aa5729cbee32f839944f"

        def install
          bin.install "baton-sql"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-sql -v"
  end
end
