# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonMongodbAtlas < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.18-add-resource-delete-v2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-mongodb-atlas/releases/download/v0.0.18-add-resource-delete-v2/baton-mongodb-atlas-v0.0.18-add-resource-delete-v2-darwin-amd64.zip"
      sha256 "6b762b22c78876186ee0c9aa8a927c9daca25a5640cb1387eca0428590e39b92"

      def install
        bin.install "baton-mongodb-atlas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-mongodb-atlas/releases/download/v0.0.18-add-resource-delete-v2/baton-mongodb-atlas-v0.0.18-add-resource-delete-v2-darwin-arm64.zip"
      sha256 "7d45b160a711e35801d5c27a80f822513b6c5c23b2f3c2c2b4cf2d39ef96577b"

      def install
        bin.install "baton-mongodb-atlas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-mongodb-atlas/releases/download/v0.0.18-add-resource-delete-v2/baton-mongodb-atlas-v0.0.18-add-resource-delete-v2-linux-amd64.tar.gz"
        sha256 "81afc0cdef5b46928f482b8525047b4cedeab02e4a615a2e31bdf98edc9201cd"

        def install
          bin.install "baton-mongodb-atlas"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-mongodb-atlas/releases/download/v0.0.18-add-resource-delete-v2/baton-mongodb-atlas-v0.0.18-add-resource-delete-v2-linux-arm64.tar.gz"
        sha256 "6f10e40d4714904fc4851d510af958fa4ca11f333f6e4c4e329e3a9516565011"

        def install
          bin.install "baton-mongodb-atlas"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-mongodb-atlas -v"
  end
end
