# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonWhimsical < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-whimsical/releases/download/v0.0.5/baton-whimsical-v0.0.5-darwin-amd64.zip"
      sha256 "e3db88bb0a5d13574104bf4def5166d3ff3d2b26edf80765a08be5eed2b86e45"

      def install
        bin.install "baton-whimsical"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-whimsical/releases/download/v0.0.5/baton-whimsical-v0.0.5-darwin-arm64.zip"
      sha256 "e709421736f1759ba1bf87a83957bb0a3d439f8ecbbef3bdb0bb02e92ce17f92"

      def install
        bin.install "baton-whimsical"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-whimsical/releases/download/v0.0.5/baton-whimsical-v0.0.5-linux-amd64.tar.gz"
      sha256 "ba751054e9380ed58992b27d4a539285e26113c337b2d377ee80598e546eaac1"
      def install
        bin.install "baton-whimsical"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-whimsical/releases/download/v0.0.5/baton-whimsical-v0.0.5-linux-arm64.tar.gz"
      sha256 "2bc5855ee2b204d3d29903a0f75e3fa9ccdbd2060025ed8d896a8955715a983f"
      def install
        bin.install "baton-whimsical"
      end
    end
  end

  test do
    system "#{bin}/baton-whimsical -v"
  end
end
