# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSevenshifts < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-sevenshifts/releases/download/v0.0.6/baton-sevenshifts-v0.0.6-darwin-amd64.zip"
      sha256 "c7dfade1f26195cb94734261f0622aa2d232675de6fc3b41fc57535443710489"

      def install
        bin.install "baton-sevenshifts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-sevenshifts/releases/download/v0.0.6/baton-sevenshifts-v0.0.6-darwin-arm64.zip"
      sha256 "5c2b1a2b9355918aaabb25ec8a74748e3512d1cadc91f966d71aacf601650b33"

      def install
        bin.install "baton-sevenshifts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-sevenshifts/releases/download/v0.0.6/baton-sevenshifts-v0.0.6-linux-amd64.tar.gz"
        sha256 "9aaec09767a9623b4dd0d2c0b88cc6add439da12a5579cd1e8cf6dddff18292a"

        def install
          bin.install "baton-sevenshifts"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-sevenshifts/releases/download/v0.0.6/baton-sevenshifts-v0.0.6-linux-arm64.tar.gz"
        sha256 "e364190f5859ffd3bea9a7c54fd1b09ae0deb7dab5b7e8be7c355b11fcaed369"

        def install
          bin.install "baton-sevenshifts"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-sevenshifts -v"
  end
end
