# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonGoogleWorkspace < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.2.29"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-google-workspace/releases/download/v0.2.29/baton-google-workspace-v0.2.29-darwin-amd64.zip"
      sha256 "b5b738030842f9e8d1bdcd53f210249d206747d0479098ecd425ea23af7c5070"

      def install
        bin.install "baton-google-workspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-google-workspace/releases/download/v0.2.29/baton-google-workspace-v0.2.29-darwin-arm64.zip"
      sha256 "3f6d42bd4674d4e7ccabfb62ba4d89bffac5a371aaf56bf84db3cdde4e112de0"

      def install
        bin.install "baton-google-workspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-google-workspace/releases/download/v0.2.29/baton-google-workspace-v0.2.29-linux-amd64.tar.gz"
        sha256 "1243f120022681fb1cd5aa2c93674f6c7be8e7a8fa11994612455982c8762360"

        def install
          bin.install "baton-google-workspace"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-google-workspace/releases/download/v0.2.29/baton-google-workspace-v0.2.29-linux-arm64.tar.gz"
        sha256 "e9931d387d1e6b8073c57e3d63e7f699317fd3a8e622d88ce8019e59fccdc9ff"

        def install
          bin.install "baton-google-workspace"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-google-workspace -v"
  end
end
