# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSmartsheet < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-smartsheet/releases/download/v0.1.1/baton-smartsheet-v0.1.1-darwin-amd64.zip"
      sha256 "d8b61e9dfc2ea5d2cd46285f59f18e0f1b3ef2eda514acc5b496256098709323"

      def install
        bin.install "baton-smartsheet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-smartsheet/releases/download/v0.1.1/baton-smartsheet-v0.1.1-darwin-arm64.zip"
      sha256 "18a17fc2ed3cd7e477985bb19a4a6d5f326b97c677d8bf2cb36e58ab74d94f5f"

      def install
        bin.install "baton-smartsheet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-smartsheet/releases/download/v0.1.1/baton-smartsheet-v0.1.1-linux-amd64.tar.gz"
      sha256 "ed7abe0732671ddff1946eb8fb91ff6053a00ae45bd5924ccf76ff47ecf858cf"
      def install
        bin.install "baton-smartsheet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-smartsheet/releases/download/v0.1.1/baton-smartsheet-v0.1.1-linux-arm64.tar.gz"
      sha256 "6d81fbdb0f11163498901a8856495f4cf61a87eaf124eaf74fa7498ac0394287"
      def install
        bin.install "baton-smartsheet"
      end
    end
  end

  test do
    system "#{bin}/baton-smartsheet -v"
  end
end
