# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonFullstory < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-fullstory/releases/download/v0.1.0/baton-fullstory-v0.1.0-darwin-amd64.zip"
      sha256 "1884cf9265ca364a6a268988d010df315c26b9bcfcb69803de20332c93efa4d9"

      def install
        bin.install "baton-fullstory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-fullstory/releases/download/v0.1.0/baton-fullstory-v0.1.0-darwin-arm64.zip"
      sha256 "150e963810e1abfa614ec21d547cba7c38cf714d8985a3263b33fbe1bd0cf765"

      def install
        bin.install "baton-fullstory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-fullstory/releases/download/v0.1.0/baton-fullstory-v0.1.0-linux-amd64.tar.gz"
      sha256 "aa7ed85b70256ecdf1f87937010cf743e9dd9882c86cf70ad24110d4382a964b"
      def install
        bin.install "baton-fullstory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-fullstory/releases/download/v0.1.0/baton-fullstory-v0.1.0-linux-arm64.tar.gz"
      sha256 "706c656a9a064977d5bed046b8fc4bdeb28d17a958309179eff907524de54ad4"
      def install
        bin.install "baton-fullstory"
      end
    end
  end

  test do
    system "#{bin}/baton-fullstory -v"
  end
end
