# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonWorkato < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-workato/releases/download/v0.0.14/baton-workato-v0.0.14-darwin-amd64.zip"
      sha256 "ef17bdd1cb72132e004d560d28c8095e6f49813a807787fc8bef63dcf789634e"

      def install
        bin.install "baton-workato"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-workato/releases/download/v0.0.14/baton-workato-v0.0.14-darwin-arm64.zip"
      sha256 "4b16ab50497de04cc35424fa957a8492b363fabf2eaa95389a94b87f3ef476d6"

      def install
        bin.install "baton-workato"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-workato/releases/download/v0.0.14/baton-workato-v0.0.14-linux-amd64.tar.gz"
      sha256 "1eb8b0db2dc9febd6b3530717a5d0286be80e45aad070727fadd55bdec943b70"
      def install
        bin.install "baton-workato"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-workato/releases/download/v0.0.14/baton-workato-v0.0.14-linux-arm64.tar.gz"
      sha256 "3608d3fc798bea9e75de6b64501803a1202adc54bd78b3ae463e04c50cb03d80"
      def install
        bin.install "baton-workato"
      end
    end
  end

  test do
    system "#{bin}/baton-workato -v"
  end
end
