# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonTeamviewer < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-teamviewer/releases/download/v0.0.3/baton-teamviewer-v0.0.3-darwin-amd64.zip"
      sha256 "8c772db5aba0aa73e0e1a18b6e15bb5316a24bbebbe5375deac3436035598ec3"

      def install
        bin.install "baton-teamviewer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-teamviewer/releases/download/v0.0.3/baton-teamviewer-v0.0.3-darwin-arm64.zip"
      sha256 "24cd8f440a909f83c6b73b86baf6d1bbb59e9a210393c2cd509750e5dc6bc792"

      def install
        bin.install "baton-teamviewer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-teamviewer/releases/download/v0.0.3/baton-teamviewer-v0.0.3-linux-amd64.tar.gz"
        sha256 "b8586941a5d44a3fa4c9c05c9c3110009a45a24c2e431a41ee74094179ae6120"

        def install
          bin.install "baton-teamviewer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-teamviewer/releases/download/v0.0.3/baton-teamviewer-v0.0.3-linux-arm64.tar.gz"
        sha256 "d10bbd4f7f9ec34b66f40d02db7869efeeb68b2d4f8f4bd417a5a01ccc08d00b"

        def install
          bin.install "baton-teamviewer"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-teamviewer -v"
  end
end
