# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonDropbox < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.4-alpha-3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-dropbox/releases/download/v0.0.4-alpha-3/baton-dropbox-v0.0.4-alpha-3-darwin-amd64.zip"
      sha256 "b35439e94e9fe6db8199f83efbeca1445bb76b607b3a30cb755727620af7112b"

      def install
        bin.install "baton-dropbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-dropbox/releases/download/v0.0.4-alpha-3/baton-dropbox-v0.0.4-alpha-3-darwin-arm64.zip"
      sha256 "418e133a79e569d8d4ac487313048201cf2e62899ec1f4f3eaa1aba27cbbddfe"

      def install
        bin.install "baton-dropbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-dropbox/releases/download/v0.0.4-alpha-3/baton-dropbox-v0.0.4-alpha-3-linux-amd64.tar.gz"
        sha256 "63ee246cefbbd7d94217f428409eb165e408cd59ba916c378175a2a751fbb566"

        def install
          bin.install "baton-dropbox"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-dropbox/releases/download/v0.0.4-alpha-3/baton-dropbox-v0.0.4-alpha-3-linux-arm64.tar.gz"
        sha256 "73ff428577354bc29aaafe5428bbc94bb428ebf01e2736960e09e7e9a907842f"

        def install
          bin.install "baton-dropbox"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-dropbox -v"
  end
end
