# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonConfluence < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.23"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-confluence/releases/download/v0.0.23/baton-confluence-v0.0.23-darwin-amd64.zip"
      sha256 "419c589d28ffb7ea055e07c79e6823d591a6827b75dc41c4b2c36f09edf197e7"

      def install
        bin.install "baton-confluence"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-confluence/releases/download/v0.0.23/baton-confluence-v0.0.23-darwin-arm64.zip"
      sha256 "39f5565fbf5bbeee796f7cb8a26668a97303b23cbbbe3d94c26d43b5078b0f83"

      def install
        bin.install "baton-confluence"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-confluence/releases/download/v0.0.23/baton-confluence-v0.0.23-linux-amd64.tar.gz"
      sha256 "2da5aa7653b652d3b94b902308a3311cc4fb31a32ac7a8591539c255b1124fb0"
      def install
        bin.install "baton-confluence"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-confluence/releases/download/v0.0.23/baton-confluence-v0.0.23-linux-arm64.tar.gz"
      sha256 "7e58c0db3db70311406729ea73a919937b69f0780c68be4e889c95cd1ba6f85c"
      def install
        bin.install "baton-confluence"
      end
    end
  end

  test do
    system "#{bin}/baton-confluence -v"
  end
end
