# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonNetlify < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-netlify/releases/download/v0.0.2/baton-netlify-v0.0.2-darwin-amd64.zip"
      sha256 "1dfb9d010834bb7c3ddb73f0ed245a555f16f6eef87ea4a9e5674255ef92c020"

      def install
        bin.install "baton-netlify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-netlify/releases/download/v0.0.2/baton-netlify-v0.0.2-darwin-arm64.zip"
      sha256 "bea93720083afdc2706ed5f1c4d28c48dc66d69d875f899a3e3c928035224e21"

      def install
        bin.install "baton-netlify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-netlify/releases/download/v0.0.2/baton-netlify-v0.0.2-linux-amd64.tar.gz"
        sha256 "43fc15f6fb3a941ec2185a50e49127a6c6a784328380b58e21ce25a86d77259e"

        def install
          bin.install "baton-netlify"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-netlify/releases/download/v0.0.2/baton-netlify-v0.0.2-linux-arm64.tar.gz"
        sha256 "36eb04ba923e96d78eff094caeeefc1bab802ef239340e61a85a1ddac3097b5e"

        def install
          bin.install "baton-netlify"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-netlify -v"
  end
end
