# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonMicrosoftEntra < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.2.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-microsoft-entra/releases/download/v0.2.13/baton-microsoft-entra-v0.2.13-darwin-amd64.zip"
      sha256 "0655b28d7a0e73977d454c2b1803f955a8344f530dbe593b0520ce54d13a0e7b"

      def install
        bin.install "baton-microsoft-entra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-microsoft-entra/releases/download/v0.2.13/baton-microsoft-entra-v0.2.13-darwin-arm64.zip"
      sha256 "f6b55db170fa8f057922bc906f59d7e2136bdf781a5caa51626050af89a73c61"

      def install
        bin.install "baton-microsoft-entra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-microsoft-entra/releases/download/v0.2.13/baton-microsoft-entra-v0.2.13-linux-amd64.tar.gz"
      sha256 "55daf614061eaf9daaaa0a5c9c2a10dea39903173ba6f731757e620a19613be6"
      def install
        bin.install "baton-microsoft-entra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-microsoft-entra/releases/download/v0.2.13/baton-microsoft-entra-v0.2.13-linux-arm64.tar.gz"
      sha256 "55fcaeb40a4b378d1df738b04ffe8cc9016b78215fcf46b74c28675b9317fa68"
      def install
        bin.install "baton-microsoft-entra"
      end
    end
  end

  test do
    system "#{bin}/baton-microsoft-entra -v"
  end
end
