# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOutreach < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-outreach/releases/download/v0.0.1/baton-outreach-v0.0.1-darwin-amd64.zip"
      sha256 "0ce7d2cecc666e5d61251c95ff8c0f4a14fa1606809019b3039594e8638cb01c"

      def install
        bin.install "baton-outreach"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-outreach/releases/download/v0.0.1/baton-outreach-v0.0.1-darwin-arm64.zip"
      sha256 "a80e95d6f174f1a2793084e916f59252b0483940cf386c8c6d1682e994426217"

      def install
        bin.install "baton-outreach"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-outreach/releases/download/v0.0.1/baton-outreach-v0.0.1-linux-amd64.tar.gz"
        sha256 "073aff9ddc8473d1229e8bfc930a80c7aa74eb905ed8c822079eeb68097f616c"

        def install
          bin.install "baton-outreach"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-outreach/releases/download/v0.0.1/baton-outreach-v0.0.1-linux-arm64.tar.gz"
        sha256 "235f464b81026299661966f6185766753517094391907e049c7b977d1106c39d"

        def install
          bin.install "baton-outreach"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-outreach -v"
  end
end
