# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonBitbucketDatacenter < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-bitbucket-datacenter/releases/download/v0.1.15/baton-bitbucket-datacenter-v0.1.15-darwin-amd64.zip"
      sha256 "9c53962c4b3656d7177f55ddfe120dd84dbc2d14f99dc1236ffc0f89a409d3d5"

      def install
        bin.install "baton-bitbucket-datacenter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-bitbucket-datacenter/releases/download/v0.1.15/baton-bitbucket-datacenter-v0.1.15-darwin-arm64.zip"
      sha256 "808955085427054824047a2ad9294b340a6bc88ed303a67119f86e18b53be142"

      def install
        bin.install "baton-bitbucket-datacenter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-bitbucket-datacenter/releases/download/v0.1.15/baton-bitbucket-datacenter-v0.1.15-linux-amd64.tar.gz"
        sha256 "ec705d958bcc60af17bc6537e4bfe8bcff5feb40df61fe0111b1eebbf1ebf573"

        def install
          bin.install "baton-bitbucket-datacenter"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-bitbucket-datacenter/releases/download/v0.1.15/baton-bitbucket-datacenter-v0.1.15-linux-arm64.tar.gz"
        sha256 "321e427ed2c6c4453013c7fff211ad3011c8d9161dbc9599c4165610af9d9358"

        def install
          bin.install "baton-bitbucket-datacenter"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-bitbucket-datacenter -v"
  end
end
