# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonAdpWorkforceNow < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.19"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-adp-workforce-now/releases/download/v0.0.19/baton-adp-workforce-now-v0.0.19-darwin-amd64.zip"
      sha256 "1fcf11fd1bcd5b3fac3ee8808d4681afa51ad801cf559d6e5b8f2bb763bbb6bf"

      def install
        bin.install "baton-adp-workforce-now"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-adp-workforce-now/releases/download/v0.0.19/baton-adp-workforce-now-v0.0.19-darwin-arm64.zip"
      sha256 "8a45cd3196afeffc62cc8991597f8bef029a4625e1faab2f032eb2e18ae192db"

      def install
        bin.install "baton-adp-workforce-now"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-adp-workforce-now/releases/download/v0.0.19/baton-adp-workforce-now-v0.0.19-linux-amd64.tar.gz"
      sha256 "e0af04e4566f56d38b4f203c97f957ec19b9632ab3d19f1edf2c7f608d9b4941"
      def install
        bin.install "baton-adp-workforce-now"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-adp-workforce-now/releases/download/v0.0.19/baton-adp-workforce-now-v0.0.19-linux-arm64.tar.gz"
      sha256 "0ef2d02e9b3b2ea3c0a07335c059b0b90d3b3778b548240c13e70dc16874c469"
      def install
        bin.install "baton-adp-workforce-now"
      end
    end
  end

  test do
    system "#{bin}/baton-adp-workforce-now -v"
  end
end
