# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonOkta < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.9"

  on_macos do
    on_intel do
      url "https://github.com/ConductorOne/baton-okta/releases/download/v0.1.9/baton-okta-v0.1.9-darwin-amd64.zip"
      sha256 "303534fb1c7e34896ee93b387343509195faeba1ab42b97b59de91b847ed0b7e"

      def install
        bin.install "baton-okta"
      end
    end
    on_arm do
      url "https://github.com/ConductorOne/baton-okta/releases/download/v0.1.9/baton-okta-v0.1.9-darwin-arm64.zip"
      sha256 "a354a6002c6cd1e95ec7bdcfcd7f8b6094e80a56423c5ae4e9352904a62101b3"

      def install
        bin.install "baton-okta"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-okta/releases/download/v0.1.9/baton-okta-v0.1.9-linux-amd64.tar.gz"
        sha256 "37cba570a5a4891d84a3f3cc1b659af98c6efb7ae4b7cfb641bf5398de0223c1"

        def install
          bin.install "baton-okta"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/baton-okta/releases/download/v0.1.9/baton-okta-v0.1.9-linux-arm64.tar.gz"
        sha256 "0126763c1feef827390f666cfbecdcaa36c1f0cf65a0d9cfbf00757f6221aaae"

        def install
          bin.install "baton-okta"
        end
      end
    end
  end

  test do
    system "#{bin}/baton-okta -v"
  end
end
