# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonDatabricks < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-databricks/releases/download/v0.1.2/baton-databricks-v0.1.2-darwin-amd64.zip"
      sha256 "de3526b8bc4f7048825d74fbd25acd5434ce9d00fbeffc805f4ae72fda3d8f94"

      def install
        bin.install "baton-databricks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-databricks/releases/download/v0.1.2/baton-databricks-v0.1.2-darwin-arm64.zip"
      sha256 "79b3dac67466473e72c26ae7ef26665a4210c26831b0c72ef1f9b673d2a5c673"

      def install
        bin.install "baton-databricks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-databricks/releases/download/v0.1.2/baton-databricks-v0.1.2-linux-amd64.tar.gz"
      sha256 "51f81ae46bb8410d011eb3adf2bff28200da6112ab8600d0e961b12d22b7ec2c"
      def install
        bin.install "baton-databricks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-databricks/releases/download/v0.1.2/baton-databricks-v0.1.2-linux-arm64.tar.gz"
      sha256 "9b214e06b6e40db829353a12a91f15c4ae4d56ddac11c792cd742ad91be92556"
      def install
        bin.install "baton-databricks"
      end
    end
  end

  test do
    system "#{bin}/baton-databricks -v"
  end
end
