# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonAdpWorkforceNow < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-adp-workforce-now/releases/download/v0.0.3/baton-adp-workforce-now-v0.0.3-darwin-amd64.zip"
      sha256 "6af41bc026b4b227e9de9d848aa807a270764793d70df49b8b2655203beb0f05"

      def install
        bin.install "baton-adp-workforce-now"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-adp-workforce-now/releases/download/v0.0.3/baton-adp-workforce-now-v0.0.3-darwin-arm64.zip"
      sha256 "f8f805ebd12486c0b1daeece9d7323481632caa412a2537668f88f120faef45d"

      def install
        bin.install "baton-adp-workforce-now"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-adp-workforce-now/releases/download/v0.0.3/baton-adp-workforce-now-v0.0.3-linux-amd64.tar.gz"
      sha256 "e0d9824b4f8facc8b46968b073258f28fce1c98f9fc5c4f96ea742d14bf64317"
      def install
        bin.install "baton-adp-workforce-now"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-adp-workforce-now/releases/download/v0.0.3/baton-adp-workforce-now-v0.0.3-linux-arm64.tar.gz"
      sha256 "ff2cd1cea55760b4497abe72d9a3766f7e47643be95feb763405b0d2166624ee"
      def install
        bin.install "baton-adp-workforce-now"
      end
    end
  end

  test do
    system "#{bin}/baton-adp-workforce-now -v"
  end
end
