# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSlackEnterprise < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-slack-enterprise/releases/download/v0.0.13/baton-slack-enterprise-v0.0.13-darwin-amd64.zip"
      sha256 "0b55a49d8861d7fc3defabe9c1d61816809854511c4a059b5f4ee45ec8a7b0c7"

      def install
        bin.install "baton-slack-enterprise"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-slack-enterprise/releases/download/v0.0.13/baton-slack-enterprise-v0.0.13-darwin-arm64.zip"
      sha256 "c6fe21467abfffc8e02c999f0c099da7fb5c765b50eec03fcafe416ffa1a5d39"

      def install
        bin.install "baton-slack-enterprise"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-slack-enterprise/releases/download/v0.0.13/baton-slack-enterprise-v0.0.13-linux-amd64.tar.gz"
      sha256 "6161fbd2c9c5df3aa9c8b59b738ec6c7c01e21de6f9f58c511f9c2ae704b3152"
      def install
        bin.install "baton-slack-enterprise"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-slack-enterprise/releases/download/v0.0.13/baton-slack-enterprise-v0.0.13-linux-arm64.tar.gz"
      sha256 "bca444f464b2eb687d9f3e3a87b6d9d5e7196c38f5c0a897aadddcb821bb6ef4"
      def install
        bin.install "baton-slack-enterprise"
      end
    end
  end

  test do
    system "#{bin}/baton-slack-enterprise -v"
  end
end
