# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonNewrelic < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-newrelic/releases/download/v0.1.1/baton-newrelic-v0.1.1-darwin-amd64.zip"
      sha256 "37747bc4aa49936757707fc82115e084162983a45403fea6c12550bac78989fb"

      def install
        bin.install "baton-newrelic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-newrelic/releases/download/v0.1.1/baton-newrelic-v0.1.1-darwin-arm64.zip"
      sha256 "fa1404b91d1d78f892054de8532b17a546e81c6ad5d647b67b1e83e944dd0240"

      def install
        bin.install "baton-newrelic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-newrelic/releases/download/v0.1.1/baton-newrelic-v0.1.1-linux-amd64.tar.gz"
      sha256 "20735918bd836b9e887347ab4e2613be646f003a547b360b8493865e97de6fad"
      def install
        bin.install "baton-newrelic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-newrelic/releases/download/v0.1.1/baton-newrelic-v0.1.1-linux-arm64.tar.gz"
      sha256 "739349d6791793952884c40ad35b1806bced7ad2aae10888d66d1264916c9997"
      def install
        bin.install "baton-newrelic"
      end
    end
  end

  test do
    system "#{bin}/baton-newrelic -v"
  end
end
