# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonWorkday < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.1.10-test.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-workday/releases/download/v0.1.10-test.2/baton-workday-v0.1.10-test.2-darwin-amd64.zip"
      sha256 "b4b8b5fd868f55ffc5d33d7cbab58b0cfddd36a411535220ecc78379277c9097"

      def install
        bin.install "baton-workday"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-workday/releases/download/v0.1.10-test.2/baton-workday-v0.1.10-test.2-darwin-arm64.zip"
      sha256 "d22e8e7a3ab2877692d719d72959b01a3d115848b4f226499a2e84ac0b57bf82"

      def install
        bin.install "baton-workday"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-workday/releases/download/v0.1.10-test.2/baton-workday-v0.1.10-test.2-linux-amd64.tar.gz"
      sha256 "50cadb985520eddad0233b41b601d27321aac9e0f36f89e41d03317dc10b634c"
      def install
        bin.install "baton-workday"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-workday/releases/download/v0.1.10-test.2/baton-workday-v0.1.10-test.2-linux-arm64.tar.gz"
      sha256 "929252039b10002e1174a92584d05905e4949404033cafc0cda5396273969947"
      def install
        bin.install "baton-workday"
      end
    end
  end

  test do
    system "#{bin}/baton-workday -v"
  end
end
