# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonWizWin < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-wiz-win/releases/download/v0.0.1/baton-wiz-win-v0.0.1-darwin-amd64.zip"
      sha256 "c9815d1e8faba899bce77c8c1f30c89e8efe10f7c36dc5c0564bfd4b038e2836"

      def install
        bin.install "baton-wiz-win"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-wiz-win/releases/download/v0.0.1/baton-wiz-win-v0.0.1-darwin-arm64.zip"
      sha256 "d26894738ba8143fa1e3208408847dca793dfff14de56f5892e257e717dd25f4"

      def install
        bin.install "baton-wiz-win"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-wiz-win/releases/download/v0.0.1/baton-wiz-win-v0.0.1-linux-amd64.tar.gz"
      sha256 "23b57bb4387b56eb8a0da463f3e034b32fe6e9d979fdb57710c64831fe170304"
      def install
        bin.install "baton-wiz-win"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-wiz-win/releases/download/v0.0.1/baton-wiz-win-v0.0.1-linux-arm64.tar.gz"
      sha256 "c7d23739eeda5185573a4b303424fd66bc535f4558bd7e14390ac02c5eb42fde"
      def install
        bin.install "baton-wiz-win"
      end
    end
  end

  test do
    system "#{bin}/baton-wiz-win -v"
  end
end
