# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BatonSevenshifts < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/baton-sevenshifts/releases/download/v0.2.0/baton-sevenshifts-v0.2.0-darwin-amd64.zip"
      sha256 "8136636835c0a3637b62a12da6d65714afa80bf782d10362a0ef1686fe4ac5ac"

      def install
        bin.install "baton-sevenshifts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/baton-sevenshifts/releases/download/v0.2.0/baton-sevenshifts-v0.2.0-darwin-arm64.zip"
      sha256 "7d992e1406928fcaea5b112581075f5498df1b6c4efde6a1a96f433021e523ea"

      def install
        bin.install "baton-sevenshifts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-sevenshifts/releases/download/v0.2.0/baton-sevenshifts-v0.2.0-linux-amd64.tar.gz"
      sha256 "fe21724a10d73256ab1ef15579e92e1edd598391e1d08124f60ef49e446b9d2f"
      def install
        bin.install "baton-sevenshifts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/baton-sevenshifts/releases/download/v0.2.0/baton-sevenshifts-v0.2.0-linux-arm64.tar.gz"
      sha256 "0b20b5340e619756bc09e1ed34723396711f778d0d26d6918cce9e32dc4acf18"
      def install
        bin.install "baton-sevenshifts"
      end
    end
  end

  test do
    system "#{bin}/baton-sevenshifts -v"
  end
end
