# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BridgeClient < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/bridge-client/releases/download/v0.0.2/bridge-client-v0.0.2-darwin-amd64.zip"
      sha256 "15d9dfec38e2ec1f799e3e63026abf687abf4d9c114c378eb20deebef92bd6d5"

      def install
        bin.install "bridge-client"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/bridge-client/releases/download/v0.0.2/bridge-client-v0.0.2-darwin-arm64.zip"
      sha256 "7dfa3d33e1113b66e32ebc275361b110ab6c3b3d0604839ff3dd72260ef93b19"

      def install
        bin.install "bridge-client"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/bridge-client/releases/download/v0.0.2/bridge-client-v0.0.2-linux-amd64.tar.gz"
      sha256 "032dd6b8f56b99d782b032fec7583b6ccb8b4da956c3e59c0ca03c3a7f96afd9"
      def install
        bin.install "bridge-client"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/bridge-client/releases/download/v0.0.2/bridge-client-v0.0.2-linux-arm64.tar.gz"
      sha256 "ab64c0afe74808abbad33c942be11a5b53487af03e07e7a3b97909d2fedce96d"
      def install
        bin.install "bridge-client"
      end
    end
  end

  test do
    system "#{bin}/bridge-client -v"
  end
end
