# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class C1i < Formula
  desc ""
  homepage "https://conductorone.com"
  version "0.5.1-rc.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/c1i/releases/download/v0.5.1-rc.1/c1i-v0.5.1-rc.1-darwin-amd64.zip"
      sha256 "4b685498a43ff72c23610892026785f5528b1aeaf83a99b9e411af7a0a5ab3d7"

      def install
        bin.install "c1i"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/c1i/releases/download/v0.5.1-rc.1/c1i-v0.5.1-rc.1-darwin-arm64.zip"
      sha256 "6dbee648141c21cd72b401439f02be096d17de2608646e9b1be5d054cdfaee00"

      def install
        bin.install "c1i"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/c1i/releases/download/v0.5.1-rc.1/c1i-v0.5.1-rc.1-linux-amd64.tar.gz"
      sha256 "8251536b39929612c7e923c46cbf5c9c23153c267af0bcd43e906d1d5b7864c0"
      def install
        bin.install "c1i"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ConductorOne/c1i/releases/download/v0.5.1-rc.1/c1i-v0.5.1-rc.1-linux-arm64.tar.gz"
      sha256 "9444737aaec78c1a0948119ab8734b6988279b7092e7e302019e163258d65145"
      def install
        bin.install "c1i"
      end
    end
  end

  test do
    system "#{bin}/c1i -v"
  end
end
