# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlaidLint < Formula
  desc ""
  homepage "https://conductorone.com"
  version "1.0.0-rc.16"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/plaid-lint/releases/download/v1.0.0-rc.16/plaid-lint-v1.0.0-rc.16-darwin-amd64.zip"
      sha256 "2959a3b9cf18fb43148aca1ea3aa9727c8e18d474f415a90673b53438c87227d"

      def install
        bin.install "plaid-lint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/plaid-lint/releases/download/v1.0.0-rc.16/plaid-lint-v1.0.0-rc.16-darwin-arm64.zip"
      sha256 "68e7906778efcedb9fae5dcde2d9d31faf7fc6d640bc630966091963cf766f18"

      def install
        bin.install "plaid-lint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/plaid-lint/releases/download/v1.0.0-rc.16/plaid-lint-v1.0.0-rc.16-linux-amd64.tar.gz"
        sha256 "b245adfb3d9e406dfb4c48a58370e1bafd3e9c32217837c93fcd30daaf0a5735"

        def install
          bin.install "plaid-lint"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/plaid-lint/releases/download/v1.0.0-rc.16/plaid-lint-v1.0.0-rc.16-linux-arm64.tar.gz"
        sha256 "75f3baabcc753f1c26714a6b5d3082f74bcb78dd6e5495a42fda29a346acdced"

        def install
          bin.install "plaid-lint"
        end
      end
    end
  end

  test do
    system "#{bin}/plaid-lint -v"
  end
end
