# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlaidCache < Formula
  desc ""
  homepage "https://conductorone.com"
  version "1.0.0-rc.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ConductorOne/plaid-cache/releases/download/v1.0.0-rc.9/plaid-cache-v1.0.0-rc.9-darwin-amd64.zip"
      sha256 "64a6b9e53d8e60b86933b2a1e07237601d70fd8cef67a2e25dcb29ee8d2d262f"

      def install
        bin.install "plaid-cache"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ConductorOne/plaid-cache/releases/download/v1.0.0-rc.9/plaid-cache-v1.0.0-rc.9-darwin-arm64.zip"
      sha256 "49d9a7920719641b03604613eb57a1d9a69bcaad651fc46229ce7f10767f1267"

      def install
        bin.install "plaid-cache"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/plaid-cache/releases/download/v1.0.0-rc.9/plaid-cache-v1.0.0-rc.9-linux-amd64.tar.gz"
        sha256 "17cf9eaec934069cc31ad2e93f40fe3595e221fdd5d424b3278a333cb7baea00"

        def install
          bin.install "plaid-cache"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ConductorOne/plaid-cache/releases/download/v1.0.0-rc.9/plaid-cache-v1.0.0-rc.9-linux-arm64.tar.gz"
        sha256 "924dacf2aa0466e21c73ec341a500698a70bd46fefc9c80e08d943efa4c850f4"

        def install
          bin.install "plaid-cache"
        end
      end
    end
  end

  test do
    system "#{bin}/plaid-cache -v"
  end
end
